# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs\OTsUI_main.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OTsUI_main(object):
    def setupUi(self, OTsUI_main):
        OTsUI_main.setObjectName("OTsUI_main")
        OTsUI_main.resize(1157, 848)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OTsUI_main.sizePolicy().hasHeightForWidth())
        OTsUI_main.setSizePolicy(sizePolicy)
        self.mainGuiWid = QtWidgets.QWidget(OTsUI_main)
        self.mainGuiWid.setObjectName("mainGuiWid")
        self.mainGuiHor = QtWidgets.QHBoxLayout(self.mainGuiWid)
        self.mainGuiHor.setObjectName("mainGuiHor")
        self.conSavLogFrame = QtWidgets.QFrame(self.mainGuiWid)
        self.conSavLogFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.conSavLogFrame.setMaximumSize(QtCore.QSize(251, 16777215))
        self.conSavLogFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conSavLogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conSavLogFrame.setObjectName("conSavLogFrame")
        self.conSavLogVert = QtWidgets.QVBoxLayout(self.conSavLogFrame)
        self.conSavLogVert.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.conSavLogVert.setObjectName("conSavLogVert")
        self.connBox = QtWidgets.QGroupBox(self.conSavLogFrame)
        self.connBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.connBox.setObjectName("connBox")
        self.connBoxVert = QtWidgets.QVBoxLayout(self.connBox)
        self.connBoxVert.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.connBoxVert.setObjectName("connBoxVert")
        self.connForm = QtWidgets.QFormLayout()
        self.connForm.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.connForm.setObjectName("connForm")
        self.ipAddLine = QtWidgets.QLineEdit(self.connBox)
        self.ipAddLine.setObjectName("ipAddLine")
        self.connForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ipAddLine)
        self.ipAddLab = QtWidgets.QLabel(self.connBox)
        self.ipAddLab.setObjectName("ipAddLab")
        self.connForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ipAddLab)
        self.pubPortLine = QtWidgets.QLineEdit(self.connBox)
        self.pubPortLine.setObjectName("pubPortLine")
        self.connForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pubPortLine)
        self.portLab = QtWidgets.QLabel(self.connBox)
        self.portLab.setObjectName("portLab")
        self.connForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portLab)
        self.subPortLine = QtWidgets.QLineEdit(self.connBox)
        self.subPortLine.setObjectName("subPortLine")
        self.connForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.subPortLine)
        self.portLab_2 = QtWidgets.QLabel(self.connBox)
        self.portLab_2.setObjectName("portLab_2")
        self.connForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.portLab_2)
        self.connBoxVert.addLayout(self.connForm)
        self.connectBtn = QtWidgets.QPushButton(self.connBox)
        self.connectBtn.setObjectName("connectBtn")
        self.connBoxVert.addWidget(self.connectBtn)
        self.conSavLogVert.addWidget(self.connBox)
        self.saveBox = QtWidgets.QGroupBox(self.conSavLogFrame)
        self.saveBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.saveBox.setObjectName("saveBox")
        self.saveBoxVert = QtWidgets.QVBoxLayout(self.saveBox)
        self.saveBoxVert.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.saveBoxVert.setObjectName("saveBoxVert")
        self.saveGrid = QtWidgets.QGridLayout()
        self.saveGrid.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.saveGrid.setObjectName("saveGrid")
        self.dataDirBtn = QtWidgets.QPushButton(self.saveBox)
        self.dataDirBtn.setObjectName("dataDirBtn")
        self.saveGrid.addWidget(self.dataDirBtn, 1, 1, 1, 1)
        self.logDirBtn = QtWidgets.QPushButton(self.saveBox)
        self.logDirBtn.setObjectName("logDirBtn")
        self.saveGrid.addWidget(self.logDirBtn, 5, 1, 1, 1)
        self.dataDirLab = QtWidgets.QLabel(self.saveBox)
        self.dataDirLab.setObjectName("dataDirLab")
        self.saveGrid.addWidget(self.dataDirLab, 0, 0, 1, 1)
        self.logDirLab = QtWidgets.QLabel(self.saveBox)
        self.logDirLab.setObjectName("logDirLab")
        self.saveGrid.addWidget(self.logDirLab, 4, 0, 1, 1)
        self.dataDirLine = QtWidgets.QLineEdit(self.saveBox)
        self.dataDirLine.setObjectName("dataDirLine")
        self.saveGrid.addWidget(self.dataDirLine, 0, 1, 1, 1)
        self.logNameLab = QtWidgets.QLabel(self.saveBox)
        self.logNameLab.setObjectName("logNameLab")
        self.saveGrid.addWidget(self.logNameLab, 6, 0, 1, 1)
        self.logDirLine = QtWidgets.QLineEdit(self.saveBox)
        self.logDirLine.setObjectName("logDirLine")
        self.saveGrid.addWidget(self.logDirLine, 4, 1, 1, 1)
        self.logNameLine = QtWidgets.QLineEdit(self.saveBox)
        self.logNameLine.setObjectName("logNameLine")
        self.saveGrid.addWidget(self.logNameLine, 6, 1, 1, 1)
        self.dataNameLab = QtWidgets.QLabel(self.saveBox)
        self.dataNameLab.setObjectName("dataNameLab")
        self.saveGrid.addWidget(self.dataNameLab, 2, 0, 1, 1)
        self.dataNameLine = QtWidgets.QLineEdit(self.saveBox)
        self.dataNameLine.setObjectName("dataNameLine")
        self.saveGrid.addWidget(self.dataNameLine, 2, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.saveBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.saveGrid.addWidget(self.line_3, 3, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.saveBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.saveGrid.addWidget(self.line_4, 7, 0, 1, 2)
        self.saveGrid.setColumnStretch(0, 1)
        self.saveBoxVert.addLayout(self.saveGrid)
        self.conSavLogVert.addWidget(self.saveBox)
        self.logText = QtWidgets.QTextEdit(self.conSavLogFrame)
        self.logText.setMaximumSize(QtCore.QSize(300, 16777215))
        self.logText.setObjectName("logText")
        self.conSavLogVert.addWidget(self.logText)
        self.lockFbBtn = QtWidgets.QPushButton(self.conSavLogFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lockFbBtn.sizePolicy().hasHeightForWidth())
        self.lockFbBtn.setSizePolicy(sizePolicy)
        self.lockFbBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.lockFbBtn.setObjectName("lockFbBtn")
        self.conSavLogVert.addWidget(self.lockFbBtn)
        self.conSavLogVert.setStretch(0, 1)
        self.conSavLogVert.setStretch(1, 3)
        self.conSavLogVert.setStretch(2, 6)
        self.mainGuiHor.addWidget(self.conSavLogFrame)
        self.sysCtrlVert = QtWidgets.QVBoxLayout()
        self.sysCtrlVert.setObjectName("sysCtrlVert")
        self.plotNfbHor = QtWidgets.QHBoxLayout()
        self.plotNfbHor.setObjectName("plotNfbHor")
        self.plotTabs = QtWidgets.QTabWidget(self.mainGuiWid)
        self.plotTabs.setObjectName("plotTabs")
        self.signalPage = QtWidgets.QWidget()
        self.signalPage.setObjectName("signalPage")
        self.signalTabGrid = QtWidgets.QGridLayout(self.signalPage)
        self.signalTabGrid.setObjectName("signalTabGrid")
        self.sig2Plot = PlotWidget(self.signalPage)
        self.sig2Plot.setObjectName("sig2Plot")
        self.signalTabGrid.addWidget(self.sig2Plot, 2, 0, 1, 1)
        self.sig2selCmb = QtWidgets.QComboBox(self.signalPage)
        self.sig2selCmb.setObjectName("sig2selCmb")
        self.sig2selCmb.addItem("")
        self.sig2selCmb.addItem("")
        self.sig2selCmb.addItem("")
        self.signalTabGrid.addWidget(self.sig2selCmb, 3, 0, 1, 1)
        self.sig3Plot = PlotWidget(self.signalPage)
        self.sig3Plot.setObjectName("sig3Plot")
        self.signalTabGrid.addWidget(self.sig3Plot, 2, 1, 1, 1)
        self.sig3selCmb = QtWidgets.QComboBox(self.signalPage)
        self.sig3selCmb.setObjectName("sig3selCmb")
        self.sig3selCmb.addItem("")
        self.sig3selCmb.addItem("")
        self.sig3selCmb.addItem("")
        self.signalTabGrid.addWidget(self.sig3selCmb, 3, 1, 1, 1)
        self.sig1Plot = PlotWidget(self.signalPage)
        self.sig1Plot.setObjectName("sig1Plot")
        self.signalTabGrid.addWidget(self.sig1Plot, 0, 0, 1, 2)
        self.sig1selCmb = QtWidgets.QComboBox(self.signalPage)
        self.sig1selCmb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sig1selCmb.setObjectName("sig1selCmb")
        self.sig1selCmb.addItem("")
        self.sig1selCmb.addItem("")
        self.sig1selCmb.addItem("")
        self.signalTabGrid.addWidget(self.sig1selCmb, 1, 0, 1, 2)
        self.signalTabGrid.setRowStretch(0, 3)
        self.signalTabGrid.setRowStretch(1, 1)
        self.signalTabGrid.setRowStretch(2, 2)
        self.signalTabGrid.setRowStretch(3, 1)
        self.plotTabs.addTab(self.signalPage, "")
        self.psPage = QtWidgets.QWidget()
        self.psPage.setObjectName("psPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.psPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.powSpec1Plot = PlotWidget(self.psPage)
        self.powSpec1Plot.setObjectName("powSpec1Plot")
        self.verticalLayout.addWidget(self.powSpec1Plot)
        self.ps1selCmb = QtWidgets.QComboBox(self.psPage)
        self.ps1selCmb.setObjectName("ps1selCmb")
        self.ps1selCmb.addItem("")
        self.ps1selCmb.addItem("")
        self.ps1selCmb.addItem("")
        self.verticalLayout.addWidget(self.ps1selCmb)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.powSpec3Plot = PlotWidget(self.psPage)
        self.powSpec3Plot.setObjectName("powSpec3Plot")
        self.gridLayout.addWidget(self.powSpec3Plot, 0, 1, 1, 1)
        self.powSpec2Plot = PlotWidget(self.psPage)
        self.powSpec2Plot.setObjectName("powSpec2Plot")
        self.gridLayout.addWidget(self.powSpec2Plot, 0, 0, 1, 1)
        self.ps2selCmb = QtWidgets.QComboBox(self.psPage)
        self.ps2selCmb.setObjectName("ps2selCmb")
        self.ps2selCmb.addItem("")
        self.ps2selCmb.addItem("")
        self.ps2selCmb.addItem("")
        self.gridLayout.addWidget(self.ps2selCmb, 1, 0, 1, 1)
        self.ps3selCmb = QtWidgets.QComboBox(self.psPage)
        self.ps3selCmb.setObjectName("ps3selCmb")
        self.ps3selCmb.addItem("")
        self.ps3selCmb.addItem("")
        self.ps3selCmb.addItem("")
        self.gridLayout.addWidget(self.ps3selCmb, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2.setStretch(0, 7)
        self.verticalLayout_2.setStretch(1, 5)
        self.plotTabs.addTab(self.psPage, "")
        self.plotNfbHor.addWidget(self.plotTabs)
        self.fbFrame = QtWidgets.QFrame(self.mainGuiWid)
        self.fbFrame.setMinimumSize(QtCore.QSize(150, 0))
        self.fbFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fbFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fbFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fbFrame.setObjectName("fbFrame")
        self.fbFrameVert = QtWidgets.QVBoxLayout(self.fbFrame)
        self.fbFrameVert.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.fbFrameVert.setObjectName("fbFrameVert")
        self.fbToolBox = QtWidgets.QToolBox(self.fbFrame)
        self.fbToolBox.setMinimumSize(QtCore.QSize(150, 0))
        self.fbToolBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fbToolBox.setObjectName("fbToolBox")
        self.piPage = QtWidgets.QWidget()
        self.piPage.setGeometry(QtCore.QRect(0, 0, 180, 396))
        self.piPage.setObjectName("piPage")
        self.piGrid = QtWidgets.QGridLayout(self.piPage)
        self.piGrid.setObjectName("piGrid")
        self.xyINumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.xyINumDbl.setObjectName("xyINumDbl")
        self.piGrid.addWidget(self.xyINumDbl, 3, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.piPage)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.piGrid.addWidget(self.line_2, 4, 0, 1, 3)
        self.zLab = QtWidgets.QLabel(self.piPage)
        self.zLab.setObjectName("zLab")
        self.piGrid.addWidget(self.zLab, 5, 0, 1, 1)
        self.xyPNumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.xyPNumDbl.setObjectName("xyPNumDbl")
        self.piGrid.addWidget(self.xyPNumDbl, 1, 2, 1, 1)
        self.zIDial = QtWidgets.QDial(self.piPage)
        self.zIDial.setObjectName("zIDial")
        self.piGrid.addWidget(self.zIDial, 7, 1, 1, 1)
        self.xyFbOnCheck = QtWidgets.QCheckBox(self.piPage)
        self.xyFbOnCheck.setObjectName("xyFbOnCheck")
        self.piGrid.addWidget(self.xyFbOnCheck, 0, 1, 1, 1)
        self.setFbBtn = QtWidgets.QPushButton(self.piPage)
        self.setFbBtn.setObjectName("setFbBtn")
        self.piGrid.addWidget(self.setFbBtn, 8, 0, 1, 3)
        self.zPLab = QtWidgets.QLabel(self.piPage)
        self.zPLab.setObjectName("zPLab")
        self.piGrid.addWidget(self.zPLab, 6, 0, 1, 1)
        self.xyIDial = QtWidgets.QDial(self.piPage)
        self.xyIDial.setObjectName("xyIDial")
        self.piGrid.addWidget(self.xyIDial, 3, 1, 1, 1)
        self.zPDial = QtWidgets.QDial(self.piPage)
        self.zPDial.setObjectName("zPDial")
        self.piGrid.addWidget(self.zPDial, 6, 1, 1, 1)
        self.xyPDial = QtWidgets.QDial(self.piPage)
        self.xyPDial.setObjectName("xyPDial")
        self.piGrid.addWidget(self.xyPDial, 1, 1, 1, 1)
        self.zILab = QtWidgets.QLabel(self.piPage)
        self.zILab.setObjectName("zILab")
        self.piGrid.addWidget(self.zILab, 7, 0, 1, 1)
        self.zPNumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.zPNumDbl.setObjectName("zPNumDbl")
        self.piGrid.addWidget(self.zPNumDbl, 6, 2, 1, 1)
        self.xyLab = QtWidgets.QLabel(self.piPage)
        self.xyLab.setObjectName("xyLab")
        self.piGrid.addWidget(self.xyLab, 0, 0, 1, 1)
        self.xyILab = QtWidgets.QLabel(self.piPage)
        self.xyILab.setObjectName("xyILab")
        self.piGrid.addWidget(self.xyILab, 3, 0, 1, 1)
        self.xyPLab = QtWidgets.QLabel(self.piPage)
        self.xyPLab.setObjectName("xyPLab")
        self.piGrid.addWidget(self.xyPLab, 1, 0, 1, 1)
        self.zINumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.zINumDbl.setObjectName("zINumDbl")
        self.piGrid.addWidget(self.zINumDbl, 7, 2, 1, 1)
        self.zFbOnCheck = QtWidgets.QCheckBox(self.piPage)
        self.zFbOnCheck.setObjectName("zFbOnCheck")
        self.piGrid.addWidget(self.zFbOnCheck, 5, 1, 1, 1)
        self.piGrid.setColumnStretch(0, 1)
        self.fbToolBox.addItem(self.piPage, "")
        self.padPage = QtWidgets.QWidget()
        self.padPage.setGeometry(QtCore.QRect(0, 0, 180, 396))
        self.padPage.setObjectName("padPage")
        self.padVert = QtWidgets.QVBoxLayout(self.padPage)
        self.padVert.setObjectName("padVert")
        self.trapPadPlot = PlotWidget(self.padPage)
        self.trapPadPlot.setMaximumSize(QtCore.QSize(180, 180))
        self.trapPadPlot.setObjectName("trapPadPlot")
        self.padVert.addWidget(self.trapPadPlot)
        self.trapPadSpeedGrid = QtWidgets.QGridLayout()
        self.trapPadSpeedGrid.setObjectName("trapPadSpeedGrid")
        self.ySpeedTrapPadSlider = QtWidgets.QSlider(self.padPage)
        self.ySpeedTrapPadSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ySpeedTrapPadSlider.setObjectName("ySpeedTrapPadSlider")
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadSlider, 3, 0, 1, 1)
        self.xSpeedTrapPadLab = QtWidgets.QLabel(self.padPage)
        self.xSpeedTrapPadLab.setObjectName("xSpeedTrapPadLab")
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadLab, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem, 5, 0, 1, 1)
        self.ySpeedTrapPadLab = QtWidgets.QLabel(self.padPage)
        self.ySpeedTrapPadLab.setObjectName("ySpeedTrapPadLab")
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadLab, 2, 0, 1, 1)
        self.ySpeedTrapPadNumDbl = QtWidgets.QDoubleSpinBox(self.padPage)
        self.ySpeedTrapPadNumDbl.setObjectName("ySpeedTrapPadNumDbl")
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadNumDbl, 3, 1, 1, 1)
        self.xSpeedTrapPadNumDbl = QtWidgets.QDoubleSpinBox(self.padPage)
        self.xSpeedTrapPadNumDbl.setObjectName("xSpeedTrapPadNumDbl")
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadNumDbl, 1, 1, 1, 1)
        self.xSpeedTrapPadSlider = QtWidgets.QSlider(self.padPage)
        self.xSpeedTrapPadSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xSpeedTrapPadSlider.setObjectName("xSpeedTrapPadSlider")
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadSlider, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem3, 7, 0, 1, 1)
        self.trapPadSpeedGrid.setColumnStretch(0, 2)
        self.trapPadSpeedGrid.setRowStretch(0, 1)
        self.trapPadSpeedGrid.setRowStretch(2, 1)
        self.padVert.addLayout(self.trapPadSpeedGrid)
        self.padVert.setStretch(0, 2)
        self.padVert.setStretch(1, 2)
        self.fbToolBox.addItem(self.padPage, "")
        self.otherPage = QtWidgets.QWidget()
        self.otherPage.setGeometry(QtCore.QRect(0, 0, 180, 396))
        self.otherPage.setObjectName("otherPage")
        self.otherGrid = QtWidgets.QGridLayout(self.otherPage)
        self.otherGrid.setObjectName("otherGrid")
        self.yOffSetNumDbl = QtWidgets.QDoubleSpinBox(self.otherPage)
        self.yOffSetNumDbl.setObjectName("yOffSetNumDbl")
        self.otherGrid.addWidget(self.yOffSetNumDbl, 1, 2, 1, 1)
        self.yOffSetDial = QtWidgets.QDial(self.otherPage)
        self.yOffSetDial.setObjectName("yOffSetDial")
        self.otherGrid.addWidget(self.yOffSetDial, 1, 1, 1, 1)
        self.xOffSetDial = QtWidgets.QDial(self.otherPage)
        self.xOffSetDial.setObjectName("xOffSetDial")
        self.otherGrid.addWidget(self.xOffSetDial, 0, 1, 1, 1)
        self.xOffSetNumDbl = QtWidgets.QDoubleSpinBox(self.otherPage)
        self.xOffSetNumDbl.setObjectName("xOffSetNumDbl")
        self.otherGrid.addWidget(self.xOffSetNumDbl, 0, 2, 1, 1)
        self.zOffSetNumDbl = QtWidgets.QDoubleSpinBox(self.otherPage)
        self.zOffSetNumDbl.setObjectName("zOffSetNumDbl")
        self.otherGrid.addWidget(self.zOffSetNumDbl, 2, 2, 1, 1)
        self.zOffSetLab = QtWidgets.QLabel(self.otherPage)
        self.zOffSetLab.setObjectName("zOffSetLab")
        self.otherGrid.addWidget(self.zOffSetLab, 2, 0, 1, 1)
        self.zOffSetDial = QtWidgets.QDial(self.otherPage)
        self.zOffSetDial.setObjectName("zOffSetDial")
        self.otherGrid.addWidget(self.zOffSetDial, 2, 1, 1, 1)
        self.yOffSetLab = QtWidgets.QLabel(self.otherPage)
        self.yOffSetLab.setObjectName("yOffSetLab")
        self.otherGrid.addWidget(self.yOffSetLab, 1, 0, 1, 1)
        self.xOffSetLab = QtWidgets.QLabel(self.otherPage)
        self.xOffSetLab.setObjectName("xOffSetLab")
        self.otherGrid.addWidget(self.xOffSetLab, 0, 0, 1, 1)
        self.fbToolBox.addItem(self.otherPage, "")
        self.fbFrameVert.addWidget(self.fbToolBox)
        self.plotNfbHor.addWidget(self.fbFrame)
        self.plotNfbHor.setStretch(1, 2)
        self.sysCtrlVert.addLayout(self.plotNfbHor)
        self.posNmodHor = QtWidgets.QHBoxLayout()
        self.posNmodHor.setObjectName("posNmodHor")
        self.trapPosXYPlot = PlotWidget(self.mainGuiWid)
        self.trapPosXYPlot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trapPosXYPlot.sizePolicy().hasHeightForWidth())
        self.trapPosXYPlot.setSizePolicy(sizePolicy)
        self.trapPosXYPlot.setMinimumSize(QtCore.QSize(280, 280))
        self.trapPosXYPlot.setMaximumSize(QtCore.QSize(280, 280))
        self.trapPosXYPlot.setSizeIncrement(QtCore.QSize(0, 0))
        self.trapPosXYPlot.setObjectName("trapPosXYPlot")
        self.posNmodHor.addWidget(self.trapPosXYPlot)
        self.trapPosZPlot = PlotWidget(self.mainGuiWid)
        self.trapPosZPlot.setMinimumSize(QtCore.QSize(0, 280))
        self.trapPosZPlot.setMaximumSize(QtCore.QSize(71, 280))
        self.trapPosZPlot.setObjectName("trapPosZPlot")
        self.posNmodHor.addWidget(self.trapPosZPlot)
        self.modTabs = QtWidgets.QTabWidget(self.mainGuiWid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modTabs.sizePolicy().hasHeightForWidth())
        self.modTabs.setSizePolicy(sizePolicy)
        self.modTabs.setMinimumSize(QtCore.QSize(0, 280))
        self.modTabs.setMaximumSize(QtCore.QSize(16777215, 280))
        self.modTabs.setObjectName("modTabs")
        self.calibPage = QtWidgets.QWidget()
        self.calibPage.setObjectName("calibPage")
        self.calibTabHor = QtWidgets.QHBoxLayout(self.calibPage)
        self.calibTabHor.setObjectName("calibTabHor")
        self.calTypeTab = QtWidgets.QTabWidget(self.calibPage)
        self.calTypeTab.setObjectName("calTypeTab")
        self.calPassivePage = QtWidgets.QWidget()
        self.calPassivePage.setObjectName("calPassivePage")
        self.passiveCalForm = QtWidgets.QFormLayout(self.calPassivePage)
        self.passiveCalForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.passiveCalForm.setObjectName("passiveCalForm")
        self.passiveCalDurLab = QtWidgets.QLabel(self.calPassivePage)
        self.passiveCalDurLab.setObjectName("passiveCalDurLab")
        self.passiveCalForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passiveCalDurLab)
        self.passiveCalDurNumDbl = QtWidgets.QDoubleSpinBox(self.calPassivePage)
        self.passiveCalDurNumDbl.setObjectName("passiveCalDurNumDbl")
        self.passiveCalForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passiveCalDurNumDbl)
        self.passiveCalMaxFreqLab = QtWidgets.QLabel(self.calPassivePage)
        self.passiveCalMaxFreqLab.setObjectName("passiveCalMaxFreqLab")
        self.passiveCalForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passiveCalMaxFreqLab)
        self.passiveCalMaxFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calPassivePage)
        self.passiveCalMaxFreqNumDbl.setObjectName("passiveCalMaxFreqNumDbl")
        self.passiveCalForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passiveCalMaxFreqNumDbl)
        self.passiveCalAvgLav = QtWidgets.QLabel(self.calPassivePage)
        self.passiveCalAvgLav.setObjectName("passiveCalAvgLav")
        self.passiveCalForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passiveCalAvgLav)
        self.passiveCalAvgNum = QtWidgets.QSpinBox(self.calPassivePage)
        self.passiveCalAvgNum.setObjectName("passiveCalAvgNum")
        self.passiveCalForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passiveCalAvgNum)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.passiveCalForm.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.passiveCalForm.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.passiveCalStartBtn = QtWidgets.QPushButton(self.calPassivePage)
        self.passiveCalStartBtn.setObjectName("passiveCalStartBtn")
        self.passiveCalForm.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.passiveCalStartBtn)
        self.calTypeTab.addTab(self.calPassivePage, "")
        self.calActivePage = QtWidgets.QWidget()
        self.calActivePage.setObjectName("calActivePage")
        self.ativeCalVert = QtWidgets.QVBoxLayout(self.calActivePage)
        self.ativeCalVert.setObjectName("ativeCalVert")
        self.activeCalSinsConfGrid = QtWidgets.QGridLayout()
        self.activeCalSinsConfGrid.setObjectName("activeCalSinsConfGrid")
        self.activeCalYLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalYLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalYLab.setObjectName("activeCalYLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalYLab, 0, 2, 1, 1)
        self.activeCalZLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalZLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalZLab.setObjectName("activeCalZLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalZLab, 0, 3, 1, 1)
        self.activeCalAmpLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalAmpLab.setObjectName("activeCalAmpLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalAmpLab, 1, 0, 1, 1)
        self.activeCalXLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalXLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalXLab.setObjectName("activeCalXLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalXLab, 0, 1, 1, 1)
        self.activeCalFreqLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalFreqLab.setObjectName("activeCalFreqLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalFreqLab, 2, 0, 1, 1)
        self.activeCalXAmplNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalXAmplNumDbl.setObjectName("activeCalXAmplNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalXAmplNumDbl, 1, 1, 1, 1)
        self.activeCalYAmplNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalYAmplNumDbl.setObjectName("activeCalYAmplNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalYAmplNumDbl, 1, 2, 1, 1)
        self.activeCalZAmplNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalZAmplNumDbl.setObjectName("activeCalZAmplNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalZAmplNumDbl, 1, 3, 1, 1)
        self.activeCalXFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalXFreqNumDbl.setObjectName("activeCalXFreqNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalXFreqNumDbl, 2, 1, 1, 1)
        self.activeCalYFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalYFreqNumDbl.setObjectName("activeCalYFreqNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalYFreqNumDbl, 2, 2, 1, 1)
        self.activeCalZFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalZFreqNumDbl.setObjectName("activeCalZFreqNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalZFreqNumDbl, 2, 3, 1, 1)
        self.activeCalSinsConfGrid.setRowStretch(1, 3)
        self.activeCalSinsConfGrid.setRowStretch(2, 2)
        self.ativeCalVert.addLayout(self.activeCalSinsConfGrid)
        self.activeConfForm = QtWidgets.QFormLayout()
        self.activeConfForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.activeConfForm.setObjectName("activeConfForm")
        self.activeCalDurLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalDurLab.setObjectName("activeCalDurLab")
        self.activeConfForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.activeCalDurLab)
        self.activeCalDurNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalDurNumDbl.setObjectName("activeCalDurNumDbl")
        self.activeConfForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.activeCalDurNumDbl)
        self.activeCalMaxFreqLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalMaxFreqLab.setObjectName("activeCalMaxFreqLab")
        self.activeConfForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.activeCalMaxFreqLab)
        self.activeCalMaxFreqNumDbl = QtWidgets.QDoubleSpinBox(self.calActivePage)
        self.activeCalMaxFreqNumDbl.setObjectName("activeCalMaxFreqNumDbl")
        self.activeConfForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.activeCalMaxFreqNumDbl)
        self.activeCalAvgLab = QtWidgets.QLabel(self.calActivePage)
        self.activeCalAvgLab.setObjectName("activeCalAvgLab")
        self.activeConfForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.activeCalAvgLab)
        self.activeCalAvgNum = QtWidgets.QSpinBox(self.calActivePage)
        self.activeCalAvgNum.setObjectName("activeCalAvgNum")
        self.activeConfForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.activeCalAvgNum)
        self.ativeCalVert.addLayout(self.activeConfForm)
        self.activeCalStartBtn = QtWidgets.QPushButton(self.calActivePage)
        self.activeCalStartBtn.setObjectName("activeCalStartBtn")
        self.ativeCalVert.addWidget(self.activeCalStartBtn)
        self.ativeCalVert.setStretch(0, 1)
        self.ativeCalVert.setStretch(1, 1)
        self.calTypeTab.addTab(self.calActivePage, "")
        self.calibTabHor.addWidget(self.calTypeTab)
        self.genParVert = QtWidgets.QVBoxLayout()
        self.genParVert.setObjectName("genParVert")
        self.genParBox = QtWidgets.QGroupBox(self.calibPage)
        self.genParBox.setObjectName("genParBox")
        self.genParForm = QtWidgets.QFormLayout(self.genParBox)
        self.genParForm.setObjectName("genParForm")
        self.radiusNumDbl = QtWidgets.QDoubleSpinBox(self.genParBox)
        self.radiusNumDbl.setObjectName("radiusNumDbl")
        self.genParForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radiusNumDbl)
        self.dynViscNumDbl = QtWidgets.QDoubleSpinBox(self.genParBox)
        self.dynViscNumDbl.setObjectName("dynViscNumDbl")
        self.genParForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dynViscNumDbl)
        self.dynViscLab = QtWidgets.QLabel(self.genParBox)
        self.dynViscLab.setObjectName("dynViscLab")
        self.genParForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dynViscLab)
        self.radiusLab = QtWidgets.QLabel(self.genParBox)
        self.radiusLab.setObjectName("radiusLab")
        self.genParForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radiusLab)
        self.genParVert.addWidget(self.genParBox)
        self.calibTabHor.addLayout(self.genParVert)
        self.calResultsBox = QtWidgets.QGroupBox(self.calibPage)
        self.calResultsBox.setObjectName("calResultsBox")
        self.formLayout_7 = QtWidgets.QFormLayout(self.calResultsBox)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.kxLab = QtWidgets.QLabel(self.calResultsBox)
        self.kxLab.setObjectName("kxLab")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kxLab)
        self.kxNumDbl = QtWidgets.QDoubleSpinBox(self.calResultsBox)
        self.kxNumDbl.setObjectName("kxNumDbl")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kxNumDbl)
        self.kyLab = QtWidgets.QLabel(self.calResultsBox)
        self.kyLab.setObjectName("kyLab")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kyLab)
        self.kyNumDbl = QtWidgets.QDoubleSpinBox(self.calResultsBox)
        self.kyNumDbl.setObjectName("kyNumDbl")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kyNumDbl)
        self.kzLab = QtWidgets.QLabel(self.calResultsBox)
        self.kzLab.setObjectName("kzLab")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.kzLab)
        self.kzNumDbl = QtWidgets.QDoubleSpinBox(self.calResultsBox)
        self.kzNumDbl.setObjectName("kzNumDbl")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kzNumDbl)
        self.SxNumDbl = QtWidgets.QDoubleSpinBox(self.calResultsBox)
        self.SxNumDbl.setObjectName("SxNumDbl")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SxNumDbl)
        self.SyNumDbl = QtWidgets.QDoubleSpinBox(self.calResultsBox)
        self.SyNumDbl.setObjectName("SyNumDbl")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SyNumDbl)
        self.SzNumDbl = QtWidgets.QDoubleSpinBox(self.calResultsBox)
        self.SzNumDbl.setObjectName("SzNumDbl")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.SzNumDbl)
        self.SxLab = QtWidgets.QLabel(self.calResultsBox)
        self.SxLab.setObjectName("SxLab")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.SxLab)
        self.SyLab = QtWidgets.QLabel(self.calResultsBox)
        self.SyLab.setObjectName("SyLab")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.SyLab)
        self.SzLab = QtWidgets.QLabel(self.calResultsBox)
        self.SzLab.setObjectName("SzLab")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.SzLab)
        self.calibTabHor.addWidget(self.calResultsBox)
        self.calibTabHor.setStretch(1, 2)
        self.calibTabHor.setStretch(2, 2)
        self.modTabs.addTab(self.calibPage, "")
        self.stdExpPage = QtWidgets.QWidget()
        self.stdExpPage.setObjectName("stdExpPage")
        self.stdExpHor = QtWidgets.QHBoxLayout(self.stdExpPage)
        self.stdExpHor.setObjectName("stdExpHor")
        self.stdExpConfigGrid = QtWidgets.QGridLayout()
        self.stdExpConfigGrid.setObjectName("stdExpConfigGrid")
        self.stdExpDurNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpPage)
        self.stdExpDurNumDbl.setObjectName("stdExpDurNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpDurNumDbl, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.stdExpPage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stdExpConfigGrid.addWidget(self.line, 4, 0, 1, 3)
        self.stdExpXLab = QtWidgets.QLabel(self.stdExpPage)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.stdExpXLab.setFont(font)
        self.stdExpXLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpXLab.setObjectName("stdExpXLab")
        self.stdExpConfigGrid.addWidget(self.stdExpXLab, 1, 0, 1, 1)
        self.stdExpSetPointLab = QtWidgets.QLabel(self.stdExpPage)
        self.stdExpSetPointLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpSetPointLab.setObjectName("stdExpSetPointLab")
        self.stdExpConfigGrid.addWidget(self.stdExpSetPointLab, 0, 1, 1, 1)
        self.stdExpXSetPntNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpPage)
        self.stdExpXSetPntNumDbl.setObjectName("stdExpXSetPntNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpXSetPntNumDbl, 1, 1, 1, 1)
        self.stdExpAxisLab = QtWidgets.QLabel(self.stdExpPage)
        self.stdExpAxisLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpAxisLab.setObjectName("stdExpAxisLab")
        self.stdExpConfigGrid.addWidget(self.stdExpAxisLab, 0, 0, 1, 1)
        self.stdExpZSetPntNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpPage)
        self.stdExpZSetPntNumDbl.setObjectName("stdExpZSetPntNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpZSetPntNumDbl, 3, 1, 1, 1)
        self.stdExpZLab = QtWidgets.QLabel(self.stdExpPage)
        self.stdExpZLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpZLab.setObjectName("stdExpZLab")
        self.stdExpConfigGrid.addWidget(self.stdExpZLab, 3, 0, 1, 1)
        self.stdExpYEqForceVsMaxLine = QtWidgets.QLineEdit(self.stdExpPage)
        self.stdExpYEqForceVsMaxLine.setObjectName("stdExpYEqForceVsMaxLine")
        self.stdExpConfigGrid.addWidget(self.stdExpYEqForceVsMaxLine, 2, 2, 1, 1)
        self.stdExpXEqForceVsMaxLine = QtWidgets.QLineEdit(self.stdExpPage)
        self.stdExpXEqForceVsMaxLine.setObjectName("stdExpXEqForceVsMaxLine")
        self.stdExpConfigGrid.addWidget(self.stdExpXEqForceVsMaxLine, 1, 2, 1, 1)
        self.stdExpYSetPntNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpPage)
        self.stdExpYSetPntNumDbl.setObjectName("stdExpYSetPntNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpYSetPntNumDbl, 2, 1, 1, 1)
        self.stdExpEqForceVsMaxLab = QtWidgets.QLabel(self.stdExpPage)
        self.stdExpEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpEqForceVsMaxLab.setObjectName("stdExpEqForceVsMaxLab")
        self.stdExpConfigGrid.addWidget(self.stdExpEqForceVsMaxLab, 0, 2, 1, 1)
        self.stdExpYLab = QtWidgets.QLabel(self.stdExpPage)
        self.stdExpYLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpYLab.setObjectName("stdExpYLab")
        self.stdExpConfigGrid.addWidget(self.stdExpYLab, 2, 0, 1, 1)
        self.stdExpZEqForceVsMaxLine = QtWidgets.QLineEdit(self.stdExpPage)
        self.stdExpZEqForceVsMaxLine.setObjectName("stdExpZEqForceVsMaxLine")
        self.stdExpConfigGrid.addWidget(self.stdExpZEqForceVsMaxLine, 3, 2, 1, 1)
        self.stdExpDurLab = QtWidgets.QLabel(self.stdExpPage)
        self.stdExpDurLab.setObjectName("stdExpDurLab")
        self.stdExpConfigGrid.addWidget(self.stdExpDurLab, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.stdExpConfigGrid.addItem(spacerItem6, 6, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.stdExpConfigGrid.addItem(spacerItem7, 7, 1, 1, 1)
        self.stdExpConfigGrid.setColumnStretch(0, 1)
        self.stdExpConfigGrid.setColumnStretch(1, 2)
        self.stdExpConfigGrid.setColumnStretch(2, 2)
        self.stdExpConfigGrid.setRowStretch(0, 1)
        self.stdExpConfigGrid.setRowStretch(1, 1)
        self.stdExpConfigGrid.setRowStretch(2, 1)
        self.stdExpConfigGrid.setRowStretch(3, 1)
        self.stdExpConfigGrid.setRowStretch(4, 1)
        self.stdExpHor.addLayout(self.stdExpConfigGrid)
        self.fbSchedVert = QtWidgets.QVBoxLayout()
        self.fbSchedVert.setObjectName("fbSchedVert")
        self.fbSchedBox = QtWidgets.QGroupBox(self.stdExpPage)
        self.fbSchedBox.setObjectName("fbSchedBox")
        self.formLayout_12 = QtWidgets.QFormLayout(self.fbSchedBox)
        self.formLayout_12.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName("formLayout_12")
        self.fbSchedNumIntLab = QtWidgets.QLabel(self.fbSchedBox)
        self.fbSchedNumIntLab.setObjectName("fbSchedNumIntLab")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fbSchedNumIntLab)
        self.fbSchedNumIntNum = QtWidgets.QSpinBox(self.fbSchedBox)
        self.fbSchedNumIntNum.setObjectName("fbSchedNumIntNum")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fbSchedNumIntNum)
        self.fbSchedOnDurLab = QtWidgets.QLabel(self.fbSchedBox)
        self.fbSchedOnDurLab.setObjectName("fbSchedOnDurLab")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fbSchedOnDurLab)
        self.fbSchedOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.fbSchedBox)
        self.fbSchedOnDurNumDbl.setObjectName("fbSchedOnDurNumDbl")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fbSchedOnDurNumDbl)
        self.fbSchedOffDurLab = QtWidgets.QLabel(self.fbSchedBox)
        self.fbSchedOffDurLab.setObjectName("fbSchedOffDurLab")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fbSchedOffDurLab)
        self.fbSchedOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.fbSchedBox)
        self.fbSchedOffDurNumDbl.setObjectName("fbSchedOffDurNumDbl")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fbSchedOffDurNumDbl)
        self.fbSchedStartOnCheck = QtWidgets.QCheckBox(self.fbSchedBox)
        self.fbSchedStartOnCheck.setTristate(False)
        self.fbSchedStartOnCheck.setObjectName("fbSchedStartOnCheck")
        self.formLayout_12.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fbSchedStartOnCheck)
        self.fbSchedVert.addWidget(self.fbSchedBox)
        self.stdExpStartBtn = QtWidgets.QPushButton(self.stdExpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdExpStartBtn.sizePolicy().hasHeightForWidth())
        self.stdExpStartBtn.setSizePolicy(sizePolicy)
        self.stdExpStartBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.stdExpStartBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stdExpStartBtn.setObjectName("stdExpStartBtn")
        self.fbSchedVert.addWidget(self.stdExpStartBtn)
        self.fbSchedVert.setStretch(0, 1)
        self.fbSchedVert.setStretch(1, 1)
        self.stdExpHor.addLayout(self.fbSchedVert)
        self.stdExpHor.setStretch(0, 3)
        self.stdExpHor.setStretch(1, 2)
        self.modTabs.addTab(self.stdExpPage, "")
        self.custExpPage = QtWidgets.QWidget()
        self.custExpPage.setObjectName("custExpPage")
        self.custExpVert = QtWidgets.QVBoxLayout(self.custExpPage)
        self.custExpVert.setObjectName("custExpVert")
        self.customExpAxisTabs = QtWidgets.QTabWidget(self.custExpPage)
        self.customExpAxisTabs.setObjectName("customExpAxisTabs")
        self.customExpXPage = QtWidgets.QWidget()
        self.customExpXPage.setObjectName("customExpXPage")
        self.custExpXVert = QtWidgets.QVBoxLayout(self.customExpXPage)
        self.custExpXVert.setObjectName("custExpXVert")
        self.customExpXConfGrid = QtWidgets.QGridLayout()
        self.customExpXConfGrid.setObjectName("customExpXConfGrid")
        self.customExpXOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXOnDurNumDbl.setObjectName("customExpXOnDurNumDbl")
        self.customExpXConfGrid.addWidget(self.customExpXOnDurNumDbl, 2, 1, 1, 1)
        self.customExpXMultiIntCheck = QtWidgets.QCheckBox(self.customExpXPage)
        self.customExpXMultiIntCheck.setObjectName("customExpXMultiIntCheck")
        self.customExpXConfGrid.addWidget(self.customExpXMultiIntCheck, 0, 0, 1, 1)
        self.customExpXNumIntLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXNumIntLab.setObjectName("customExpXNumIntLab")
        self.customExpXConfGrid.addWidget(self.customExpXNumIntLab, 1, 0, 1, 1)
        self.customExpXOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXOffDurNumDbl.setObjectName("customExpXOffDurNumDbl")
        self.customExpXConfGrid.addWidget(self.customExpXOffDurNumDbl, 3, 1, 1, 1)
        self.customExpXOnDurLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXOnDurLab.setObjectName("customExpXOnDurLab")
        self.customExpXConfGrid.addWidget(self.customExpXOnDurLab, 2, 0, 1, 1)
        self.customExpXOffDurLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXOffDurLab.setObjectName("customExpXOffDurLab")
        self.customExpXConfGrid.addWidget(self.customExpXOffDurLab, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpXConfGrid.addItem(spacerItem8, 2, 2, 1, 1)
        self.customExpXStartOnCheck = QtWidgets.QCheckBox(self.customExpXPage)
        self.customExpXStartOnCheck.setObjectName("customExpXStartOnCheck")
        self.customExpXConfGrid.addWidget(self.customExpXStartOnCheck, 4, 0, 1, 1)
        self.customExpXNumIntNum = QtWidgets.QSpinBox(self.customExpXPage)
        self.customExpXNumIntNum.setObjectName("customExpXNumIntNum")
        self.customExpXConfGrid.addWidget(self.customExpXNumIntNum, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpXConfGrid.addItem(spacerItem9, 2, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpXConfGrid.addItem(spacerItem10, 2, 4, 1, 1)
        self.customExpXConfGrid.setColumnStretch(0, 1)
        self.customExpXConfGrid.setColumnStretch(1, 1)
        self.customExpXConfGrid.setColumnStretch(2, 1)
        self.customExpXConfGrid.setColumnStretch(3, 1)
        self.customExpXConfGrid.setColumnStretch(4, 1)
        self.custExpXVert.addLayout(self.customExpXConfGrid)
        self.customExpXWFGrid = QtWidgets.QGridLayout()
        self.customExpXWFGrid.setObjectName("customExpXWFGrid")
        self.customExpXAmplNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXAmplNumDbl.setObjectName("customExpXAmplNumDbl")
        self.customExpXWFGrid.addWidget(self.customExpXAmplNumDbl, 1, 2, 1, 1)
        self.customExpXWFLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXWFLab.setObjectName("customExpXWFLab")
        self.customExpXWFGrid.addWidget(self.customExpXWFLab, 0, 0, 1, 1)
        self.customExpXFreqLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXFreqLab.setObjectName("customExpXFreqLab")
        self.customExpXWFGrid.addWidget(self.customExpXFreqLab, 0, 1, 1, 1)
        self.customExpXAmplLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXAmplLab.setObjectName("customExpXAmplLab")
        self.customExpXWFGrid.addWidget(self.customExpXAmplLab, 0, 2, 1, 1)
        self.customExpXFreqNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXFreqNumDbl.setObjectName("customExpXFreqNumDbl")
        self.customExpXWFGrid.addWidget(self.customExpXFreqNumDbl, 1, 1, 1, 1)
        self.customExpXWFCmb = QtWidgets.QComboBox(self.customExpXPage)
        self.customExpXWFCmb.setObjectName("customExpXWFCmb")
        self.customExpXWFGrid.addWidget(self.customExpXWFCmb, 1, 0, 1, 1)
        self.customExpXEqForceVsMaxLine = QtWidgets.QLineEdit(self.customExpXPage)
        self.customExpXEqForceVsMaxLine.setObjectName("customExpXEqForceVsMaxLine")
        self.customExpXWFGrid.addWidget(self.customExpXEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpXEqForceVsMaxLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXEqForceVsMaxLab.setObjectName("customExpXEqForceVsMaxLab")
        self.customExpXWFGrid.addWidget(self.customExpXEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpXWFGrid.setColumnStretch(0, 2)
        self.customExpXWFGrid.setColumnStretch(1, 1)
        self.customExpXWFGrid.setColumnStretch(2, 1)
        self.customExpXWFGrid.setColumnStretch(3, 1)
        self.custExpXVert.addLayout(self.customExpXWFGrid)
        self.custExpXVert.setStretch(0, 1)
        self.custExpXVert.setStretch(1, 1)
        self.customExpAxisTabs.addTab(self.customExpXPage, "")
        self.customExpYPage = QtWidgets.QWidget()
        self.customExpYPage.setObjectName("customExpYPage")
        self.custExpYVert = QtWidgets.QVBoxLayout(self.customExpYPage)
        self.custExpYVert.setObjectName("custExpYVert")
        self.customExpYConfGrid = QtWidgets.QGridLayout()
        self.customExpYConfGrid.setObjectName("customExpYConfGrid")
        self.customExpYNumIntNum = QtWidgets.QSpinBox(self.customExpYPage)
        self.customExpYNumIntNum.setObjectName("customExpYNumIntNum")
        self.customExpYConfGrid.addWidget(self.customExpYNumIntNum, 1, 1, 1, 1)
        self.customExpYOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYOnDurNumDbl.setObjectName("customExpYOnDurNumDbl")
        self.customExpYConfGrid.addWidget(self.customExpYOnDurNumDbl, 2, 1, 1, 1)
        self.customExpYStartOnCheck = QtWidgets.QCheckBox(self.customExpYPage)
        self.customExpYStartOnCheck.setObjectName("customExpYStartOnCheck")
        self.customExpYConfGrid.addWidget(self.customExpYStartOnCheck, 4, 0, 1, 1)
        self.customExpYNumIntLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYNumIntLab.setObjectName("customExpYNumIntLab")
        self.customExpYConfGrid.addWidget(self.customExpYNumIntLab, 1, 0, 1, 1)
        self.customExpYOffDurLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYOffDurLab.setObjectName("customExpYOffDurLab")
        self.customExpYConfGrid.addWidget(self.customExpYOffDurLab, 3, 0, 1, 1)
        self.customExpYOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYOffDurNumDbl.setObjectName("customExpYOffDurNumDbl")
        self.customExpYConfGrid.addWidget(self.customExpYOffDurNumDbl, 3, 1, 1, 1)
        self.customExpYOnDurLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYOnDurLab.setObjectName("customExpYOnDurLab")
        self.customExpYConfGrid.addWidget(self.customExpYOnDurLab, 2, 0, 1, 1)
        self.customExpYMultiIntCheck = QtWidgets.QCheckBox(self.customExpYPage)
        self.customExpYMultiIntCheck.setObjectName("customExpYMultiIntCheck")
        self.customExpYConfGrid.addWidget(self.customExpYMultiIntCheck, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpYConfGrid.addItem(spacerItem11, 2, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpYConfGrid.addItem(spacerItem12, 2, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpYConfGrid.addItem(spacerItem13, 2, 4, 1, 1)
        self.customExpYConfGrid.setColumnStretch(0, 1)
        self.customExpYConfGrid.setColumnStretch(1, 1)
        self.customExpYConfGrid.setColumnStretch(2, 1)
        self.customExpYConfGrid.setColumnStretch(3, 1)
        self.customExpYConfGrid.setColumnStretch(4, 1)
        self.custExpYVert.addLayout(self.customExpYConfGrid)
        self.customExpYWFGrid = QtWidgets.QGridLayout()
        self.customExpYWFGrid.setObjectName("customExpYWFGrid")
        self.customExpYAmplNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYAmplNumDbl.setObjectName("customExpYAmplNumDbl")
        self.customExpYWFGrid.addWidget(self.customExpYAmplNumDbl, 1, 2, 1, 1)
        self.customExpYWFLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYWFLab.setObjectName("customExpYWFLab")
        self.customExpYWFGrid.addWidget(self.customExpYWFLab, 0, 0, 1, 1)
        self.customExpYFreqLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYFreqLab.setObjectName("customExpYFreqLab")
        self.customExpYWFGrid.addWidget(self.customExpYFreqLab, 0, 1, 1, 1)
        self.customExpYAmplLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYAmplLab.setObjectName("customExpYAmplLab")
        self.customExpYWFGrid.addWidget(self.customExpYAmplLab, 0, 2, 1, 1)
        self.customExpYFreqNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYFreqNumDbl.setObjectName("customExpYFreqNumDbl")
        self.customExpYWFGrid.addWidget(self.customExpYFreqNumDbl, 1, 1, 1, 1)
        self.customExpYWFCmb = QtWidgets.QComboBox(self.customExpYPage)
        self.customExpYWFCmb.setObjectName("customExpYWFCmb")
        self.customExpYWFGrid.addWidget(self.customExpYWFCmb, 1, 0, 1, 1)
        self.customExpYEqForceVsMaxLine = QtWidgets.QLineEdit(self.customExpYPage)
        self.customExpYEqForceVsMaxLine.setObjectName("customExpYEqForceVsMaxLine")
        self.customExpYWFGrid.addWidget(self.customExpYEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpYEqForceVsMaxLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYEqForceVsMaxLab.setObjectName("customExpYEqForceVsMaxLab")
        self.customExpYWFGrid.addWidget(self.customExpYEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpYWFGrid.setColumnStretch(0, 2)
        self.customExpYWFGrid.setColumnStretch(1, 1)
        self.customExpYWFGrid.setColumnStretch(2, 1)
        self.customExpYWFGrid.setColumnStretch(3, 1)
        self.custExpYVert.addLayout(self.customExpYWFGrid)
        self.custExpYVert.setStretch(0, 1)
        self.custExpYVert.setStretch(1, 1)
        self.customExpAxisTabs.addTab(self.customExpYPage, "")
        self.customExpZPage = QtWidgets.QWidget()
        self.customExpZPage.setObjectName("customExpZPage")
        self.custExpZVert = QtWidgets.QVBoxLayout(self.customExpZPage)
        self.custExpZVert.setObjectName("custExpZVert")
        self.customExpZConfGrid = QtWidgets.QGridLayout()
        self.customExpZConfGrid.setObjectName("customExpZConfGrid")
        self.customExpZMultiIntCheck = QtWidgets.QCheckBox(self.customExpZPage)
        self.customExpZMultiIntCheck.setObjectName("customExpZMultiIntCheck")
        self.customExpZConfGrid.addWidget(self.customExpZMultiIntCheck, 0, 0, 1, 1)
        self.customExpZOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZOnDurNumDbl.setObjectName("customExpZOnDurNumDbl")
        self.customExpZConfGrid.addWidget(self.customExpZOnDurNumDbl, 2, 1, 1, 1)
        self.customExpZOnDurLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZOnDurLab.setObjectName("customExpZOnDurLab")
        self.customExpZConfGrid.addWidget(self.customExpZOnDurLab, 2, 0, 1, 1)
        self.customExpZStartOnCheck = QtWidgets.QCheckBox(self.customExpZPage)
        self.customExpZStartOnCheck.setObjectName("customExpZStartOnCheck")
        self.customExpZConfGrid.addWidget(self.customExpZStartOnCheck, 4, 0, 1, 1)
        self.customExpZOffDurLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZOffDurLab.setObjectName("customExpZOffDurLab")
        self.customExpZConfGrid.addWidget(self.customExpZOffDurLab, 3, 0, 1, 1)
        self.customExpZNumIntLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZNumIntLab.setObjectName("customExpZNumIntLab")
        self.customExpZConfGrid.addWidget(self.customExpZNumIntLab, 1, 0, 1, 1)
        self.customExpZOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZOffDurNumDbl.setObjectName("customExpZOffDurNumDbl")
        self.customExpZConfGrid.addWidget(self.customExpZOffDurNumDbl, 3, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpZConfGrid.addItem(spacerItem14, 2, 2, 1, 1)
        self.customExpZNumIntNum = QtWidgets.QSpinBox(self.customExpZPage)
        self.customExpZNumIntNum.setObjectName("customExpZNumIntNum")
        self.customExpZConfGrid.addWidget(self.customExpZNumIntNum, 1, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpZConfGrid.addItem(spacerItem15, 2, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpZConfGrid.addItem(spacerItem16, 2, 4, 1, 1)
        self.customExpZConfGrid.setColumnStretch(0, 1)
        self.customExpZConfGrid.setColumnStretch(1, 1)
        self.customExpZConfGrid.setColumnStretch(2, 1)
        self.customExpZConfGrid.setColumnStretch(3, 1)
        self.customExpZConfGrid.setColumnStretch(4, 1)
        self.custExpZVert.addLayout(self.customExpZConfGrid)
        self.customExpZWFGrid = QtWidgets.QGridLayout()
        self.customExpZWFGrid.setObjectName("customExpZWFGrid")
        self.customExpZAmplNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZAmplNumDbl.setObjectName("customExpZAmplNumDbl")
        self.customExpZWFGrid.addWidget(self.customExpZAmplNumDbl, 1, 2, 1, 1)
        self.customExpZWFLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZWFLab.setObjectName("customExpZWFLab")
        self.customExpZWFGrid.addWidget(self.customExpZWFLab, 0, 0, 1, 1)
        self.customExpZFreqLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZFreqLab.setObjectName("customExpZFreqLab")
        self.customExpZWFGrid.addWidget(self.customExpZFreqLab, 0, 1, 1, 1)
        self.customExpZAmplLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZAmplLab.setObjectName("customExpZAmplLab")
        self.customExpZWFGrid.addWidget(self.customExpZAmplLab, 0, 2, 1, 1)
        self.customExpZFreqNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZFreqNumDbl.setObjectName("customExpZFreqNumDbl")
        self.customExpZWFGrid.addWidget(self.customExpZFreqNumDbl, 1, 1, 1, 1)
        self.customExpZWFCmb = QtWidgets.QComboBox(self.customExpZPage)
        self.customExpZWFCmb.setObjectName("customExpZWFCmb")
        self.customExpZWFGrid.addWidget(self.customExpZWFCmb, 1, 0, 1, 1)
        self.customExpZEqForceVsMaxLine = QtWidgets.QLineEdit(self.customExpZPage)
        self.customExpZEqForceVsMaxLine.setObjectName("customExpZEqForceVsMaxLine")
        self.customExpZWFGrid.addWidget(self.customExpZEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpZEqForceVsMaxLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZEqForceVsMaxLab.setObjectName("customExpZEqForceVsMaxLab")
        self.customExpZWFGrid.addWidget(self.customExpZEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpZWFGrid.setColumnStretch(0, 2)
        self.customExpZWFGrid.setColumnStretch(1, 1)
        self.customExpZWFGrid.setColumnStretch(2, 1)
        self.customExpZWFGrid.setColumnStretch(3, 1)
        self.custExpZVert.addLayout(self.customExpZWFGrid)
        self.custExpZVert.setStretch(0, 1)
        self.custExpZVert.setStretch(1, 1)
        self.customExpAxisTabs.addTab(self.customExpZPage, "")
        self.custExpVert.addWidget(self.customExpAxisTabs)
        self.customExpStartBtn = QtWidgets.QPushButton(self.custExpPage)
        self.customExpStartBtn.setObjectName("customExpStartBtn")
        self.custExpVert.addWidget(self.customExpStartBtn)
        self.modTabs.addTab(self.custExpPage, "")
        self.posNmodHor.addWidget(self.modTabs)
        self.posNmodHor.setStretch(1, 1)
        self.posNmodHor.setStretch(2, 15)
        self.sysCtrlVert.addLayout(self.posNmodHor)
        self.sysCtrlVert.setStretch(0, 7)
        self.mainGuiHor.addLayout(self.sysCtrlVert)
        OTsUI_main.setCentralWidget(self.mainGuiWid)
        self.menubar = QtWidgets.QMenuBar(OTsUI_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1157, 21))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        OTsUI_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OTsUI_main)
        self.statusbar.setObjectName("statusbar")
        OTsUI_main.setStatusBar(self.statusbar)
        self.action_Config_File = QtWidgets.QAction(OTsUI_main)
        self.action_Config_File.setObjectName("action_Config_File")
        self.action_Save_Parameters = QtWidgets.QAction(OTsUI_main)
        self.action_Save_Parameters.setObjectName("action_Save_Parameters")
        self.action_Load_Parameters = QtWidgets.QAction(OTsUI_main)
        self.action_Load_Parameters.setObjectName("action_Load_Parameters")
        self.action_Exit = QtWidgets.QAction(OTsUI_main)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_Config_File)
        self.menu_File.addAction(self.action_Save_Parameters)
        self.menu_File.addAction(self.action_Load_Parameters)
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(OTsUI_main)
        self.plotTabs.setCurrentIndex(0)
        self.sig2selCmb.setCurrentIndex(1)
        self.sig3selCmb.setCurrentIndex(2)
        self.ps2selCmb.setCurrentIndex(1)
        self.ps3selCmb.setCurrentIndex(2)
        self.fbToolBox.setCurrentIndex(0)
        self.modTabs.setCurrentIndex(0)
        self.calTypeTab.setCurrentIndex(0)
        self.customExpAxisTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OTsUI_main)

    def retranslateUi(self, OTsUI_main):
        _translate = QtCore.QCoreApplication.translate
        OTsUI_main.setWindowTitle(_translate("OTsUI_main", "MainWindow"))
        self.connBox.setTitle(_translate("OTsUI_main", "Connection"))
        self.ipAddLab.setText(_translate("OTsUI_main", "IP address"))
        self.portLab.setText(_translate("OTsUI_main", "PUB Port"))
        self.portLab_2.setText(_translate("OTsUI_main", "SUB Port"))
        self.connectBtn.setText(_translate("OTsUI_main", "CONNECT"))
        self.saveBox.setTitle(_translate("OTsUI_main", "Save settings"))
        self.dataDirBtn.setText(_translate("OTsUI_main", "Browse..."))
        self.logDirBtn.setText(_translate("OTsUI_main", "Browse"))
        self.dataDirLab.setText(_translate("OTsUI_main", "Data directory"))
        self.logDirLab.setText(_translate("OTsUI_main", "Log directory"))
        self.logNameLab.setText(_translate("OTsUI_main", "Log file name"))
        self.dataNameLab.setText(_translate("OTsUI_main", "Experiment name"))
        self.lockFbBtn.setText(_translate("OTsUI_main", "LOCK FEED-BACK"))
        self.sig2selCmb.setItemText(0, _translate("OTsUI_main", "X"))
        self.sig2selCmb.setItemText(1, _translate("OTsUI_main", "Y"))
        self.sig2selCmb.setItemText(2, _translate("OTsUI_main", "Z"))
        self.sig3selCmb.setItemText(0, _translate("OTsUI_main", "X"))
        self.sig3selCmb.setItemText(1, _translate("OTsUI_main", "Y"))
        self.sig3selCmb.setItemText(2, _translate("OTsUI_main", "Z"))
        self.sig1selCmb.setItemText(0, _translate("OTsUI_main", "X"))
        self.sig1selCmb.setItemText(1, _translate("OTsUI_main", "Y"))
        self.sig1selCmb.setItemText(2, _translate("OTsUI_main", "Z"))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.signalPage), _translate("OTsUI_main", "Signals"))
        self.ps1selCmb.setItemText(0, _translate("OTsUI_main", "X"))
        self.ps1selCmb.setItemText(1, _translate("OTsUI_main", "Y"))
        self.ps1selCmb.setItemText(2, _translate("OTsUI_main", "Z"))
        self.ps2selCmb.setItemText(0, _translate("OTsUI_main", "X"))
        self.ps2selCmb.setItemText(1, _translate("OTsUI_main", "Y"))
        self.ps2selCmb.setItemText(2, _translate("OTsUI_main", "Z"))
        self.ps3selCmb.setItemText(0, _translate("OTsUI_main", "X"))
        self.ps3selCmb.setItemText(1, _translate("OTsUI_main", "Y"))
        self.ps3selCmb.setItemText(2, _translate("OTsUI_main", "Z"))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.psPage), _translate("OTsUI_main", "Power spectrums"))
        self.zLab.setText(_translate("OTsUI_main", "Z"))
        self.xyFbOnCheck.setText(_translate("OTsUI_main", "FB ON"))
        self.setFbBtn.setText(_translate("OTsUI_main", "SET PI PARAMETERS"))
        self.zPLab.setText(_translate("OTsUI_main", "P"))
        self.zILab.setText(_translate("OTsUI_main", "I"))
        self.xyLab.setText(_translate("OTsUI_main", "X-Y"))
        self.xyILab.setText(_translate("OTsUI_main", "I"))
        self.xyPLab.setText(_translate("OTsUI_main", "P"))
        self.zFbOnCheck.setText(_translate("OTsUI_main", "FB ON"))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.piPage), _translate("OTsUI_main", "PI controller parameters"))
        self.xSpeedTrapPadLab.setText(_translate("OTsUI_main", "X speed [nm/s]"))
        self.ySpeedTrapPadLab.setText(_translate("OTsUI_main", "Y speed [nm/s]"))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.padPage), _translate("OTsUI_main", "Optical trap control pad"))
        self.zOffSetLab.setText(_translate("OTsUI_main", "Z offset"))
        self.yOffSetLab.setText(_translate("OTsUI_main", "Y offset"))
        self.xOffSetLab.setText(_translate("OTsUI_main", "X offset"))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.otherPage), _translate("OTsUI_main", "Other parameters"))
        self.passiveCalDurLab.setText(_translate("OTsUI_main", "Duration [s]"))
        self.passiveCalMaxFreqLab.setText(_translate("OTsUI_main", "Max. frequency [Hz]"))
        self.passiveCalAvgLav.setText(_translate("OTsUI_main", "Averages"))
        self.passiveCalStartBtn.setText(_translate("OTsUI_main", "START"))
        self.calTypeTab.setTabText(self.calTypeTab.indexOf(self.calPassivePage), _translate("OTsUI_main", "Passive"))
        self.activeCalYLab.setText(_translate("OTsUI_main", "Y"))
        self.activeCalZLab.setText(_translate("OTsUI_main", "Z"))
        self.activeCalAmpLab.setText(_translate("OTsUI_main", "Ampl [nm]"))
        self.activeCalXLab.setText(_translate("OTsUI_main", "X"))
        self.activeCalFreqLab.setText(_translate("OTsUI_main", "Freq [Hz]"))
        self.activeCalDurLab.setText(_translate("OTsUI_main", "Duration [s]"))
        self.activeCalMaxFreqLab.setText(_translate("OTsUI_main", "Max freq [Hz]"))
        self.activeCalAvgLab.setText(_translate("OTsUI_main", "Averages"))
        self.activeCalStartBtn.setText(_translate("OTsUI_main", "START"))
        self.calTypeTab.setTabText(self.calTypeTab.indexOf(self.calActivePage), _translate("OTsUI_main", "Active"))
        self.genParBox.setTitle(_translate("OTsUI_main", "General Params"))
        self.dynViscLab.setText(_translate("OTsUI_main", "Dyn. Visc."))
        self.radiusLab.setText(_translate("OTsUI_main", "Radius [um]"))
        self.calResultsBox.setTitle(_translate("OTsUI_main", "Results"))
        self.kxLab.setText(_translate("OTsUI_main", "kx"))
        self.kyLab.setText(_translate("OTsUI_main", "ky"))
        self.kzLab.setText(_translate("OTsUI_main", "kz"))
        self.SxLab.setText(_translate("OTsUI_main", "Sx"))
        self.SyLab.setText(_translate("OTsUI_main", "Sy"))
        self.SzLab.setText(_translate("OTsUI_main", "Sz"))
        self.modTabs.setTabText(self.modTabs.indexOf(self.calibPage), _translate("OTsUI_main", "Calibration"))
        self.stdExpXLab.setText(_translate("OTsUI_main", "X"))
        self.stdExpSetPointLab.setText(_translate("OTsUI_main", "Set point [nm]"))
        self.stdExpAxisLab.setText(_translate("OTsUI_main", "Axis"))
        self.stdExpZLab.setText(_translate("OTsUI_main", "Z"))
        self.stdExpEqForceVsMaxLab.setText(_translate("OTsUI_main", "S.P. Force [pN]/Max force[pN]"))
        self.stdExpYLab.setText(_translate("OTsUI_main", "Y"))
        self.stdExpDurLab.setText(_translate("OTsUI_main", "Duration [s]"))
        self.fbSchedBox.setTitle(_translate("OTsUI_main", "Feed Back time scheduler"))
        self.fbSchedNumIntLab.setText(_translate("OTsUI_main", "Number of intervals"))
        self.fbSchedOnDurLab.setText(_translate("OTsUI_main", "On part dur. [s]"))
        self.fbSchedOffDurLab.setText(_translate("OTsUI_main", "Off part dur. [s]"))
        self.fbSchedStartOnCheck.setText(_translate("OTsUI_main", "Start On"))
        self.stdExpStartBtn.setText(_translate("OTsUI_main", "START"))
        self.modTabs.setTabText(self.modTabs.indexOf(self.stdExpPage), _translate("OTsUI_main", "Standard experiment"))
        self.customExpXMultiIntCheck.setText(_translate("OTsUI_main", "Multi interval"))
        self.customExpXNumIntLab.setText(_translate("OTsUI_main", "Number of intervals"))
        self.customExpXOnDurLab.setText(_translate("OTsUI_main", "On part duration [s]"))
        self.customExpXOffDurLab.setText(_translate("OTsUI_main", "Off part duration [s]"))
        self.customExpXStartOnCheck.setText(_translate("OTsUI_main", "Start On"))
        self.customExpXWFLab.setText(_translate("OTsUI_main", "Waveform type"))
        self.customExpXFreqLab.setText(_translate("OTsUI_main", "Frequency [Hz]"))
        self.customExpXAmplLab.setText(_translate("OTsUI_main", "Amplitude [nm]"))
        self.customExpXEqForceVsMaxLab.setText(_translate("OTsUI_main", "Force ampl. [pN]/Max. force [pN]"))
        self.customExpAxisTabs.setTabText(self.customExpAxisTabs.indexOf(self.customExpXPage), _translate("OTsUI_main", "X"))
        self.customExpYStartOnCheck.setText(_translate("OTsUI_main", "Start On"))
        self.customExpYNumIntLab.setText(_translate("OTsUI_main", "Number of intervals"))
        self.customExpYOffDurLab.setText(_translate("OTsUI_main", "Off part duration [s]"))
        self.customExpYOnDurLab.setText(_translate("OTsUI_main", "On part duration [s]"))
        self.customExpYMultiIntCheck.setText(_translate("OTsUI_main", "Multi interval"))
        self.customExpYWFLab.setText(_translate("OTsUI_main", "Waveform type"))
        self.customExpYFreqLab.setText(_translate("OTsUI_main", "Frequency [Hz]"))
        self.customExpYAmplLab.setText(_translate("OTsUI_main", "Amplitude [nm]"))
        self.customExpYEqForceVsMaxLab.setText(_translate("OTsUI_main", "Force ampl. [pN]/Max. force [pN]"))
        self.customExpAxisTabs.setTabText(self.customExpAxisTabs.indexOf(self.customExpYPage), _translate("OTsUI_main", "Y"))
        self.customExpZMultiIntCheck.setText(_translate("OTsUI_main", "Multi interval"))
        self.customExpZOnDurLab.setText(_translate("OTsUI_main", "On part duration [s]"))
        self.customExpZStartOnCheck.setText(_translate("OTsUI_main", "Start On"))
        self.customExpZOffDurLab.setText(_translate("OTsUI_main", "Off part duration [s]"))
        self.customExpZNumIntLab.setText(_translate("OTsUI_main", "Number of intervals"))
        self.customExpZWFLab.setText(_translate("OTsUI_main", "Waveform type"))
        self.customExpZFreqLab.setText(_translate("OTsUI_main", "Frequency [Hz]"))
        self.customExpZAmplLab.setText(_translate("OTsUI_main", "Amplitude [nm]"))
        self.customExpZEqForceVsMaxLab.setText(_translate("OTsUI_main", "Force ampl. [pN]/Max. force [pN]"))
        self.customExpAxisTabs.setTabText(self.customExpAxisTabs.indexOf(self.customExpZPage), _translate("OTsUI_main", "Z"))
        self.customExpStartBtn.setText(_translate("OTsUI_main", "START"))
        self.modTabs.setTabText(self.modTabs.indexOf(self.custExpPage), _translate("OTsUI_main", "Custom experiment"))
        self.menu_File.setTitle(_translate("OTsUI_main", "&File"))
        self.action_Config_File.setText(_translate("OTsUI_main", "&Config File"))
        self.action_Save_Parameters.setText(_translate("OTsUI_main", "&Save Parameters"))
        self.action_Save_Parameters.setShortcut(_translate("OTsUI_main", "Ctrl+S"))
        self.action_Load_Parameters.setText(_translate("OTsUI_main", "&Load Parameters"))
        self.action_Load_Parameters.setShortcut(_translate("OTsUI_main", "Ctrl+L"))
        self.action_Exit.setText(_translate("OTsUI_main", "&Exit"))
        self.action_Exit.setShortcut(_translate("OTsUI_main", "Ctrl+Shift+E"))

from pyqtgraph import PlotWidget
