# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs\configUI_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_configDial(object):
    def setupUi(self, configDial):
        configDial.setObjectName("configDial")
        configDial.resize(400, 581)
        self.verticalLayout = QtWidgets.QVBoxLayout(configDial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CONN_Box = QtWidgets.QGroupBox(configDial)
        self.CONN_Box.setObjectName("CONN_Box")
        self.formLayout_3 = QtWidgets.QFormLayout(self.CONN_Box)
        self.formLayout_3.setObjectName("formLayout_3")
        self.ipaddr_Label = QtWidgets.QLabel(self.CONN_Box)
        self.ipaddr_Label.setObjectName("ipaddr_Label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ipaddr_Label)
        self.ipaddr_Line = QtWidgets.QLineEdit(self.CONN_Box)
        self.ipaddr_Line.setObjectName("ipaddr_Line")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ipaddr_Line)
        self.subport_Label = QtWidgets.QLabel(self.CONN_Box)
        self.subport_Label.setObjectName("subport_Label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.subport_Label)
        self.subport_Line = QtWidgets.QLineEdit(self.CONN_Box)
        self.subport_Line.setObjectName("subport_Line")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.subport_Line)
        self.pubport_Label = QtWidgets.QLabel(self.CONN_Box)
        self.pubport_Label.setObjectName("pubport_Label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pubport_Label)
        self.pubport_Line = QtWidgets.QLineEdit(self.CONN_Box)
        self.pubport_Line.setObjectName("pubport_Line")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pubport_Line)
        self.verticalLayout.addWidget(self.CONN_Box)
        self.AXIS_Box = QtWidgets.QGroupBox(configDial)
        self.AXIS_Box.setObjectName("AXIS_Box")
        self.formLayout_2 = QtWidgets.QFormLayout(self.AXIS_Box)
        self.formLayout_2.setObjectName("formLayout_2")
        self.axisCmbBox = QtWidgets.QComboBox(self.AXIS_Box)
        self.axisCmbBox.setObjectName("axisCmbBox")
        self.axisCmbBox.addItem("")
        self.axisCmbBox.addItem("")
        self.axisCmbBox.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.axisCmbBox)
        self.devname_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.devname_Label.setObjectName("devname_Label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.devname_Label)
        self.devname_Line = QtWidgets.QLineEdit(self.AXIS_Box)
        self.devname_Line.setObjectName("devname_Line")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.devname_Line)
        self.vgalvmax_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.vgalvmax_Label.setObjectName("vgalvmax_Label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.vgalvmax_Label)
        self.vgalvmax_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.vgalvmax_NumDbl.setMinimum(-10.0)
        self.vgalvmax_NumDbl.setMaximum(10.0)
        self.vgalvmax_NumDbl.setObjectName("vgalvmax_NumDbl")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.vgalvmax_NumDbl)
        self.vgalvmin_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.vgalvmin_Label.setObjectName("vgalvmin_Label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.vgalvmin_Label)
        self.vgalvmin_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.vgalvmin_NumDbl.setMinimum(-10.0)
        self.vgalvmin_NumDbl.setMaximum(10.0)
        self.vgalvmin_NumDbl.setObjectName("vgalvmin_NumDbl")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.vgalvmin_NumDbl)
        self.nmgalvmax_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.nmgalvmax_Label.setObjectName("nmgalvmax_Label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.nmgalvmax_Label)
        self.nmgalvmax_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.nmgalvmax_NumDbl.setMinimum(-10000.0)
        self.nmgalvmax_NumDbl.setMaximum(10000.0)
        self.nmgalvmax_NumDbl.setObjectName("nmgalvmax_NumDbl")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.nmgalvmax_NumDbl)
        self.nmgalvmin_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.nmgalvmin_Label.setObjectName("nmgalvmin_Label")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nmgalvmin_Label)
        self.nmgalvmin_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.nmgalvmin_NumDbl.setMinimum(-10000.0)
        self.nmgalvmin_NumDbl.setMaximum(10000.0)
        self.nmgalvmin_NumDbl.setObjectName("nmgalvmin_NumDbl")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nmgalvmin_NumDbl)
        self.qpdmax_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.qpdmax_Label.setObjectName("qpdmax_Label")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.qpdmax_Label)
        self.qpdmax_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.qpdmax_NumDbl.setMinimum(-10.0)
        self.qpdmax_NumDbl.setMaximum(10.0)
        self.qpdmax_NumDbl.setObjectName("qpdmax_NumDbl")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.qpdmax_NumDbl)
        self.qpdmin_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.qpdmin_Label.setObjectName("qpdmin_Label")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.qpdmin_Label)
        self.qpdmin_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.qpdmin_NumDbl.setMinimum(-10.0)
        self.qpdmin_NumDbl.setMaximum(10.0)
        self.qpdmin_NumDbl.setObjectName("qpdmin_NumDbl")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.qpdmin_NumDbl)
        self.pmax_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.pmax_Label.setObjectName("pmax_Label")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pmax_Label)
        self.pmax_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.pmax_NumDbl.setMinimum(0.0)
        self.pmax_NumDbl.setMaximum(1000.0)
        self.pmax_NumDbl.setObjectName("pmax_NumDbl")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pmax_NumDbl)
        self.imax_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.imax_Label.setObjectName("imax_Label")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.imax_Label)
        self.imax_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.imax_NumDbl.setMinimum(0.0)
        self.imax_NumDbl.setMaximum(1000.0)
        self.imax_NumDbl.setObjectName("imax_NumDbl")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.imax_NumDbl)
        self.speedmax_Label = QtWidgets.QLabel(self.AXIS_Box)
        self.speedmax_Label.setObjectName("speedmax_Label")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.speedmax_Label)
        self.speedmax_NumDbl = QtWidgets.QDoubleSpinBox(self.AXIS_Box)
        self.speedmax_NumDbl.setMinimum(0.0)
        self.speedmax_NumDbl.setMaximum(1000.0)
        self.speedmax_NumDbl.setObjectName("speedmax_NumDbl")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.speedmax_NumDbl)
        self.verticalLayout.addWidget(self.AXIS_Box)
        self.OTHER_Box = QtWidgets.QGroupBox(configDial)
        self.OTHER_Box.setObjectName("OTHER_Box")
        self.formLayout_4 = QtWidgets.QFormLayout(self.OTHER_Box)
        self.formLayout_4.setObjectName("formLayout_4")
        self.stimmaxfreq_NumDbl = QtWidgets.QDoubleSpinBox(self.OTHER_Box)
        self.stimmaxfreq_NumDbl.setMinimum(0.0)
        self.stimmaxfreq_NumDbl.setMaximum(1000.0)
        self.stimmaxfreq_NumDbl.setObjectName("stimmaxfreq_NumDbl")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stimmaxfreq_NumDbl)
        self.stimmaxfreq_Label = QtWidgets.QLabel(self.OTHER_Box)
        self.stimmaxfreq_Label.setObjectName("stimmaxfreq_Label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stimmaxfreq_Label)
        self.verticalLayout.addWidget(self.OTHER_Box)
        self.buttonBox = QtWidgets.QDialogButtonBox(configDial)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 6)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(configDial)
        self.buttonBox.accepted.connect(configDial.accept)
        self.buttonBox.rejected.connect(configDial.reject)
        QtCore.QMetaObject.connectSlotsByName(configDial)

    def retranslateUi(self, configDial):
        _translate = QtCore.QCoreApplication.translate
        configDial.setWindowTitle(_translate("configDial", "OTsUI configuration"))
        self.CONN_Box.setTitle(_translate("configDial", "Connection"))
        self.ipaddr_Label.setText(_translate("configDial", "Forwarder IP address"))
        self.subport_Label.setText(_translate("configDial", "SUB Port"))
        self.pubport_Label.setText(_translate("configDial", "PUB Port"))
        self.AXIS_Box.setTitle(_translate("configDial", "Axis parameters"))
        self.axisCmbBox.setItemText(0, _translate("configDial", "X"))
        self.axisCmbBox.setItemText(1, _translate("configDial", "Y"))
        self.axisCmbBox.setItemText(2, _translate("configDial", "Z"))
        self.devname_Label.setText(_translate("configDial", "Device name"))
        self.vgalvmax_Label.setText(_translate("configDial", "Galvo Maximum [V]"))
        self.vgalvmin_Label.setText(_translate("configDial", "Galvo Minimum [V]"))
        self.nmgalvmax_Label.setText(_translate("configDial", "Galvo Maximum [nm]"))
        self.nmgalvmin_Label.setText(_translate("configDial", "Galvo Minimum [nm]"))
        self.qpdmax_Label.setText(_translate("configDial", "QPD Maximum [V]"))
        self.qpdmin_Label.setText(_translate("configDial", "QPD Minimum [V]"))
        self.pmax_Label.setText(_translate("configDial", "P gain Maximum"))
        self.imax_Label.setText(_translate("configDial", "I gain Maximum"))
        self.speedmax_Label.setText(_translate("configDial", "Speed Maximum [nm/s]"))
        self.OTHER_Box.setTitle(_translate("configDial", "Other parameters"))
        self.stimmaxfreq_Label.setText(_translate("configDial", "Stimuli max frequency [Hz]"))

