# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs\OTsUI_MainGUI.ui'
#
# Created: Thu Dec 17 17:14:30 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OTsUI_main(object):
    def setupUi(self, OTsUI_main):
        OTsUI_main.setObjectName(_fromUtf8("OTsUI_main"))
        OTsUI_main.resize(1401, 910)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OTsUI_main.sizePolicy().hasHeightForWidth())
        OTsUI_main.setSizePolicy(sizePolicy)
        self.mainGuiWid = QtGui.QWidget(OTsUI_main)
        self.mainGuiWid.setObjectName(_fromUtf8("mainGuiWid"))
        self.mainGuiHor = QtGui.QHBoxLayout(self.mainGuiWid)
        self.mainGuiHor.setObjectName(_fromUtf8("mainGuiHor"))
        self.conSavLogFrame = QtGui.QFrame(self.mainGuiWid)
        self.conSavLogFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.conSavLogFrame.setMaximumSize(QtCore.QSize(251, 16777215))
        self.conSavLogFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.conSavLogFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.conSavLogFrame.setObjectName(_fromUtf8("conSavLogFrame"))
        self.conSavLogVert = QtGui.QVBoxLayout(self.conSavLogFrame)
        self.conSavLogVert.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.conSavLogVert.setObjectName(_fromUtf8("conSavLogVert"))
        self.connBox = QtGui.QGroupBox(self.conSavLogFrame)
        self.connBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.connBox.setObjectName(_fromUtf8("connBox"))
        self.connBoxVert = QtGui.QVBoxLayout(self.connBox)
        self.connBoxVert.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.connBoxVert.setObjectName(_fromUtf8("connBoxVert"))
        self.connForm = QtGui.QFormLayout()
        self.connForm.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.connForm.setObjectName(_fromUtf8("connForm"))
        self.ipAddLine = QtGui.QLineEdit(self.connBox)
        self.ipAddLine.setReadOnly(True)
        self.ipAddLine.setObjectName(_fromUtf8("ipAddLine"))
        self.connForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.ipAddLine)
        self.ipAddLab = QtGui.QLabel(self.connBox)
        self.ipAddLab.setObjectName(_fromUtf8("ipAddLab"))
        self.connForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.ipAddLab)
        self.pubPortLine = QtGui.QLineEdit(self.connBox)
        self.pubPortLine.setReadOnly(True)
        self.pubPortLine.setObjectName(_fromUtf8("pubPortLine"))
        self.connForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.pubPortLine)
        self.portLab = QtGui.QLabel(self.connBox)
        self.portLab.setObjectName(_fromUtf8("portLab"))
        self.connForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.portLab)
        self.subPortLine = QtGui.QLineEdit(self.connBox)
        self.subPortLine.setReadOnly(True)
        self.subPortLine.setObjectName(_fromUtf8("subPortLine"))
        self.connForm.setWidget(2, QtGui.QFormLayout.FieldRole, self.subPortLine)
        self.portLab_2 = QtGui.QLabel(self.connBox)
        self.portLab_2.setObjectName(_fromUtf8("portLab_2"))
        self.connForm.setWidget(2, QtGui.QFormLayout.LabelRole, self.portLab_2)
        self.connBoxVert.addLayout(self.connForm)
        self.connectBtn = QtGui.QPushButton(self.connBox)
        self.connectBtn.setObjectName(_fromUtf8("connectBtn"))
        self.connBoxVert.addWidget(self.connectBtn)
        self.conSavLogVert.addWidget(self.connBox)
        self.saveBox = QtGui.QGroupBox(self.conSavLogFrame)
        self.saveBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.saveBox.setObjectName(_fromUtf8("saveBox"))
        self.saveBoxVert = QtGui.QVBoxLayout(self.saveBox)
        self.saveBoxVert.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.saveBoxVert.setObjectName(_fromUtf8("saveBoxVert"))
        self.saveGrid = QtGui.QGridLayout()
        self.saveGrid.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.saveGrid.setObjectName(_fromUtf8("saveGrid"))
        self.logDirLine = QtGui.QLineEdit(self.saveBox)
        self.logDirLine.setObjectName(_fromUtf8("logDirLine"))
        self.saveGrid.addWidget(self.logDirLine, 4, 1, 1, 1)
        self.dataNameLab = QtGui.QLabel(self.saveBox)
        self.dataNameLab.setObjectName(_fromUtf8("dataNameLab"))
        self.saveGrid.addWidget(self.dataNameLab, 2, 0, 1, 1)
        self.logNameLab = QtGui.QLabel(self.saveBox)
        self.logNameLab.setObjectName(_fromUtf8("logNameLab"))
        self.saveGrid.addWidget(self.logNameLab, 7, 0, 1, 1)
        self.dataNameLine = QtGui.QLineEdit(self.saveBox)
        self.dataNameLine.setObjectName(_fromUtf8("dataNameLine"))
        self.saveGrid.addWidget(self.dataNameLine, 2, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.saveBox)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.saveGrid.addWidget(self.line_4, 8, 0, 1, 2)
        self.logDirBtn = QtGui.QPushButton(self.saveBox)
        self.logDirBtn.setObjectName(_fromUtf8("logDirBtn"))
        self.saveGrid.addWidget(self.logDirBtn, 6, 1, 1, 1)
        self.dataDirLine = QtGui.QLineEdit(self.saveBox)
        self.dataDirLine.setObjectName(_fromUtf8("dataDirLine"))
        self.saveGrid.addWidget(self.dataDirLine, 0, 1, 1, 1)
        self.dataDirBtn = QtGui.QPushButton(self.saveBox)
        self.dataDirBtn.setObjectName(_fromUtf8("dataDirBtn"))
        self.saveGrid.addWidget(self.dataDirBtn, 1, 1, 1, 1)
        self.dataDirLab = QtGui.QLabel(self.saveBox)
        self.dataDirLab.setObjectName(_fromUtf8("dataDirLab"))
        self.saveGrid.addWidget(self.dataDirLab, 0, 0, 1, 1)
        self.logNameLine = QtGui.QLineEdit(self.saveBox)
        self.logNameLine.setObjectName(_fromUtf8("logNameLine"))
        self.saveGrid.addWidget(self.logNameLine, 7, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.saveBox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.saveGrid.addWidget(self.line_3, 3, 0, 1, 2)
        self.logDirLab = QtGui.QLabel(self.saveBox)
        self.logDirLab.setObjectName(_fromUtf8("logDirLab"))
        self.saveGrid.addWidget(self.logDirLab, 4, 0, 1, 1)
        self.saveGrid.setColumnStretch(0, 1)
        self.saveBoxVert.addLayout(self.saveGrid)
        self.logText = QtGui.QTextEdit(self.saveBox)
        self.logText.setMaximumSize(QtCore.QSize(300, 16777215))
        self.logText.setObjectName(_fromUtf8("logText"))
        self.saveBoxVert.addWidget(self.logText)
        self.conSavLogVert.addWidget(self.saveBox)
        self.lockFbBtn = QtGui.QPushButton(self.conSavLogFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lockFbBtn.sizePolicy().hasHeightForWidth())
        self.lockFbBtn.setSizePolicy(sizePolicy)
        self.lockFbBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.lockFbBtn.setObjectName(_fromUtf8("lockFbBtn"))
        self.conSavLogVert.addWidget(self.lockFbBtn)
        self.conSavLogVert.setStretch(0, 1)
        self.conSavLogVert.setStretch(1, 3)
        self.mainGuiHor.addWidget(self.conSavLogFrame)
        self.sysCtrlVert = QtGui.QVBoxLayout()
        self.sysCtrlVert.setObjectName(_fromUtf8("sysCtrlVert"))
        self.plotNfbHor = QtGui.QHBoxLayout()
        self.plotNfbHor.setObjectName(_fromUtf8("plotNfbHor"))
        self.plotTabs = QtGui.QTabWidget(self.mainGuiWid)
        self.plotTabs.setObjectName(_fromUtf8("plotTabs"))
        self.signalPage = QtGui.QWidget()
        self.signalPage.setObjectName(_fromUtf8("signalPage"))
        self.signalTabGrid = QtGui.QGridLayout(self.signalPage)
        self.signalTabGrid.setObjectName(_fromUtf8("signalTabGrid"))
        self.sig2Plot = PlotWidget(self.signalPage)
        self.sig2Plot.setObjectName(_fromUtf8("sig2Plot"))
        self.signalTabGrid.addWidget(self.sig2Plot, 2, 0, 1, 1)
        self.sig2selCmb = QtGui.QComboBox(self.signalPage)
        self.sig2selCmb.setObjectName(_fromUtf8("sig2selCmb"))
        self.sig2selCmb.addItem(_fromUtf8(""))
        self.sig2selCmb.addItem(_fromUtf8(""))
        self.sig2selCmb.addItem(_fromUtf8(""))
        self.sig2selCmb.addItem(_fromUtf8(""))
        self.sig2selCmb.addItem(_fromUtf8(""))
        self.sig2selCmb.addItem(_fromUtf8(""))
        self.signalTabGrid.addWidget(self.sig2selCmb, 3, 0, 1, 1)
        self.sig3Plot = PlotWidget(self.signalPage)
        self.sig3Plot.setObjectName(_fromUtf8("sig3Plot"))
        self.signalTabGrid.addWidget(self.sig3Plot, 2, 1, 1, 1)
        self.sig3selCmb = QtGui.QComboBox(self.signalPage)
        self.sig3selCmb.setObjectName(_fromUtf8("sig3selCmb"))
        self.sig3selCmb.addItem(_fromUtf8(""))
        self.sig3selCmb.addItem(_fromUtf8(""))
        self.sig3selCmb.addItem(_fromUtf8(""))
        self.sig3selCmb.addItem(_fromUtf8(""))
        self.sig3selCmb.addItem(_fromUtf8(""))
        self.sig3selCmb.addItem(_fromUtf8(""))
        self.signalTabGrid.addWidget(self.sig3selCmb, 3, 1, 1, 1)
        self.sig1Plot = PlotWidget(self.signalPage)
        self.sig1Plot.setObjectName(_fromUtf8("sig1Plot"))
        self.signalTabGrid.addWidget(self.sig1Plot, 0, 0, 1, 2)
        self.sig1selCmb = QtGui.QComboBox(self.signalPage)
        self.sig1selCmb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sig1selCmb.setObjectName(_fromUtf8("sig1selCmb"))
        self.sig1selCmb.addItem(_fromUtf8(""))
        self.sig1selCmb.addItem(_fromUtf8(""))
        self.sig1selCmb.addItem(_fromUtf8(""))
        self.sig1selCmb.addItem(_fromUtf8(""))
        self.sig1selCmb.addItem(_fromUtf8(""))
        self.sig1selCmb.addItem(_fromUtf8(""))
        self.signalTabGrid.addWidget(self.sig1selCmb, 1, 0, 1, 2)
        self.signalTabGrid.setRowStretch(0, 3)
        self.signalTabGrid.setRowStretch(1, 1)
        self.signalTabGrid.setRowStretch(2, 2)
        self.signalTabGrid.setRowStretch(3, 1)
        self.plotTabs.addTab(self.signalPage, _fromUtf8(""))
        self.psPage = QtGui.QWidget()
        self.psPage.setObjectName(_fromUtf8("psPage"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.psPage)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.powSpec1Plot = PlotWidget(self.psPage)
        self.powSpec1Plot.setObjectName(_fromUtf8("powSpec1Plot"))
        self.verticalLayout.addWidget(self.powSpec1Plot)
        self.ps1selCmb = QtGui.QComboBox(self.psPage)
        self.ps1selCmb.setObjectName(_fromUtf8("ps1selCmb"))
        self.ps1selCmb.addItem(_fromUtf8(""))
        self.ps1selCmb.addItem(_fromUtf8(""))
        self.ps1selCmb.addItem(_fromUtf8(""))
        self.ps1selCmb.addItem(_fromUtf8(""))
        self.ps1selCmb.addItem(_fromUtf8(""))
        self.ps1selCmb.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.ps1selCmb)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.powSpec3Plot = PlotWidget(self.psPage)
        self.powSpec3Plot.setObjectName(_fromUtf8("powSpec3Plot"))
        self.gridLayout.addWidget(self.powSpec3Plot, 0, 1, 1, 1)
        self.powSpec2Plot = PlotWidget(self.psPage)
        self.powSpec2Plot.setObjectName(_fromUtf8("powSpec2Plot"))
        self.gridLayout.addWidget(self.powSpec2Plot, 0, 0, 1, 1)
        self.ps2selCmb = QtGui.QComboBox(self.psPage)
        self.ps2selCmb.setObjectName(_fromUtf8("ps2selCmb"))
        self.ps2selCmb.addItem(_fromUtf8(""))
        self.ps2selCmb.addItem(_fromUtf8(""))
        self.ps2selCmb.addItem(_fromUtf8(""))
        self.ps2selCmb.addItem(_fromUtf8(""))
        self.ps2selCmb.addItem(_fromUtf8(""))
        self.ps2selCmb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ps2selCmb, 1, 0, 1, 1)
        self.ps3selCmb = QtGui.QComboBox(self.psPage)
        self.ps3selCmb.setObjectName(_fromUtf8("ps3selCmb"))
        self.ps3selCmb.addItem(_fromUtf8(""))
        self.ps3selCmb.addItem(_fromUtf8(""))
        self.ps3selCmb.addItem(_fromUtf8(""))
        self.ps3selCmb.addItem(_fromUtf8(""))
        self.ps3selCmb.addItem(_fromUtf8(""))
        self.ps3selCmb.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ps3selCmb, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2.setStretch(0, 7)
        self.verticalLayout_2.setStretch(1, 5)
        self.plotTabs.addTab(self.psPage, _fromUtf8(""))
        self.plotNfbHor.addWidget(self.plotTabs)
        self.fbFrame = QtGui.QFrame(self.mainGuiWid)
        self.fbFrame.setMinimumSize(QtCore.QSize(420, 0))
        self.fbFrame.setMaximumSize(QtCore.QSize(420, 16777215))
        self.fbFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fbFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fbFrame.setObjectName(_fromUtf8("fbFrame"))
        self.fbFrameVert = QtGui.QVBoxLayout(self.fbFrame)
        self.fbFrameVert.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.fbFrameVert.setObjectName(_fromUtf8("fbFrameVert"))
        self.fbToolBox = QtGui.QToolBox(self.fbFrame)
        self.fbToolBox.setMinimumSize(QtCore.QSize(420, 0))
        self.fbToolBox.setMaximumSize(QtCore.QSize(420, 16777215))
        self.fbToolBox.setObjectName(_fromUtf8("fbToolBox"))
        self.piPage = QtGui.QWidget()
        self.piPage.setGeometry(QtCore.QRect(0, 0, 420, 458))
        self.piPage.setObjectName(_fromUtf8("piPage"))
        self.piGrid = QtGui.QGridLayout(self.piPage)
        self.piGrid.setObjectName(_fromUtf8("piGrid"))
        self.zIDial = QtGui.QDial(self.piPage)
        self.zIDial.setObjectName(_fromUtf8("zIDial"))
        self.piGrid.addWidget(self.zIDial, 7, 1, 1, 1)
        self.xyIDial = QtGui.QDial(self.piPage)
        self.xyIDial.setObjectName(_fromUtf8("xyIDial"))
        self.piGrid.addWidget(self.xyIDial, 3, 1, 1, 1)
        self.zPLab = QtGui.QLabel(self.piPage)
        self.zPLab.setObjectName(_fromUtf8("zPLab"))
        self.piGrid.addWidget(self.zPLab, 6, 0, 1, 1)
        self.yPiFrame = QtGui.QFrame(self.piPage)
        self.yPiFrame.setEnabled(False)
        self.yPiFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.yPiFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.yPiFrame.setObjectName(_fromUtf8("yPiFrame"))
        self.yPiGrid = QtGui.QGridLayout(self.yPiFrame)
        self.yPiGrid.setObjectName(_fromUtf8("yPiGrid"))
        self.yOptPDial = QtGui.QDial(self.yPiFrame)
        self.yOptPDial.setObjectName(_fromUtf8("yOptPDial"))
        self.yPiGrid.addWidget(self.yOptPDial, 0, 1, 1, 1)
        self.yOptPLab = QtGui.QLabel(self.yPiFrame)
        self.yOptPLab.setObjectName(_fromUtf8("yOptPLab"))
        self.yPiGrid.addWidget(self.yOptPLab, 0, 0, 1, 1)
        self.yOptILab = QtGui.QLabel(self.yPiFrame)
        self.yOptILab.setObjectName(_fromUtf8("yOptILab"))
        self.yPiGrid.addWidget(self.yOptILab, 1, 0, 1, 1)
        self.yOptIDial = QtGui.QDial(self.yPiFrame)
        self.yOptIDial.setObjectName(_fromUtf8("yOptIDial"))
        self.yPiGrid.addWidget(self.yOptIDial, 1, 1, 1, 1)
        self.yOptPNumDbl = QtGui.QDoubleSpinBox(self.yPiFrame)
        self.yOptPNumDbl.setObjectName(_fromUtf8("yOptPNumDbl"))
        self.yPiGrid.addWidget(self.yOptPNumDbl, 0, 2, 1, 1)
        self.yOptINumDbl = QtGui.QDoubleSpinBox(self.yPiFrame)
        self.yOptINumDbl.setObjectName(_fromUtf8("yOptINumDbl"))
        self.yPiGrid.addWidget(self.yOptINumDbl, 1, 2, 1, 1)
        self.piGrid.addWidget(self.yPiFrame, 1, 3, 3, 1)
        self.xyPDial = QtGui.QDial(self.piPage)
        self.xyPDial.setObjectName(_fromUtf8("xyPDial"))
        self.piGrid.addWidget(self.xyPDial, 1, 1, 1, 1)
        self.zLab = QtGui.QLabel(self.piPage)
        self.zLab.setObjectName(_fromUtf8("zLab"))
        self.piGrid.addWidget(self.zLab, 5, 0, 1, 1)
        self.xyINumDbl = QtGui.QDoubleSpinBox(self.piPage)
        self.xyINumDbl.setObjectName(_fromUtf8("xyINumDbl"))
        self.piGrid.addWidget(self.xyINumDbl, 3, 2, 1, 1)
        self.xyPLab = QtGui.QLabel(self.piPage)
        self.xyPLab.setObjectName(_fromUtf8("xyPLab"))
        self.piGrid.addWidget(self.xyPLab, 1, 0, 1, 1)
        self.xyILab = QtGui.QLabel(self.piPage)
        self.xyILab.setObjectName(_fromUtf8("xyILab"))
        self.piGrid.addWidget(self.xyILab, 3, 0, 1, 1)
        self.zFbOnCheck = QtGui.QCheckBox(self.piPage)
        self.zFbOnCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.zFbOnCheck.setObjectName(_fromUtf8("zFbOnCheck"))
        self.piGrid.addWidget(self.zFbOnCheck, 5, 1, 1, 1)
        self.zPDial = QtGui.QDial(self.piPage)
        self.zPDial.setObjectName(_fromUtf8("zPDial"))
        self.piGrid.addWidget(self.zPDial, 6, 1, 1, 1)
        self.zPNumDbl = QtGui.QDoubleSpinBox(self.piPage)
        self.zPNumDbl.setObjectName(_fromUtf8("zPNumDbl"))
        self.piGrid.addWidget(self.zPNumDbl, 6, 2, 1, 1)
        self.zILab = QtGui.QLabel(self.piPage)
        self.zILab.setObjectName(_fromUtf8("zILab"))
        self.piGrid.addWidget(self.zILab, 7, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.piPage)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.piGrid.addWidget(self.line_2, 4, 0, 1, 4)
        self.xyPNumDbl = QtGui.QDoubleSpinBox(self.piPage)
        self.xyPNumDbl.setObjectName(_fromUtf8("xyPNumDbl"))
        self.piGrid.addWidget(self.xyPNumDbl, 1, 2, 1, 1)
        self.zINumDbl = QtGui.QDoubleSpinBox(self.piPage)
        self.zINumDbl.setObjectName(_fromUtf8("zINumDbl"))
        self.piGrid.addWidget(self.zINumDbl, 7, 2, 1, 1)
        self.setFbBtn = QtGui.QPushButton(self.piPage)
        self.setFbBtn.setObjectName(_fromUtf8("setFbBtn"))
        self.piGrid.addWidget(self.setFbBtn, 8, 0, 1, 4)
        self.u = QtGui.QCheckBox(self.piPage)
        self.u.setChecked(False)
        self.u.setObjectName(_fromUtf8("u"))
        self.piGrid.addWidget(self.u, 0, 3, 1, 1)
        self.xyFbOnCheck = QtGui.QCheckBox(self.piPage)
        self.xyFbOnCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.xyFbOnCheck.setObjectName(_fromUtf8("xyFbOnCheck"))
        self.piGrid.addWidget(self.xyFbOnCheck, 0, 1, 1, 1)
        self.xyLab = QtGui.QLabel(self.piPage)
        self.xyLab.setObjectName(_fromUtf8("xyLab"))
        self.piGrid.addWidget(self.xyLab, 0, 0, 1, 1)
        self.piGrid.setColumnStretch(0, 1)
        self.piGrid.setColumnStretch(1, 9)
        self.piGrid.setColumnStretch(2, 7)
        self.piGrid.setColumnStretch(3, 18)
        self.fbToolBox.addItem(self.piPage, _fromUtf8(""))
        self.padPage = QtGui.QWidget()
        self.padPage.setGeometry(QtCore.QRect(0, 0, 398, 464))
        self.padPage.setObjectName(_fromUtf8("padPage"))
        self.padVert = QtGui.QVBoxLayout(self.padPage)
        self.padVert.setObjectName(_fromUtf8("padVert"))
        self.padFrame = QtGui.QFrame(self.padPage)
        self.padFrame.setMinimumSize(QtCore.QSize(380, 295))
        self.padFrame.setMaximumSize(QtCore.QSize(380, 295))
        self.padFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.padFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.padFrame.setObjectName(_fromUtf8("padFrame"))
        self.padHor = QtGui.QHBoxLayout(self.padFrame)
        self.padHor.setObjectName(_fromUtf8("padHor"))
        self.trapXyPlotGrid = QtGui.QGridLayout()
        self.trapXyPlotGrid.setObjectName(_fromUtf8("trapXyPlotGrid"))
        self.yPlusTrapBtn = QtGui.QPushButton(self.padFrame)
        self.yPlusTrapBtn.setMinimumSize(QtCore.QSize(190, 30))
        self.yPlusTrapBtn.setMaximumSize(QtCore.QSize(190, 30))
        self.yPlusTrapBtn.setObjectName(_fromUtf8("yPlusTrapBtn"))
        self.trapXyPlotGrid.addWidget(self.yPlusTrapBtn, 0, 1, 1, 1)
        self.xMinusTrapBtn = QtGui.QPushButton(self.padFrame)
        self.xMinusTrapBtn.setMinimumSize(QtCore.QSize(30, 190))
        self.xMinusTrapBtn.setMaximumSize(QtCore.QSize(30, 200))
        self.xMinusTrapBtn.setObjectName(_fromUtf8("xMinusTrapBtn"))
        self.trapXyPlotGrid.addWidget(self.xMinusTrapBtn, 1, 0, 1, 1)
        self.xPlusTrapBtn = QtGui.QPushButton(self.padFrame)
        self.xPlusTrapBtn.setMinimumSize(QtCore.QSize(30, 190))
        self.xPlusTrapBtn.setMaximumSize(QtCore.QSize(30, 190))
        self.xPlusTrapBtn.setObjectName(_fromUtf8("xPlusTrapBtn"))
        self.trapXyPlotGrid.addWidget(self.xPlusTrapBtn, 1, 2, 1, 1)
        self.trapPadPlot = PlotWidget(self.padFrame)
        self.trapPadPlot.setMinimumSize(QtCore.QSize(190, 190))
        self.trapPadPlot.setMaximumSize(QtCore.QSize(190, 190))
        self.trapPadPlot.setObjectName(_fromUtf8("trapPadPlot"))
        self.trapXyPlotGrid.addWidget(self.trapPadPlot, 1, 1, 1, 1)
        self.yMinusTrapBtn = QtGui.QPushButton(self.padFrame)
        self.yMinusTrapBtn.setMinimumSize(QtCore.QSize(190, 30))
        self.yMinusTrapBtn.setMaximumSize(QtCore.QSize(200, 30))
        self.yMinusTrapBtn.setObjectName(_fromUtf8("yMinusTrapBtn"))
        self.trapXyPlotGrid.addWidget(self.yMinusTrapBtn, 2, 1, 1, 1)
        self.padHor.addLayout(self.trapXyPlotGrid)
        self.trapZHomeVert = QtGui.QVBoxLayout()
        self.trapZHomeVert.setObjectName(_fromUtf8("trapZHomeVert"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.trapZHomeVert.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.zPlusTrapBtn = QtGui.QPushButton(self.padFrame)
        self.zPlusTrapBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.zPlusTrapBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.zPlusTrapBtn.setObjectName(_fromUtf8("zPlusTrapBtn"))
        self.horizontalLayout_3.addWidget(self.zPlusTrapBtn)
        self.trapZHomeVert.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.trapZHomeVert.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.zMinusTrapBtn = QtGui.QPushButton(self.padFrame)
        self.zMinusTrapBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.zMinusTrapBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.zMinusTrapBtn.setObjectName(_fromUtf8("zMinusTrapBtn"))
        self.horizontalLayout_4.addWidget(self.zMinusTrapBtn)
        self.trapZHomeVert.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.trapZHomeVert.addItem(spacerItem2)
        self.line_5 = QtGui.QFrame(self.padFrame)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.trapZHomeVert.addWidget(self.line_5)
        self.homeHor = QtGui.QHBoxLayout()
        self.homeHor.setObjectName(_fromUtf8("homeHor"))
        self.line_6 = QtGui.QFrame(self.padFrame)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.homeHor.addWidget(self.line_6)
        self.goHomeBtn = QtGui.QPushButton(self.padFrame)
        self.goHomeBtn.setMinimumSize(QtCore.QSize(60, 60))
        self.goHomeBtn.setMaximumSize(QtCore.QSize(60, 60))
        self.goHomeBtn.setObjectName(_fromUtf8("goHomeBtn"))
        self.homeHor.addWidget(self.goHomeBtn)
        self.line_7 = QtGui.QFrame(self.padFrame)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.homeHor.addWidget(self.line_7)
        self.trapZHomeVert.addLayout(self.homeHor)
        self.line_8 = QtGui.QFrame(self.padFrame)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.trapZHomeVert.addWidget(self.line_8)
        self.trapZHomeVert.setStretch(1, 2)
        self.trapZHomeVert.setStretch(2, 1)
        self.trapZHomeVert.setStretch(3, 2)
        self.trapZHomeVert.setStretch(4, 1)
        self.trapZHomeVert.setStretch(5, 1)
        self.trapZHomeVert.setStretch(6, 2)
        self.padHor.addLayout(self.trapZHomeVert)
        self.padVert.addWidget(self.padFrame)
        self.stepNspeedHor = QtGui.QHBoxLayout()
        self.stepNspeedHor.setObjectName(_fromUtf8("stepNspeedHor"))
        self.trapPadStepGrid = QtGui.QGridLayout()
        self.trapPadStepGrid.setObjectName(_fromUtf8("trapPadStepGrid"))
        self.xStepLab_3 = QtGui.QLabel(self.padPage)
        self.xStepLab_3.setAlignment(QtCore.Qt.AlignCenter)
        self.xStepLab_3.setObjectName(_fromUtf8("xStepLab_3"))
        self.trapPadStepGrid.addWidget(self.xStepLab_3, 3, 0, 1, 1)
        self.xStepLab = QtGui.QLabel(self.padPage)
        self.xStepLab.setAlignment(QtCore.Qt.AlignCenter)
        self.xStepLab.setObjectName(_fromUtf8("xStepLab"))
        self.trapPadStepGrid.addWidget(self.xStepLab, 1, 0, 1, 1)
        self.xTrapPadStepNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.xTrapPadStepNumDbl.setObjectName(_fromUtf8("xTrapPadStepNumDbl"))
        self.trapPadStepGrid.addWidget(self.xTrapPadStepNumDbl, 1, 1, 1, 1)
        self.xStepLab_2 = QtGui.QLabel(self.padPage)
        self.xStepLab_2.setAlignment(QtCore.Qt.AlignCenter)
        self.xStepLab_2.setObjectName(_fromUtf8("xStepLab_2"))
        self.trapPadStepGrid.addWidget(self.xStepLab_2, 2, 0, 1, 1)
        self.yTrapPadStepNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.yTrapPadStepNumDbl.setObjectName(_fromUtf8("yTrapPadStepNumDbl"))
        self.trapPadStepGrid.addWidget(self.yTrapPadStepNumDbl, 2, 1, 1, 1)
        self.zTrapPadStepNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.zTrapPadStepNumDbl.setObjectName(_fromUtf8("zTrapPadStepNumDbl"))
        self.trapPadStepGrid.addWidget(self.zTrapPadStepNumDbl, 3, 1, 1, 1)
        self.stepLab = QtGui.QLabel(self.padPage)
        self.stepLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stepLab.setObjectName(_fromUtf8("stepLab"))
        self.trapPadStepGrid.addWidget(self.stepLab, 0, 1, 1, 1)
        self.currPosLab = QtGui.QLabel(self.padPage)
        self.currPosLab.setAlignment(QtCore.Qt.AlignCenter)
        self.currPosLab.setObjectName(_fromUtf8("currPosLab"))
        self.trapPadStepGrid.addWidget(self.currPosLab, 0, 2, 1, 1)
        self.setHomeBtn = QtGui.QPushButton(self.padPage)
        self.setHomeBtn.setMinimumSize(QtCore.QSize(60, 30))
        self.setHomeBtn.setMaximumSize(QtCore.QSize(1000, 30))
        self.setHomeBtn.setObjectName(_fromUtf8("setHomeBtn"))
        self.trapPadStepGrid.addWidget(self.setHomeBtn, 4, 2, 1, 1)
        self.xTrapPosNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.xTrapPosNumDbl.setReadOnly(True)
        self.xTrapPosNumDbl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.xTrapPosNumDbl.setObjectName(_fromUtf8("xTrapPosNumDbl"))
        self.trapPadStepGrid.addWidget(self.xTrapPosNumDbl, 1, 2, 1, 1)
        self.yTrapPosNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.yTrapPosNumDbl.setReadOnly(True)
        self.yTrapPosNumDbl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.yTrapPosNumDbl.setObjectName(_fromUtf8("yTrapPosNumDbl"))
        self.trapPadStepGrid.addWidget(self.yTrapPosNumDbl, 2, 2, 1, 1)
        self.zTrapPosNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.zTrapPosNumDbl.setReadOnly(True)
        self.zTrapPosNumDbl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.zTrapPosNumDbl.setObjectName(_fromUtf8("zTrapPosNumDbl"))
        self.trapPadStepGrid.addWidget(self.zTrapPosNumDbl, 3, 2, 1, 1)
        self.trapPadStepGrid.setColumnStretch(0, 1)
        self.trapPadStepGrid.setColumnStretch(1, 3)
        self.trapPadStepGrid.setColumnStretch(2, 4)
        self.trapPadStepGrid.setRowStretch(0, 1)
        self.trapPadStepGrid.setRowStretch(1, 2)
        self.trapPadStepGrid.setRowStretch(2, 2)
        self.trapPadStepGrid.setRowStretch(3, 2)
        self.trapPadStepGrid.setRowStretch(4, 4)
        self.stepNspeedHor.addLayout(self.trapPadStepGrid)
        self.line_9 = QtGui.QFrame(self.padPage)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.stepNspeedHor.addWidget(self.line_9)
        self.trapPadSpeedGrid = QtGui.QGridLayout()
        self.trapPadSpeedGrid.setObjectName(_fromUtf8("trapPadSpeedGrid"))
        self.xSpeedTrapPadSlider = QtGui.QSlider(self.padPage)
        self.xSpeedTrapPadSlider.setTracking(False)
        self.xSpeedTrapPadSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xSpeedTrapPadSlider.setObjectName(_fromUtf8("xSpeedTrapPadSlider"))
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadSlider, 1, 0, 1, 1)
        self.ySpeedTrapPadLab = QtGui.QLabel(self.padPage)
        self.ySpeedTrapPadLab.setObjectName(_fromUtf8("ySpeedTrapPadLab"))
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadLab, 2, 0, 1, 1)
        self.xSpeedTrapPadNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.xSpeedTrapPadNumDbl.setKeyboardTracking(False)
        self.xSpeedTrapPadNumDbl.setDecimals(0)
        self.xSpeedTrapPadNumDbl.setObjectName(_fromUtf8("xSpeedTrapPadNumDbl"))
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadNumDbl, 1, 1, 1, 1)
        self.ySpeedTrapPadSlider = QtGui.QSlider(self.padPage)
        self.ySpeedTrapPadSlider.setTracking(False)
        self.ySpeedTrapPadSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ySpeedTrapPadSlider.setObjectName(_fromUtf8("ySpeedTrapPadSlider"))
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadSlider, 3, 0, 1, 1)
        self.ySpeedTrapPadNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.ySpeedTrapPadNumDbl.setKeyboardTracking(False)
        self.ySpeedTrapPadNumDbl.setDecimals(0)
        self.ySpeedTrapPadNumDbl.setObjectName(_fromUtf8("ySpeedTrapPadNumDbl"))
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadNumDbl, 3, 1, 1, 1)
        self.zSpeedTrapPadLab = QtGui.QLabel(self.padPage)
        self.zSpeedTrapPadLab.setObjectName(_fromUtf8("zSpeedTrapPadLab"))
        self.trapPadSpeedGrid.addWidget(self.zSpeedTrapPadLab, 4, 0, 1, 1)
        self.xSpeedTrapPadLab = QtGui.QLabel(self.padPage)
        self.xSpeedTrapPadLab.setObjectName(_fromUtf8("xSpeedTrapPadLab"))
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadLab, 0, 0, 1, 1)
        self.zSpeedTrapPadSlider = QtGui.QSlider(self.padPage)
        self.zSpeedTrapPadSlider.setTracking(False)
        self.zSpeedTrapPadSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zSpeedTrapPadSlider.setObjectName(_fromUtf8("zSpeedTrapPadSlider"))
        self.trapPadSpeedGrid.addWidget(self.zSpeedTrapPadSlider, 5, 0, 1, 1)
        self.zSpeedTrapPadNumDbl = QtGui.QDoubleSpinBox(self.padPage)
        self.zSpeedTrapPadNumDbl.setKeyboardTracking(False)
        self.zSpeedTrapPadNumDbl.setDecimals(0)
        self.zSpeedTrapPadNumDbl.setMaximum(5000.0)
        self.zSpeedTrapPadNumDbl.setObjectName(_fromUtf8("zSpeedTrapPadNumDbl"))
        self.trapPadSpeedGrid.addWidget(self.zSpeedTrapPadNumDbl, 5, 1, 1, 1)
        self.trapPadSpeedGrid.setColumnStretch(0, 3)
        self.trapPadSpeedGrid.setColumnStretch(1, 2)
        self.trapPadSpeedGrid.setRowStretch(0, 1)
        self.stepNspeedHor.addLayout(self.trapPadSpeedGrid)
        self.stepNspeedHor.setStretch(0, 4)
        self.stepNspeedHor.setStretch(1, 1)
        self.stepNspeedHor.setStretch(2, 4)
        self.padVert.addLayout(self.stepNspeedHor)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.padVert.addItem(spacerItem3)
        self.padVert.setStretch(0, 5)
        self.fbToolBox.addItem(self.padPage, _fromUtf8(""))
        self.otherPage = QtGui.QWidget()
        self.otherPage.setGeometry(QtCore.QRect(0, 0, 173, 186))
        self.otherPage.setObjectName(_fromUtf8("otherPage"))
        self.otherGrid = QtGui.QGridLayout(self.otherPage)
        self.otherGrid.setObjectName(_fromUtf8("otherGrid"))
        self.zOffSetNumDbl = QtGui.QDoubleSpinBox(self.otherPage)
        self.zOffSetNumDbl.setObjectName(_fromUtf8("zOffSetNumDbl"))
        self.otherGrid.addWidget(self.zOffSetNumDbl, 2, 2, 1, 1)
        self.yOffSetDial = QtGui.QDial(self.otherPage)
        self.yOffSetDial.setObjectName(_fromUtf8("yOffSetDial"))
        self.otherGrid.addWidget(self.yOffSetDial, 1, 1, 1, 1)
        self.yOffSetNumDbl = QtGui.QDoubleSpinBox(self.otherPage)
        self.yOffSetNumDbl.setObjectName(_fromUtf8("yOffSetNumDbl"))
        self.otherGrid.addWidget(self.yOffSetNumDbl, 1, 2, 1, 1)
        self.yOffSetLab = QtGui.QLabel(self.otherPage)
        self.yOffSetLab.setObjectName(_fromUtf8("yOffSetLab"))
        self.otherGrid.addWidget(self.yOffSetLab, 1, 0, 1, 1)
        self.xOffSetNumDbl = QtGui.QDoubleSpinBox(self.otherPage)
        self.xOffSetNumDbl.setObjectName(_fromUtf8("xOffSetNumDbl"))
        self.otherGrid.addWidget(self.xOffSetNumDbl, 0, 2, 1, 1)
        self.zOffSetLab = QtGui.QLabel(self.otherPage)
        self.zOffSetLab.setObjectName(_fromUtf8("zOffSetLab"))
        self.otherGrid.addWidget(self.zOffSetLab, 2, 0, 1, 1)
        self.zOffSetDial = QtGui.QDial(self.otherPage)
        self.zOffSetDial.setObjectName(_fromUtf8("zOffSetDial"))
        self.otherGrid.addWidget(self.zOffSetDial, 2, 1, 1, 1)
        self.xOffSetDial = QtGui.QDial(self.otherPage)
        self.xOffSetDial.setObjectName(_fromUtf8("xOffSetDial"))
        self.otherGrid.addWidget(self.xOffSetDial, 0, 1, 1, 1)
        self.xOffSetLab = QtGui.QLabel(self.otherPage)
        self.xOffSetLab.setObjectName(_fromUtf8("xOffSetLab"))
        self.otherGrid.addWidget(self.xOffSetLab, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.otherGrid.addItem(spacerItem4, 1, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.otherGrid.addItem(spacerItem5, 3, 1, 1, 1)
        self.otherGrid.setRowMinimumHeight(0, 1)
        self.otherGrid.setRowMinimumHeight(1, 9)
        self.otherGrid.setRowMinimumHeight(2, 7)
        self.otherGrid.setColumnStretch(0, 1)
        self.otherGrid.setColumnStretch(1, 9)
        self.otherGrid.setColumnStretch(2, 7)
        self.otherGrid.setColumnStretch(3, 10)
        self.fbToolBox.addItem(self.otherPage, _fromUtf8(""))
        self.fbFrameVert.addWidget(self.fbToolBox)
        self.plotNfbHor.addWidget(self.fbFrame)
        self.plotNfbHor.setStretch(0, 5)
        self.plotNfbHor.setStretch(1, 1)
        self.sysCtrlVert.addLayout(self.plotNfbHor)
        self.posNmodHor = QtGui.QHBoxLayout()
        self.posNmodHor.setObjectName(_fromUtf8("posNmodHor"))
        self.trapPosXYPlot = PlotWidget(self.mainGuiWid)
        self.trapPosXYPlot.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trapPosXYPlot.sizePolicy().hasHeightForWidth())
        self.trapPosXYPlot.setSizePolicy(sizePolicy)
        self.trapPosXYPlot.setMinimumSize(QtCore.QSize(280, 280))
        self.trapPosXYPlot.setMaximumSize(QtCore.QSize(280, 280))
        self.trapPosXYPlot.setSizeIncrement(QtCore.QSize(0, 0))
        self.trapPosXYPlot.setObjectName(_fromUtf8("trapPosXYPlot"))
        self.posNmodHor.addWidget(self.trapPosXYPlot)
        self.modTabs = QtGui.QTabWidget(self.mainGuiWid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modTabs.sizePolicy().hasHeightForWidth())
        self.modTabs.setSizePolicy(sizePolicy)
        self.modTabs.setMinimumSize(QtCore.QSize(0, 280))
        self.modTabs.setMaximumSize(QtCore.QSize(16777215, 280))
        self.modTabs.setObjectName(_fromUtf8("modTabs"))
        self.calibPage = QtGui.QWidget()
        self.calibPage.setObjectName(_fromUtf8("calibPage"))
        self.calibTabHor = QtGui.QHBoxLayout(self.calibPage)
        self.calibTabHor.setObjectName(_fromUtf8("calibTabHor"))
        self.calTypeTab = QtGui.QTabWidget(self.calibPage)
        self.calTypeTab.setObjectName(_fromUtf8("calTypeTab"))
        self.calPassivePage = QtGui.QWidget()
        self.calPassivePage.setObjectName(_fromUtf8("calPassivePage"))
        self.passiveCalForm = QtGui.QFormLayout(self.calPassivePage)
        self.passiveCalForm.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.passiveCalForm.setObjectName(_fromUtf8("passiveCalForm"))
        self.passiveCalDurLab = QtGui.QLabel(self.calPassivePage)
        self.passiveCalDurLab.setObjectName(_fromUtf8("passiveCalDurLab"))
        self.passiveCalForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.passiveCalDurLab)
        self.passiveCalDurNumDbl = QtGui.QDoubleSpinBox(self.calPassivePage)
        self.passiveCalDurNumDbl.setMaximum(10000.0)
        self.passiveCalDurNumDbl.setObjectName(_fromUtf8("passiveCalDurNumDbl"))
        self.passiveCalForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.passiveCalDurNumDbl)
        self.passiveCalMaxFreqLab = QtGui.QLabel(self.calPassivePage)
        self.passiveCalMaxFreqLab.setObjectName(_fromUtf8("passiveCalMaxFreqLab"))
        self.passiveCalForm.setWidget(2, QtGui.QFormLayout.LabelRole, self.passiveCalMaxFreqLab)
        self.passiveCalMaxFreqNumDbl = QtGui.QDoubleSpinBox(self.calPassivePage)
        self.passiveCalMaxFreqNumDbl.setObjectName(_fromUtf8("passiveCalMaxFreqNumDbl"))
        self.passiveCalForm.setWidget(2, QtGui.QFormLayout.FieldRole, self.passiveCalMaxFreqNumDbl)
        self.passiveCalAvgLav = QtGui.QLabel(self.calPassivePage)
        self.passiveCalAvgLav.setObjectName(_fromUtf8("passiveCalAvgLav"))
        self.passiveCalForm.setWidget(3, QtGui.QFormLayout.LabelRole, self.passiveCalAvgLav)
        self.passiveCalAvgNum = QtGui.QSpinBox(self.calPassivePage)
        self.passiveCalAvgNum.setMaximum(1000)
        self.passiveCalAvgNum.setObjectName(_fromUtf8("passiveCalAvgNum"))
        self.passiveCalForm.setWidget(3, QtGui.QFormLayout.FieldRole, self.passiveCalAvgNum)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.passiveCalForm.setItem(4, QtGui.QFormLayout.LabelRole, spacerItem6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.passiveCalForm.setItem(5, QtGui.QFormLayout.LabelRole, spacerItem7)
        self.passiveCalStartBtn = QtGui.QPushButton(self.calPassivePage)
        self.passiveCalStartBtn.setObjectName(_fromUtf8("passiveCalStartBtn"))
        self.passiveCalForm.setWidget(6, QtGui.QFormLayout.SpanningRole, self.passiveCalStartBtn)
        self.calTypeTab.addTab(self.calPassivePage, _fromUtf8(""))
        self.calActivePage = QtGui.QWidget()
        self.calActivePage.setObjectName(_fromUtf8("calActivePage"))
        self.ativeCalVert = QtGui.QVBoxLayout(self.calActivePage)
        self.ativeCalVert.setObjectName(_fromUtf8("ativeCalVert"))
        self.activeCalSinsConfGrid = QtGui.QGridLayout()
        self.activeCalSinsConfGrid.setObjectName(_fromUtf8("activeCalSinsConfGrid"))
        self.activeCalYLab = QtGui.QLabel(self.calActivePage)
        self.activeCalYLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalYLab.setObjectName(_fromUtf8("activeCalYLab"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalYLab, 0, 2, 1, 1)
        self.activeCalZLab = QtGui.QLabel(self.calActivePage)
        self.activeCalZLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalZLab.setObjectName(_fromUtf8("activeCalZLab"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalZLab, 0, 3, 1, 1)
        self.activeCalAmpLab = QtGui.QLabel(self.calActivePage)
        self.activeCalAmpLab.setObjectName(_fromUtf8("activeCalAmpLab"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalAmpLab, 1, 0, 1, 1)
        self.activeCalXLab = QtGui.QLabel(self.calActivePage)
        self.activeCalXLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalXLab.setObjectName(_fromUtf8("activeCalXLab"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalXLab, 0, 1, 1, 1)
        self.activeCalFreqLab = QtGui.QLabel(self.calActivePage)
        self.activeCalFreqLab.setObjectName(_fromUtf8("activeCalFreqLab"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalFreqLab, 2, 0, 1, 1)
        self.activeCalXAmplNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalXAmplNumDbl.setObjectName(_fromUtf8("activeCalXAmplNumDbl"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalXAmplNumDbl, 1, 1, 1, 1)
        self.activeCalYAmplNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalYAmplNumDbl.setObjectName(_fromUtf8("activeCalYAmplNumDbl"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalYAmplNumDbl, 1, 2, 1, 1)
        self.activeCalZAmplNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalZAmplNumDbl.setObjectName(_fromUtf8("activeCalZAmplNumDbl"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalZAmplNumDbl, 1, 3, 1, 1)
        self.activeCalXFreqNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalXFreqNumDbl.setObjectName(_fromUtf8("activeCalXFreqNumDbl"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalXFreqNumDbl, 2, 1, 1, 1)
        self.activeCalYFreqNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalYFreqNumDbl.setObjectName(_fromUtf8("activeCalYFreqNumDbl"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalYFreqNumDbl, 2, 2, 1, 1)
        self.activeCalZFreqNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalZFreqNumDbl.setObjectName(_fromUtf8("activeCalZFreqNumDbl"))
        self.activeCalSinsConfGrid.addWidget(self.activeCalZFreqNumDbl, 2, 3, 1, 1)
        self.activeCalSinsConfGrid.setRowStretch(1, 3)
        self.activeCalSinsConfGrid.setRowStretch(2, 2)
        self.ativeCalVert.addLayout(self.activeCalSinsConfGrid)
        self.activeConfForm = QtGui.QFormLayout()
        self.activeConfForm.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.activeConfForm.setObjectName(_fromUtf8("activeConfForm"))
        self.activeCalDurLab = QtGui.QLabel(self.calActivePage)
        self.activeCalDurLab.setObjectName(_fromUtf8("activeCalDurLab"))
        self.activeConfForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.activeCalDurLab)
        self.activeCalDurNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalDurNumDbl.setObjectName(_fromUtf8("activeCalDurNumDbl"))
        self.activeConfForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.activeCalDurNumDbl)
        self.activeCalMaxFreqLab = QtGui.QLabel(self.calActivePage)
        self.activeCalMaxFreqLab.setObjectName(_fromUtf8("activeCalMaxFreqLab"))
        self.activeConfForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.activeCalMaxFreqLab)
        self.activeCalMaxFreqNumDbl = QtGui.QDoubleSpinBox(self.calActivePage)
        self.activeCalMaxFreqNumDbl.setObjectName(_fromUtf8("activeCalMaxFreqNumDbl"))
        self.activeConfForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.activeCalMaxFreqNumDbl)
        self.activeCalAvgLab = QtGui.QLabel(self.calActivePage)
        self.activeCalAvgLab.setObjectName(_fromUtf8("activeCalAvgLab"))
        self.activeConfForm.setWidget(2, QtGui.QFormLayout.LabelRole, self.activeCalAvgLab)
        self.activeCalAvgNum = QtGui.QSpinBox(self.calActivePage)
        self.activeCalAvgNum.setObjectName(_fromUtf8("activeCalAvgNum"))
        self.activeConfForm.setWidget(2, QtGui.QFormLayout.FieldRole, self.activeCalAvgNum)
        self.ativeCalVert.addLayout(self.activeConfForm)
        self.activeCalStartBtn = QtGui.QPushButton(self.calActivePage)
        self.activeCalStartBtn.setObjectName(_fromUtf8("activeCalStartBtn"))
        self.ativeCalVert.addWidget(self.activeCalStartBtn)
        self.ativeCalVert.setStretch(0, 1)
        self.ativeCalVert.setStretch(1, 1)
        self.calTypeTab.addTab(self.calActivePage, _fromUtf8(""))
        self.calibTabHor.addWidget(self.calTypeTab)
        self.genParVert = QtGui.QVBoxLayout()
        self.genParVert.setObjectName(_fromUtf8("genParVert"))
        self.genParBox = QtGui.QGroupBox(self.calibPage)
        self.genParBox.setObjectName(_fromUtf8("genParBox"))
        self.genParForm = QtGui.QFormLayout(self.genParBox)
        self.genParForm.setObjectName(_fromUtf8("genParForm"))
        self.radiusNumDbl = QtGui.QDoubleSpinBox(self.genParBox)
        self.radiusNumDbl.setMaximum(1000.0)
        self.radiusNumDbl.setObjectName(_fromUtf8("radiusNumDbl"))
        self.genParForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.radiusNumDbl)
        self.dynViscNumDbl = QtGui.QDoubleSpinBox(self.genParBox)
        self.dynViscNumDbl.setMaximum(10000.0)
        self.dynViscNumDbl.setObjectName(_fromUtf8("dynViscNumDbl"))
        self.genParForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.dynViscNumDbl)
        self.dynViscLab = QtGui.QLabel(self.genParBox)
        self.dynViscLab.setObjectName(_fromUtf8("dynViscLab"))
        self.genParForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.dynViscLab)
        self.radiusLab = QtGui.QLabel(self.genParBox)
        self.radiusLab.setObjectName(_fromUtf8("radiusLab"))
        self.genParForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.radiusLab)
        self.genParVert.addWidget(self.genParBox)
        self.calibTabHor.addLayout(self.genParVert)
        self.calResultsBox = QtGui.QGroupBox(self.calibPage)
        self.calResultsBox.setObjectName(_fromUtf8("calResultsBox"))
        self.formLayout_7 = QtGui.QFormLayout(self.calResultsBox)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.kxLab = QtGui.QLabel(self.calResultsBox)
        self.kxLab.setObjectName(_fromUtf8("kxLab"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.kxLab)
        self.kxNumDbl = QtGui.QDoubleSpinBox(self.calResultsBox)
        self.kxNumDbl.setMaximum(10000.0)
        self.kxNumDbl.setObjectName(_fromUtf8("kxNumDbl"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.kxNumDbl)
        self.kyLab = QtGui.QLabel(self.calResultsBox)
        self.kyLab.setObjectName(_fromUtf8("kyLab"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.kyLab)
        self.kyNumDbl = QtGui.QDoubleSpinBox(self.calResultsBox)
        self.kyNumDbl.setMaximum(10000.0)
        self.kyNumDbl.setObjectName(_fromUtf8("kyNumDbl"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.kyNumDbl)
        self.kzLab = QtGui.QLabel(self.calResultsBox)
        self.kzLab.setObjectName(_fromUtf8("kzLab"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.kzLab)
        self.kzNumDbl = QtGui.QDoubleSpinBox(self.calResultsBox)
        self.kzNumDbl.setMaximum(10000.0)
        self.kzNumDbl.setObjectName(_fromUtf8("kzNumDbl"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.kzNumDbl)
        self.SxNumDbl = QtGui.QDoubleSpinBox(self.calResultsBox)
        self.SxNumDbl.setMaximum(10000.0)
        self.SxNumDbl.setObjectName(_fromUtf8("SxNumDbl"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.SxNumDbl)
        self.SyNumDbl = QtGui.QDoubleSpinBox(self.calResultsBox)
        self.SyNumDbl.setMaximum(10000.0)
        self.SyNumDbl.setObjectName(_fromUtf8("SyNumDbl"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.SyNumDbl)
        self.SzNumDbl = QtGui.QDoubleSpinBox(self.calResultsBox)
        self.SzNumDbl.setMaximum(10000.0)
        self.SzNumDbl.setObjectName(_fromUtf8("SzNumDbl"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.SzNumDbl)
        self.SxLab = QtGui.QLabel(self.calResultsBox)
        self.SxLab.setObjectName(_fromUtf8("SxLab"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.SxLab)
        self.SyLab = QtGui.QLabel(self.calResultsBox)
        self.SyLab.setObjectName(_fromUtf8("SyLab"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.SyLab)
        self.SzLab = QtGui.QLabel(self.calResultsBox)
        self.SzLab.setObjectName(_fromUtf8("SzLab"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.SzLab)
        self.calibTabHor.addWidget(self.calResultsBox)
        self.calibTabHor.setStretch(1, 2)
        self.calibTabHor.setStretch(2, 2)
        self.modTabs.addTab(self.calibPage, _fromUtf8(""))
        self.stdExpPage = QtGui.QWidget()
        self.stdExpPage.setObjectName(_fromUtf8("stdExpPage"))
        self.stdExpHor = QtGui.QHBoxLayout(self.stdExpPage)
        self.stdExpHor.setObjectName(_fromUtf8("stdExpHor"))
        self.stdExpConfigGrid = QtGui.QGridLayout()
        self.stdExpConfigGrid.setObjectName(_fromUtf8("stdExpConfigGrid"))
        self.stdExpDurNumDbl = QtGui.QDoubleSpinBox(self.stdExpPage)
        self.stdExpDurNumDbl.setObjectName(_fromUtf8("stdExpDurNumDbl"))
        self.stdExpConfigGrid.addWidget(self.stdExpDurNumDbl, 5, 2, 1, 1)
        self.line = QtGui.QFrame(self.stdExpPage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.stdExpConfigGrid.addWidget(self.line, 4, 0, 1, 3)
        self.stdExpXLab = QtGui.QLabel(self.stdExpPage)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.stdExpXLab.setFont(font)
        self.stdExpXLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpXLab.setObjectName(_fromUtf8("stdExpXLab"))
        self.stdExpConfigGrid.addWidget(self.stdExpXLab, 1, 0, 1, 1)
        self.stdExpSetPointLab = QtGui.QLabel(self.stdExpPage)
        self.stdExpSetPointLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpSetPointLab.setObjectName(_fromUtf8("stdExpSetPointLab"))
        self.stdExpConfigGrid.addWidget(self.stdExpSetPointLab, 0, 1, 1, 1)
        self.stdExpXSetPntNumDbl = QtGui.QDoubleSpinBox(self.stdExpPage)
        self.stdExpXSetPntNumDbl.setObjectName(_fromUtf8("stdExpXSetPntNumDbl"))
        self.stdExpConfigGrid.addWidget(self.stdExpXSetPntNumDbl, 1, 1, 1, 1)
        self.stdExpAxisLab = QtGui.QLabel(self.stdExpPage)
        self.stdExpAxisLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpAxisLab.setObjectName(_fromUtf8("stdExpAxisLab"))
        self.stdExpConfigGrid.addWidget(self.stdExpAxisLab, 0, 0, 1, 1)
        self.stdExpZSetPntNumDbl = QtGui.QDoubleSpinBox(self.stdExpPage)
        self.stdExpZSetPntNumDbl.setObjectName(_fromUtf8("stdExpZSetPntNumDbl"))
        self.stdExpConfigGrid.addWidget(self.stdExpZSetPntNumDbl, 3, 1, 1, 1)
        self.stdExpZLab = QtGui.QLabel(self.stdExpPage)
        self.stdExpZLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpZLab.setObjectName(_fromUtf8("stdExpZLab"))
        self.stdExpConfigGrid.addWidget(self.stdExpZLab, 3, 0, 1, 1)
        self.stdExpYEqForceVsMaxLine = QtGui.QLineEdit(self.stdExpPage)
        self.stdExpYEqForceVsMaxLine.setReadOnly(True)
        self.stdExpYEqForceVsMaxLine.setObjectName(_fromUtf8("stdExpYEqForceVsMaxLine"))
        self.stdExpConfigGrid.addWidget(self.stdExpYEqForceVsMaxLine, 2, 2, 1, 1)
        self.stdExpXEqForceVsMaxLine = QtGui.QLineEdit(self.stdExpPage)
        self.stdExpXEqForceVsMaxLine.setReadOnly(True)
        self.stdExpXEqForceVsMaxLine.setObjectName(_fromUtf8("stdExpXEqForceVsMaxLine"))
        self.stdExpConfigGrid.addWidget(self.stdExpXEqForceVsMaxLine, 1, 2, 1, 1)
        self.stdExpYSetPntNumDbl = QtGui.QDoubleSpinBox(self.stdExpPage)
        self.stdExpYSetPntNumDbl.setObjectName(_fromUtf8("stdExpYSetPntNumDbl"))
        self.stdExpConfigGrid.addWidget(self.stdExpYSetPntNumDbl, 2, 1, 1, 1)
        self.stdExpEqForceVsMaxLab = QtGui.QLabel(self.stdExpPage)
        self.stdExpEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpEqForceVsMaxLab.setObjectName(_fromUtf8("stdExpEqForceVsMaxLab"))
        self.stdExpConfigGrid.addWidget(self.stdExpEqForceVsMaxLab, 0, 2, 1, 1)
        self.stdExpYLab = QtGui.QLabel(self.stdExpPage)
        self.stdExpYLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpYLab.setObjectName(_fromUtf8("stdExpYLab"))
        self.stdExpConfigGrid.addWidget(self.stdExpYLab, 2, 0, 1, 1)
        self.stdExpZEqForceVsMaxLine = QtGui.QLineEdit(self.stdExpPage)
        self.stdExpZEqForceVsMaxLine.setReadOnly(True)
        self.stdExpZEqForceVsMaxLine.setObjectName(_fromUtf8("stdExpZEqForceVsMaxLine"))
        self.stdExpConfigGrid.addWidget(self.stdExpZEqForceVsMaxLine, 3, 2, 1, 1)
        self.stdExpDurLab = QtGui.QLabel(self.stdExpPage)
        self.stdExpDurLab.setObjectName(_fromUtf8("stdExpDurLab"))
        self.stdExpConfigGrid.addWidget(self.stdExpDurLab, 5, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.stdExpConfigGrid.addItem(spacerItem8, 6, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.stdExpConfigGrid.addItem(spacerItem9, 7, 1, 1, 1)
        self.stdExpConfigGrid.setColumnStretch(0, 1)
        self.stdExpConfigGrid.setColumnStretch(1, 2)
        self.stdExpConfigGrid.setColumnStretch(2, 2)
        self.stdExpConfigGrid.setRowStretch(0, 1)
        self.stdExpConfigGrid.setRowStretch(1, 1)
        self.stdExpConfigGrid.setRowStretch(2, 1)
        self.stdExpConfigGrid.setRowStretch(3, 1)
        self.stdExpConfigGrid.setRowStretch(4, 1)
        self.stdExpHor.addLayout(self.stdExpConfigGrid)
        self.fbSchedVert = QtGui.QVBoxLayout()
        self.fbSchedVert.setObjectName(_fromUtf8("fbSchedVert"))
        self.fbSchedBox = QtGui.QGroupBox(self.stdExpPage)
        self.fbSchedBox.setObjectName(_fromUtf8("fbSchedBox"))
        self.formLayout_12 = QtGui.QFormLayout(self.fbSchedBox)
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.fbSchedNumIntLab = QtGui.QLabel(self.fbSchedBox)
        self.fbSchedNumIntLab.setObjectName(_fromUtf8("fbSchedNumIntLab"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.fbSchedNumIntLab)
        self.fbSchedNumIntNum = QtGui.QSpinBox(self.fbSchedBox)
        self.fbSchedNumIntNum.setObjectName(_fromUtf8("fbSchedNumIntNum"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.fbSchedNumIntNum)
        self.fbSchedOnDurLab = QtGui.QLabel(self.fbSchedBox)
        self.fbSchedOnDurLab.setObjectName(_fromUtf8("fbSchedOnDurLab"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.fbSchedOnDurLab)
        self.fbSchedOnDurNumDbl = QtGui.QDoubleSpinBox(self.fbSchedBox)
        self.fbSchedOnDurNumDbl.setObjectName(_fromUtf8("fbSchedOnDurNumDbl"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.fbSchedOnDurNumDbl)
        self.fbSchedOffDurLab = QtGui.QLabel(self.fbSchedBox)
        self.fbSchedOffDurLab.setObjectName(_fromUtf8("fbSchedOffDurLab"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.LabelRole, self.fbSchedOffDurLab)
        self.fbSchedOffDurNumDbl = QtGui.QDoubleSpinBox(self.fbSchedBox)
        self.fbSchedOffDurNumDbl.setObjectName(_fromUtf8("fbSchedOffDurNumDbl"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.FieldRole, self.fbSchedOffDurNumDbl)
        self.fbSchedStartOnCheck = QtGui.QCheckBox(self.fbSchedBox)
        self.fbSchedStartOnCheck.setTristate(False)
        self.fbSchedStartOnCheck.setObjectName(_fromUtf8("fbSchedStartOnCheck"))
        self.formLayout_12.setWidget(3, QtGui.QFormLayout.LabelRole, self.fbSchedStartOnCheck)
        self.fbSchedVert.addWidget(self.fbSchedBox)
        self.stdExpStartBtn = QtGui.QPushButton(self.stdExpPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdExpStartBtn.sizePolicy().hasHeightForWidth())
        self.stdExpStartBtn.setSizePolicy(sizePolicy)
        self.stdExpStartBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.stdExpStartBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stdExpStartBtn.setObjectName(_fromUtf8("stdExpStartBtn"))
        self.fbSchedVert.addWidget(self.stdExpStartBtn)
        self.fbSchedVert.setStretch(0, 1)
        self.fbSchedVert.setStretch(1, 1)
        self.stdExpHor.addLayout(self.fbSchedVert)
        self.stdExpHor.setStretch(0, 3)
        self.stdExpHor.setStretch(1, 2)
        self.modTabs.addTab(self.stdExpPage, _fromUtf8(""))
        self.custExpPage = QtGui.QWidget()
        self.custExpPage.setObjectName(_fromUtf8("custExpPage"))
        self.custExpVert = QtGui.QVBoxLayout(self.custExpPage)
        self.custExpVert.setObjectName(_fromUtf8("custExpVert"))
        self.customExpAxisTabs = QtGui.QTabWidget(self.custExpPage)
        self.customExpAxisTabs.setObjectName(_fromUtf8("customExpAxisTabs"))
        self.customExpXPage = QtGui.QWidget()
        self.customExpXPage.setObjectName(_fromUtf8("customExpXPage"))
        self.custExpXVert = QtGui.QVBoxLayout(self.customExpXPage)
        self.custExpXVert.setObjectName(_fromUtf8("custExpXVert"))
        self.customExpXConfGrid = QtGui.QGridLayout()
        self.customExpXConfGrid.setObjectName(_fromUtf8("customExpXConfGrid"))
        self.customExpXOnDurNumDbl = QtGui.QDoubleSpinBox(self.customExpXPage)
        self.customExpXOnDurNumDbl.setObjectName(_fromUtf8("customExpXOnDurNumDbl"))
        self.customExpXConfGrid.addWidget(self.customExpXOnDurNumDbl, 2, 1, 1, 1)
        self.customExpXMultiIntCheck = QtGui.QCheckBox(self.customExpXPage)
        self.customExpXMultiIntCheck.setObjectName(_fromUtf8("customExpXMultiIntCheck"))
        self.customExpXConfGrid.addWidget(self.customExpXMultiIntCheck, 0, 0, 1, 1)
        self.customExpXNumIntLab = QtGui.QLabel(self.customExpXPage)
        self.customExpXNumIntLab.setObjectName(_fromUtf8("customExpXNumIntLab"))
        self.customExpXConfGrid.addWidget(self.customExpXNumIntLab, 1, 0, 1, 1)
        self.customExpXOffDurNumDbl = QtGui.QDoubleSpinBox(self.customExpXPage)
        self.customExpXOffDurNumDbl.setObjectName(_fromUtf8("customExpXOffDurNumDbl"))
        self.customExpXConfGrid.addWidget(self.customExpXOffDurNumDbl, 3, 1, 1, 1)
        self.customExpXOnDurLab = QtGui.QLabel(self.customExpXPage)
        self.customExpXOnDurLab.setObjectName(_fromUtf8("customExpXOnDurLab"))
        self.customExpXConfGrid.addWidget(self.customExpXOnDurLab, 2, 0, 1, 1)
        self.customExpXOffDurLab = QtGui.QLabel(self.customExpXPage)
        self.customExpXOffDurLab.setObjectName(_fromUtf8("customExpXOffDurLab"))
        self.customExpXConfGrid.addWidget(self.customExpXOffDurLab, 3, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpXConfGrid.addItem(spacerItem10, 2, 2, 1, 1)
        self.customExpXStartOnCheck = QtGui.QCheckBox(self.customExpXPage)
        self.customExpXStartOnCheck.setObjectName(_fromUtf8("customExpXStartOnCheck"))
        self.customExpXConfGrid.addWidget(self.customExpXStartOnCheck, 4, 0, 1, 1)
        self.customExpXNumIntNum = QtGui.QSpinBox(self.customExpXPage)
        self.customExpXNumIntNum.setObjectName(_fromUtf8("customExpXNumIntNum"))
        self.customExpXConfGrid.addWidget(self.customExpXNumIntNum, 1, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpXConfGrid.addItem(spacerItem11, 2, 3, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpXConfGrid.addItem(spacerItem12, 2, 4, 1, 1)
        self.customExpXConfGrid.setColumnStretch(0, 1)
        self.customExpXConfGrid.setColumnStretch(1, 1)
        self.customExpXConfGrid.setColumnStretch(2, 1)
        self.customExpXConfGrid.setColumnStretch(3, 1)
        self.customExpXConfGrid.setColumnStretch(4, 1)
        self.custExpXVert.addLayout(self.customExpXConfGrid)
        self.customExpXWFGrid = QtGui.QGridLayout()
        self.customExpXWFGrid.setObjectName(_fromUtf8("customExpXWFGrid"))
        self.customExpXAmplNumDbl = QtGui.QDoubleSpinBox(self.customExpXPage)
        self.customExpXAmplNumDbl.setObjectName(_fromUtf8("customExpXAmplNumDbl"))
        self.customExpXWFGrid.addWidget(self.customExpXAmplNumDbl, 1, 2, 1, 1)
        self.customExpXWFLab = QtGui.QLabel(self.customExpXPage)
        self.customExpXWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXWFLab.setObjectName(_fromUtf8("customExpXWFLab"))
        self.customExpXWFGrid.addWidget(self.customExpXWFLab, 0, 0, 1, 1)
        self.customExpXFreqLab = QtGui.QLabel(self.customExpXPage)
        self.customExpXFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXFreqLab.setObjectName(_fromUtf8("customExpXFreqLab"))
        self.customExpXWFGrid.addWidget(self.customExpXFreqLab, 0, 1, 1, 1)
        self.customExpXAmplLab = QtGui.QLabel(self.customExpXPage)
        self.customExpXAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXAmplLab.setObjectName(_fromUtf8("customExpXAmplLab"))
        self.customExpXWFGrid.addWidget(self.customExpXAmplLab, 0, 2, 1, 1)
        self.customExpXFreqNumDbl = QtGui.QDoubleSpinBox(self.customExpXPage)
        self.customExpXFreqNumDbl.setObjectName(_fromUtf8("customExpXFreqNumDbl"))
        self.customExpXWFGrid.addWidget(self.customExpXFreqNumDbl, 1, 1, 1, 1)
        self.customExpXWFCmb = QtGui.QComboBox(self.customExpXPage)
        self.customExpXWFCmb.setObjectName(_fromUtf8("customExpXWFCmb"))
        self.customExpXWFGrid.addWidget(self.customExpXWFCmb, 1, 0, 1, 1)
        self.customExpXEqForceVsMaxLine = QtGui.QLineEdit(self.customExpXPage)
        self.customExpXEqForceVsMaxLine.setReadOnly(True)
        self.customExpXEqForceVsMaxLine.setObjectName(_fromUtf8("customExpXEqForceVsMaxLine"))
        self.customExpXWFGrid.addWidget(self.customExpXEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpXEqForceVsMaxLab = QtGui.QLabel(self.customExpXPage)
        self.customExpXEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXEqForceVsMaxLab.setObjectName(_fromUtf8("customExpXEqForceVsMaxLab"))
        self.customExpXWFGrid.addWidget(self.customExpXEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpXWFGrid.setColumnStretch(0, 2)
        self.customExpXWFGrid.setColumnStretch(1, 1)
        self.customExpXWFGrid.setColumnStretch(2, 1)
        self.customExpXWFGrid.setColumnStretch(3, 1)
        self.custExpXVert.addLayout(self.customExpXWFGrid)
        self.custExpXVert.setStretch(0, 1)
        self.custExpXVert.setStretch(1, 1)
        self.customExpAxisTabs.addTab(self.customExpXPage, _fromUtf8(""))
        self.customExpYPage = QtGui.QWidget()
        self.customExpYPage.setObjectName(_fromUtf8("customExpYPage"))
        self.custExpYVert = QtGui.QVBoxLayout(self.customExpYPage)
        self.custExpYVert.setObjectName(_fromUtf8("custExpYVert"))
        self.customExpYConfGrid = QtGui.QGridLayout()
        self.customExpYConfGrid.setObjectName(_fromUtf8("customExpYConfGrid"))
        self.customExpYNumIntNum = QtGui.QSpinBox(self.customExpYPage)
        self.customExpYNumIntNum.setObjectName(_fromUtf8("customExpYNumIntNum"))
        self.customExpYConfGrid.addWidget(self.customExpYNumIntNum, 1, 1, 1, 1)
        self.customExpYOnDurNumDbl = QtGui.QDoubleSpinBox(self.customExpYPage)
        self.customExpYOnDurNumDbl.setObjectName(_fromUtf8("customExpYOnDurNumDbl"))
        self.customExpYConfGrid.addWidget(self.customExpYOnDurNumDbl, 2, 1, 1, 1)
        self.customExpYStartOnCheck = QtGui.QCheckBox(self.customExpYPage)
        self.customExpYStartOnCheck.setObjectName(_fromUtf8("customExpYStartOnCheck"))
        self.customExpYConfGrid.addWidget(self.customExpYStartOnCheck, 4, 0, 1, 1)
        self.customExpYNumIntLab = QtGui.QLabel(self.customExpYPage)
        self.customExpYNumIntLab.setObjectName(_fromUtf8("customExpYNumIntLab"))
        self.customExpYConfGrid.addWidget(self.customExpYNumIntLab, 1, 0, 1, 1)
        self.customExpYOffDurLab = QtGui.QLabel(self.customExpYPage)
        self.customExpYOffDurLab.setObjectName(_fromUtf8("customExpYOffDurLab"))
        self.customExpYConfGrid.addWidget(self.customExpYOffDurLab, 3, 0, 1, 1)
        self.customExpYOffDurNumDbl = QtGui.QDoubleSpinBox(self.customExpYPage)
        self.customExpYOffDurNumDbl.setObjectName(_fromUtf8("customExpYOffDurNumDbl"))
        self.customExpYConfGrid.addWidget(self.customExpYOffDurNumDbl, 3, 1, 1, 1)
        self.customExpYOnDurLab = QtGui.QLabel(self.customExpYPage)
        self.customExpYOnDurLab.setObjectName(_fromUtf8("customExpYOnDurLab"))
        self.customExpYConfGrid.addWidget(self.customExpYOnDurLab, 2, 0, 1, 1)
        self.customExpYMultiIntCheck = QtGui.QCheckBox(self.customExpYPage)
        self.customExpYMultiIntCheck.setObjectName(_fromUtf8("customExpYMultiIntCheck"))
        self.customExpYConfGrid.addWidget(self.customExpYMultiIntCheck, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpYConfGrid.addItem(spacerItem13, 2, 2, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpYConfGrid.addItem(spacerItem14, 2, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpYConfGrid.addItem(spacerItem15, 2, 4, 1, 1)
        self.customExpYConfGrid.setColumnStretch(0, 1)
        self.customExpYConfGrid.setColumnStretch(1, 1)
        self.customExpYConfGrid.setColumnStretch(2, 1)
        self.customExpYConfGrid.setColumnStretch(3, 1)
        self.customExpYConfGrid.setColumnStretch(4, 1)
        self.custExpYVert.addLayout(self.customExpYConfGrid)
        self.customExpYWFGrid = QtGui.QGridLayout()
        self.customExpYWFGrid.setObjectName(_fromUtf8("customExpYWFGrid"))
        self.customExpYAmplNumDbl = QtGui.QDoubleSpinBox(self.customExpYPage)
        self.customExpYAmplNumDbl.setObjectName(_fromUtf8("customExpYAmplNumDbl"))
        self.customExpYWFGrid.addWidget(self.customExpYAmplNumDbl, 1, 2, 1, 1)
        self.customExpYWFLab = QtGui.QLabel(self.customExpYPage)
        self.customExpYWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYWFLab.setObjectName(_fromUtf8("customExpYWFLab"))
        self.customExpYWFGrid.addWidget(self.customExpYWFLab, 0, 0, 1, 1)
        self.customExpYFreqLab = QtGui.QLabel(self.customExpYPage)
        self.customExpYFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYFreqLab.setObjectName(_fromUtf8("customExpYFreqLab"))
        self.customExpYWFGrid.addWidget(self.customExpYFreqLab, 0, 1, 1, 1)
        self.customExpYAmplLab = QtGui.QLabel(self.customExpYPage)
        self.customExpYAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYAmplLab.setObjectName(_fromUtf8("customExpYAmplLab"))
        self.customExpYWFGrid.addWidget(self.customExpYAmplLab, 0, 2, 1, 1)
        self.customExpYFreqNumDbl = QtGui.QDoubleSpinBox(self.customExpYPage)
        self.customExpYFreqNumDbl.setObjectName(_fromUtf8("customExpYFreqNumDbl"))
        self.customExpYWFGrid.addWidget(self.customExpYFreqNumDbl, 1, 1, 1, 1)
        self.customExpYWFCmb = QtGui.QComboBox(self.customExpYPage)
        self.customExpYWFCmb.setObjectName(_fromUtf8("customExpYWFCmb"))
        self.customExpYWFGrid.addWidget(self.customExpYWFCmb, 1, 0, 1, 1)
        self.customExpYEqForceVsMaxLine = QtGui.QLineEdit(self.customExpYPage)
        self.customExpYEqForceVsMaxLine.setReadOnly(True)
        self.customExpYEqForceVsMaxLine.setObjectName(_fromUtf8("customExpYEqForceVsMaxLine"))
        self.customExpYWFGrid.addWidget(self.customExpYEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpYEqForceVsMaxLab = QtGui.QLabel(self.customExpYPage)
        self.customExpYEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYEqForceVsMaxLab.setObjectName(_fromUtf8("customExpYEqForceVsMaxLab"))
        self.customExpYWFGrid.addWidget(self.customExpYEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpYWFGrid.setColumnStretch(0, 2)
        self.customExpYWFGrid.setColumnStretch(1, 1)
        self.customExpYWFGrid.setColumnStretch(2, 1)
        self.customExpYWFGrid.setColumnStretch(3, 1)
        self.custExpYVert.addLayout(self.customExpYWFGrid)
        self.custExpYVert.setStretch(0, 1)
        self.custExpYVert.setStretch(1, 1)
        self.customExpAxisTabs.addTab(self.customExpYPage, _fromUtf8(""))
        self.customExpZPage = QtGui.QWidget()
        self.customExpZPage.setObjectName(_fromUtf8("customExpZPage"))
        self.custExpZVert = QtGui.QVBoxLayout(self.customExpZPage)
        self.custExpZVert.setObjectName(_fromUtf8("custExpZVert"))
        self.customExpZConfGrid = QtGui.QGridLayout()
        self.customExpZConfGrid.setObjectName(_fromUtf8("customExpZConfGrid"))
        self.customExpZMultiIntCheck = QtGui.QCheckBox(self.customExpZPage)
        self.customExpZMultiIntCheck.setObjectName(_fromUtf8("customExpZMultiIntCheck"))
        self.customExpZConfGrid.addWidget(self.customExpZMultiIntCheck, 0, 0, 1, 1)
        self.customExpZOnDurNumDbl = QtGui.QDoubleSpinBox(self.customExpZPage)
        self.customExpZOnDurNumDbl.setObjectName(_fromUtf8("customExpZOnDurNumDbl"))
        self.customExpZConfGrid.addWidget(self.customExpZOnDurNumDbl, 2, 1, 1, 1)
        self.customExpZOnDurLab = QtGui.QLabel(self.customExpZPage)
        self.customExpZOnDurLab.setObjectName(_fromUtf8("customExpZOnDurLab"))
        self.customExpZConfGrid.addWidget(self.customExpZOnDurLab, 2, 0, 1, 1)
        self.customExpZStartOnCheck = QtGui.QCheckBox(self.customExpZPage)
        self.customExpZStartOnCheck.setObjectName(_fromUtf8("customExpZStartOnCheck"))
        self.customExpZConfGrid.addWidget(self.customExpZStartOnCheck, 4, 0, 1, 1)
        self.customExpZOffDurLab = QtGui.QLabel(self.customExpZPage)
        self.customExpZOffDurLab.setObjectName(_fromUtf8("customExpZOffDurLab"))
        self.customExpZConfGrid.addWidget(self.customExpZOffDurLab, 3, 0, 1, 1)
        self.customExpZNumIntLab = QtGui.QLabel(self.customExpZPage)
        self.customExpZNumIntLab.setObjectName(_fromUtf8("customExpZNumIntLab"))
        self.customExpZConfGrid.addWidget(self.customExpZNumIntLab, 1, 0, 1, 1)
        self.customExpZOffDurNumDbl = QtGui.QDoubleSpinBox(self.customExpZPage)
        self.customExpZOffDurNumDbl.setObjectName(_fromUtf8("customExpZOffDurNumDbl"))
        self.customExpZConfGrid.addWidget(self.customExpZOffDurNumDbl, 3, 1, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpZConfGrid.addItem(spacerItem16, 2, 2, 1, 1)
        self.customExpZNumIntNum = QtGui.QSpinBox(self.customExpZPage)
        self.customExpZNumIntNum.setObjectName(_fromUtf8("customExpZNumIntNum"))
        self.customExpZConfGrid.addWidget(self.customExpZNumIntNum, 1, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpZConfGrid.addItem(spacerItem17, 2, 3, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.customExpZConfGrid.addItem(spacerItem18, 2, 4, 1, 1)
        self.customExpZConfGrid.setColumnStretch(0, 1)
        self.customExpZConfGrid.setColumnStretch(1, 1)
        self.customExpZConfGrid.setColumnStretch(2, 1)
        self.customExpZConfGrid.setColumnStretch(3, 1)
        self.customExpZConfGrid.setColumnStretch(4, 1)
        self.custExpZVert.addLayout(self.customExpZConfGrid)
        self.customExpZWFGrid = QtGui.QGridLayout()
        self.customExpZWFGrid.setObjectName(_fromUtf8("customExpZWFGrid"))
        self.customExpZAmplNumDbl = QtGui.QDoubleSpinBox(self.customExpZPage)
        self.customExpZAmplNumDbl.setObjectName(_fromUtf8("customExpZAmplNumDbl"))
        self.customExpZWFGrid.addWidget(self.customExpZAmplNumDbl, 1, 2, 1, 1)
        self.customExpZWFLab = QtGui.QLabel(self.customExpZPage)
        self.customExpZWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZWFLab.setObjectName(_fromUtf8("customExpZWFLab"))
        self.customExpZWFGrid.addWidget(self.customExpZWFLab, 0, 0, 1, 1)
        self.customExpZFreqLab = QtGui.QLabel(self.customExpZPage)
        self.customExpZFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZFreqLab.setObjectName(_fromUtf8("customExpZFreqLab"))
        self.customExpZWFGrid.addWidget(self.customExpZFreqLab, 0, 1, 1, 1)
        self.customExpZAmplLab = QtGui.QLabel(self.customExpZPage)
        self.customExpZAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZAmplLab.setObjectName(_fromUtf8("customExpZAmplLab"))
        self.customExpZWFGrid.addWidget(self.customExpZAmplLab, 0, 2, 1, 1)
        self.customExpZFreqNumDbl = QtGui.QDoubleSpinBox(self.customExpZPage)
        self.customExpZFreqNumDbl.setObjectName(_fromUtf8("customExpZFreqNumDbl"))
        self.customExpZWFGrid.addWidget(self.customExpZFreqNumDbl, 1, 1, 1, 1)
        self.customExpZWFCmb = QtGui.QComboBox(self.customExpZPage)
        self.customExpZWFCmb.setObjectName(_fromUtf8("customExpZWFCmb"))
        self.customExpZWFGrid.addWidget(self.customExpZWFCmb, 1, 0, 1, 1)
        self.customExpZEqForceVsMaxLine = QtGui.QLineEdit(self.customExpZPage)
        self.customExpZEqForceVsMaxLine.setReadOnly(True)
        self.customExpZEqForceVsMaxLine.setObjectName(_fromUtf8("customExpZEqForceVsMaxLine"))
        self.customExpZWFGrid.addWidget(self.customExpZEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpZEqForceVsMaxLab = QtGui.QLabel(self.customExpZPage)
        self.customExpZEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZEqForceVsMaxLab.setObjectName(_fromUtf8("customExpZEqForceVsMaxLab"))
        self.customExpZWFGrid.addWidget(self.customExpZEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpZWFGrid.setColumnStretch(0, 2)
        self.customExpZWFGrid.setColumnStretch(1, 1)
        self.customExpZWFGrid.setColumnStretch(2, 1)
        self.customExpZWFGrid.setColumnStretch(3, 1)
        self.custExpZVert.addLayout(self.customExpZWFGrid)
        self.custExpZVert.setStretch(0, 1)
        self.custExpZVert.setStretch(1, 1)
        self.customExpAxisTabs.addTab(self.customExpZPage, _fromUtf8(""))
        self.custExpVert.addWidget(self.customExpAxisTabs)
        self.customExpStartBtn = QtGui.QPushButton(self.custExpPage)
        self.customExpStartBtn.setObjectName(_fromUtf8("customExpStartBtn"))
        self.custExpVert.addWidget(self.customExpStartBtn)
        self.modTabs.addTab(self.custExpPage, _fromUtf8(""))
        self.posNmodHor.addWidget(self.modTabs)
        self.sysCtrlVert.addLayout(self.posNmodHor)
        self.sysCtrlVert.setStretch(0, 7)
        self.mainGuiHor.addLayout(self.sysCtrlVert)
        OTsUI_main.setCentralWidget(self.mainGuiWid)
        self.menubar = QtGui.QMenuBar(OTsUI_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1401, 21))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        OTsUI_main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OTsUI_main)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        OTsUI_main.setStatusBar(self.statusbar)
        self.action_Config_File = QtGui.QAction(OTsUI_main)
        self.action_Config_File.setObjectName(_fromUtf8("action_Config_File"))
        self.action_Save_Parameters = QtGui.QAction(OTsUI_main)
        self.action_Save_Parameters.setObjectName(_fromUtf8("action_Save_Parameters"))
        self.action_Load_Parameters = QtGui.QAction(OTsUI_main)
        self.action_Load_Parameters.setObjectName(_fromUtf8("action_Load_Parameters"))
        self.action_Exit = QtGui.QAction(OTsUI_main)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.menu_File.addAction(self.action_Config_File)
        self.menu_File.addAction(self.action_Save_Parameters)
        self.menu_File.addAction(self.action_Load_Parameters)
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(OTsUI_main)
        self.plotTabs.setCurrentIndex(0)
        self.sig2selCmb.setCurrentIndex(1)
        self.sig3selCmb.setCurrentIndex(2)
        self.ps2selCmb.setCurrentIndex(1)
        self.ps3selCmb.setCurrentIndex(2)
        self.fbToolBox.setCurrentIndex(0)
        self.modTabs.setCurrentIndex(2)
        self.calTypeTab.setCurrentIndex(0)
        self.customExpAxisTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OTsUI_main)

    def retranslateUi(self, OTsUI_main):
        OTsUI_main.setWindowTitle(_translate("OTsUI_main", "MainWindow", None))
        self.connBox.setTitle(_translate("OTsUI_main", "Connection", None))
        self.ipAddLab.setText(_translate("OTsUI_main", "IP address", None))
        self.portLab.setText(_translate("OTsUI_main", "PUB Port", None))
        self.portLab_2.setText(_translate("OTsUI_main", "SUB Port", None))
        self.connectBtn.setText(_translate("OTsUI_main", "CONNECT", None))
        self.saveBox.setTitle(_translate("OTsUI_main", "Save settings", None))
        self.dataNameLab.setText(_translate("OTsUI_main", "Experiment name", None))
        self.logNameLab.setText(_translate("OTsUI_main", "Log file name", None))
        self.logDirBtn.setText(_translate("OTsUI_main", "Browse", None))
        self.dataDirBtn.setText(_translate("OTsUI_main", "Browse...", None))
        self.dataDirLab.setText(_translate("OTsUI_main", "Data directory", None))
        self.logDirLab.setText(_translate("OTsUI_main", "Log directory", None))
        self.lockFbBtn.setText(_translate("OTsUI_main", "LOCK FEED-BACK", None))
        self.sig2selCmb.setItemText(0, _translate("OTsUI_main", "X QPD", None))
        self.sig2selCmb.setItemText(1, _translate("OTsUI_main", "Y QPD", None))
        self.sig2selCmb.setItemText(2, _translate("OTsUI_main", "Z QPD", None))
        self.sig2selCmb.setItemText(3, _translate("OTsUI_main", "X Galv", None))
        self.sig2selCmb.setItemText(4, _translate("OTsUI_main", "Y Galv", None))
        self.sig2selCmb.setItemText(5, _translate("OTsUI_main", "Z Galv", None))
        self.sig3selCmb.setItemText(0, _translate("OTsUI_main", "X QPD", None))
        self.sig3selCmb.setItemText(1, _translate("OTsUI_main", "Y QPD", None))
        self.sig3selCmb.setItemText(2, _translate("OTsUI_main", "Z QPD", None))
        self.sig3selCmb.setItemText(3, _translate("OTsUI_main", "X Galv", None))
        self.sig3selCmb.setItemText(4, _translate("OTsUI_main", "Y Galv", None))
        self.sig3selCmb.setItemText(5, _translate("OTsUI_main", "Z Galv", None))
        self.sig1selCmb.setItemText(0, _translate("OTsUI_main", "X QPD", None))
        self.sig1selCmb.setItemText(1, _translate("OTsUI_main", "Y QPD", None))
        self.sig1selCmb.setItemText(2, _translate("OTsUI_main", "Z QPD", None))
        self.sig1selCmb.setItemText(3, _translate("OTsUI_main", "X Galv", None))
        self.sig1selCmb.setItemText(4, _translate("OTsUI_main", "Y Galv", None))
        self.sig1selCmb.setItemText(5, _translate("OTsUI_main", "Z Galv", None))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.signalPage), _translate("OTsUI_main", "Signals", None))
        self.ps1selCmb.setItemText(0, _translate("OTsUI_main", "X QPD", None))
        self.ps1selCmb.setItemText(1, _translate("OTsUI_main", "Y QPD", None))
        self.ps1selCmb.setItemText(2, _translate("OTsUI_main", "Z QPD", None))
        self.ps1selCmb.setItemText(3, _translate("OTsUI_main", "X Galv", None))
        self.ps1selCmb.setItemText(4, _translate("OTsUI_main", "Y Galv", None))
        self.ps1selCmb.setItemText(5, _translate("OTsUI_main", "Z Galv", None))
        self.ps2selCmb.setItemText(0, _translate("OTsUI_main", "X QPD", None))
        self.ps2selCmb.setItemText(1, _translate("OTsUI_main", "Y QPD", None))
        self.ps2selCmb.setItemText(2, _translate("OTsUI_main", "Z QPD", None))
        self.ps2selCmb.setItemText(3, _translate("OTsUI_main", "X Galv", None))
        self.ps2selCmb.setItemText(4, _translate("OTsUI_main", "Y Galv", None))
        self.ps2selCmb.setItemText(5, _translate("OTsUI_main", "Z Galv", None))
        self.ps3selCmb.setItemText(0, _translate("OTsUI_main", "X QPD", None))
        self.ps3selCmb.setItemText(1, _translate("OTsUI_main", "Y QPD", None))
        self.ps3selCmb.setItemText(2, _translate("OTsUI_main", "Z QPD", None))
        self.ps3selCmb.setItemText(3, _translate("OTsUI_main", "X Galv", None))
        self.ps3selCmb.setItemText(4, _translate("OTsUI_main", "Y Galv", None))
        self.ps3selCmb.setItemText(5, _translate("OTsUI_main", "Z Galv", None))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.psPage), _translate("OTsUI_main", "Power spectrums", None))
        self.zPLab.setText(_translate("OTsUI_main", "P", None))
        self.yOptPLab.setText(_translate("OTsUI_main", "P", None))
        self.yOptILab.setText(_translate("OTsUI_main", "I", None))
        self.zLab.setText(_translate("OTsUI_main", "Z", None))
        self.xyPLab.setText(_translate("OTsUI_main", "P", None))
        self.xyILab.setText(_translate("OTsUI_main", "I", None))
        self.zFbOnCheck.setText(_translate("OTsUI_main", "FB ON", None))
        self.zILab.setText(_translate("OTsUI_main", "I", None))
        self.setFbBtn.setText(_translate("OTsUI_main", "SET PI PARAMETERS", None))
        self.u.setText(_translate("OTsUI_main", "Y", None))
        self.xyFbOnCheck.setText(_translate("OTsUI_main", "FB ON", None))
        self.xyLab.setText(_translate("OTsUI_main", "X-Y", None))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.piPage), _translate("OTsUI_main", "PI controller parameters", None))
        self.yPlusTrapBtn.setText(_translate("OTsUI_main", "▲", None))
        self.xMinusTrapBtn.setText(_translate("OTsUI_main", "◄", None))
        self.xPlusTrapBtn.setText(_translate("OTsUI_main", "►", None))
        self.yMinusTrapBtn.setText(_translate("OTsUI_main", "▼", None))
        self.zPlusTrapBtn.setText(_translate("OTsUI_main", "▲", None))
        self.zMinusTrapBtn.setText(_translate("OTsUI_main", "▼", None))
        self.goHomeBtn.setText(_translate("OTsUI_main", "⌂ HOME", None))
        self.xStepLab_3.setText(_translate("OTsUI_main", "Z", None))
        self.xStepLab.setText(_translate("OTsUI_main", "X", None))
        self.xStepLab_2.setText(_translate("OTsUI_main", "Y", None))
        self.stepLab.setText(_translate("OTsUI_main", "Step ampl [nm]", None))
        self.currPosLab.setText(_translate("OTsUI_main", "Curr. pos. [nm]", None))
        self.setHomeBtn.setText(_translate("OTsUI_main", "Set Home", None))
        self.ySpeedTrapPadLab.setText(_translate("OTsUI_main", "Y speed [nm/s]", None))
        self.zSpeedTrapPadLab.setText(_translate("OTsUI_main", "Z speed [nm/s]", None))
        self.xSpeedTrapPadLab.setText(_translate("OTsUI_main", "X speed [nm/s]", None))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.padPage), _translate("OTsUI_main", "Optical trap control pad", None))
        self.yOffSetLab.setText(_translate("OTsUI_main", "Y offset", None))
        self.zOffSetLab.setText(_translate("OTsUI_main", "Z offset", None))
        self.xOffSetLab.setText(_translate("OTsUI_main", "X offset", None))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.otherPage), _translate("OTsUI_main", "Other parameters", None))
        self.passiveCalDurLab.setText(_translate("OTsUI_main", "Duration [s]", None))
        self.passiveCalMaxFreqLab.setText(_translate("OTsUI_main", "Max. frequency [Hz]", None))
        self.passiveCalAvgLav.setText(_translate("OTsUI_main", "Averages", None))
        self.passiveCalStartBtn.setText(_translate("OTsUI_main", "START", None))
        self.calTypeTab.setTabText(self.calTypeTab.indexOf(self.calPassivePage), _translate("OTsUI_main", "Passive", None))
        self.activeCalYLab.setText(_translate("OTsUI_main", "Y", None))
        self.activeCalZLab.setText(_translate("OTsUI_main", "Z", None))
        self.activeCalAmpLab.setText(_translate("OTsUI_main", "Ampl [nm]", None))
        self.activeCalXLab.setText(_translate("OTsUI_main", "X", None))
        self.activeCalFreqLab.setText(_translate("OTsUI_main", "Freq [Hz]", None))
        self.activeCalDurLab.setText(_translate("OTsUI_main", "Duration [s]", None))
        self.activeCalMaxFreqLab.setText(_translate("OTsUI_main", "Max freq [Hz]", None))
        self.activeCalAvgLab.setText(_translate("OTsUI_main", "Averages", None))
        self.activeCalStartBtn.setText(_translate("OTsUI_main", "START", None))
        self.calTypeTab.setTabText(self.calTypeTab.indexOf(self.calActivePage), _translate("OTsUI_main", "Active", None))
        self.genParBox.setTitle(_translate("OTsUI_main", "General Params", None))
        self.dynViscLab.setText(_translate("OTsUI_main", "Dyn. Visc.", None))
        self.radiusLab.setText(_translate("OTsUI_main", "Radius [um]", None))
        self.calResultsBox.setTitle(_translate("OTsUI_main", "Results", None))
        self.kxLab.setText(_translate("OTsUI_main", "kx", None))
        self.kyLab.setText(_translate("OTsUI_main", "ky", None))
        self.kzLab.setText(_translate("OTsUI_main", "kz", None))
        self.SxLab.setText(_translate("OTsUI_main", "Sx", None))
        self.SyLab.setText(_translate("OTsUI_main", "Sy", None))
        self.SzLab.setText(_translate("OTsUI_main", "Sz", None))
        self.modTabs.setTabText(self.modTabs.indexOf(self.calibPage), _translate("OTsUI_main", "Calibration", None))
        self.stdExpXLab.setText(_translate("OTsUI_main", "X", None))
        self.stdExpSetPointLab.setText(_translate("OTsUI_main", "Set point [nm]", None))
        self.stdExpAxisLab.setText(_translate("OTsUI_main", "Axis", None))
        self.stdExpZLab.setText(_translate("OTsUI_main", "Z", None))
        self.stdExpEqForceVsMaxLab.setText(_translate("OTsUI_main", "S.P. Force [pN]/Max force[pN]", None))
        self.stdExpYLab.setText(_translate("OTsUI_main", "Y", None))
        self.stdExpDurLab.setText(_translate("OTsUI_main", "Duration [s]", None))
        self.fbSchedBox.setTitle(_translate("OTsUI_main", "Feed Back time scheduler", None))
        self.fbSchedNumIntLab.setText(_translate("OTsUI_main", "Number of intervals", None))
        self.fbSchedOnDurLab.setText(_translate("OTsUI_main", "On part dur. [s]", None))
        self.fbSchedOffDurLab.setText(_translate("OTsUI_main", "Off part dur. [s]", None))
        self.fbSchedStartOnCheck.setText(_translate("OTsUI_main", "Start On", None))
        self.stdExpStartBtn.setText(_translate("OTsUI_main", "START", None))
        self.modTabs.setTabText(self.modTabs.indexOf(self.stdExpPage), _translate("OTsUI_main", "Standard experiment", None))
        self.customExpXMultiIntCheck.setText(_translate("OTsUI_main", "Multi interval", None))
        self.customExpXNumIntLab.setText(_translate("OTsUI_main", "Number of intervals", None))
        self.customExpXOnDurLab.setText(_translate("OTsUI_main", "On part duration [s]", None))
        self.customExpXOffDurLab.setText(_translate("OTsUI_main", "Off part duration [s]", None))
        self.customExpXStartOnCheck.setText(_translate("OTsUI_main", "Start On", None))
        self.customExpXWFLab.setText(_translate("OTsUI_main", "Waveform type", None))
        self.customExpXFreqLab.setText(_translate("OTsUI_main", "Frequency [Hz]", None))
        self.customExpXAmplLab.setText(_translate("OTsUI_main", "Amplitude [nm]", None))
        self.customExpXEqForceVsMaxLab.setText(_translate("OTsUI_main", "Force ampl. [pN]/Max. force [pN]", None))
        self.customExpAxisTabs.setTabText(self.customExpAxisTabs.indexOf(self.customExpXPage), _translate("OTsUI_main", "X", None))
        self.customExpYStartOnCheck.setText(_translate("OTsUI_main", "Start On", None))
        self.customExpYNumIntLab.setText(_translate("OTsUI_main", "Number of intervals", None))
        self.customExpYOffDurLab.setText(_translate("OTsUI_main", "Off part duration [s]", None))
        self.customExpYOnDurLab.setText(_translate("OTsUI_main", "On part duration [s]", None))
        self.customExpYMultiIntCheck.setText(_translate("OTsUI_main", "Multi interval", None))
        self.customExpYWFLab.setText(_translate("OTsUI_main", "Waveform type", None))
        self.customExpYFreqLab.setText(_translate("OTsUI_main", "Frequency [Hz]", None))
        self.customExpYAmplLab.setText(_translate("OTsUI_main", "Amplitude [nm]", None))
        self.customExpYEqForceVsMaxLab.setText(_translate("OTsUI_main", "Force ampl. [pN]/Max. force [pN]", None))
        self.customExpAxisTabs.setTabText(self.customExpAxisTabs.indexOf(self.customExpYPage), _translate("OTsUI_main", "Y", None))
        self.customExpZMultiIntCheck.setText(_translate("OTsUI_main", "Multi interval", None))
        self.customExpZOnDurLab.setText(_translate("OTsUI_main", "On part duration [s]", None))
        self.customExpZStartOnCheck.setText(_translate("OTsUI_main", "Start On", None))
        self.customExpZOffDurLab.setText(_translate("OTsUI_main", "Off part duration [s]", None))
        self.customExpZNumIntLab.setText(_translate("OTsUI_main", "Number of intervals", None))
        self.customExpZWFLab.setText(_translate("OTsUI_main", "Waveform type", None))
        self.customExpZFreqLab.setText(_translate("OTsUI_main", "Frequency [Hz]", None))
        self.customExpZAmplLab.setText(_translate("OTsUI_main", "Amplitude [nm]", None))
        self.customExpZEqForceVsMaxLab.setText(_translate("OTsUI_main", "Force ampl. [pN]/Max. force [pN]", None))
        self.customExpAxisTabs.setTabText(self.customExpAxisTabs.indexOf(self.customExpZPage), _translate("OTsUI_main", "Z", None))
        self.customExpStartBtn.setText(_translate("OTsUI_main", "START", None))
        self.modTabs.setTabText(self.modTabs.indexOf(self.custExpPage), _translate("OTsUI_main", "Custom experiment", None))
        self.menu_File.setTitle(_translate("OTsUI_main", "&File", None))
        self.action_Config_File.setText(_translate("OTsUI_main", "&Config File", None))
        self.action_Save_Parameters.setText(_translate("OTsUI_main", "&Save Parameters", None))
        self.action_Save_Parameters.setShortcut(_translate("OTsUI_main", "Ctrl+S", None))
        self.action_Load_Parameters.setText(_translate("OTsUI_main", "&Load Parameters", None))
        self.action_Load_Parameters.setShortcut(_translate("OTsUI_main", "Ctrl+L", None))
        self.action_Exit.setText(_translate("OTsUI_main", "&Exit", None))
        self.action_Exit.setShortcut(_translate("OTsUI_main", "Ctrl+Shift+E", None))

from pyqtgraph import PlotWidget
