# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OTsUI_main.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

#class Ui_MainWindow(object):
class OTsUI_main(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 848)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.mainGuiHor = QtWidgets.QWidget(MainWindow)
        self.mainGuiHor.setObjectName("mainGuiHor")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainGuiHor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.conSavLogFrame = QtWidgets.QFrame(self.mainGuiHor)
        self.conSavLogFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.conSavLogFrame.setMaximumSize(QtCore.QSize(251, 16777215))
        self.conSavLogFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conSavLogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conSavLogFrame.setObjectName("conSavLogFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.conSavLogFrame)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.connBox = QtWidgets.QGroupBox(self.conSavLogFrame)
        self.connBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.connBox.setObjectName("connBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.connBox)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.connForm = QtWidgets.QFormLayout()
        self.connForm.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.connForm.setObjectName("connForm")
        self.ipAddLine = QtWidgets.QLineEdit(self.connBox)
        self.ipAddLine.setObjectName("ipAddLine")
        self.connForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ipAddLine)
        self.ipAddLab = QtWidgets.QLabel(self.connBox)
        self.ipAddLab.setObjectName("ipAddLab")
        self.connForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ipAddLab)
        self.portLine = QtWidgets.QLineEdit(self.connBox)
        self.portLine.setObjectName("portLine")
        self.connForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portLine)
        self.portLab = QtWidgets.QLabel(self.connBox)
        self.portLab.setObjectName("portLab")
        self.connForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portLab)
        self.verticalLayout_7.addLayout(self.connForm)
        self.connectBtn = QtWidgets.QPushButton(self.connBox)
        self.connectBtn.setObjectName("connectBtn")
        self.verticalLayout_7.addWidget(self.connectBtn)
        self.verticalLayout_9.addWidget(self.connBox)
        self.saveBox = QtWidgets.QGroupBox(self.conSavLogFrame)
        self.saveBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.saveBox.setObjectName("saveBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.saveBox)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.saveGrid = QtWidgets.QGridLayout()
        self.saveGrid.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.saveGrid.setObjectName("saveGrid")
        self.dataDirLab = QtWidgets.QLabel(self.saveBox)
        self.dataDirLab.setObjectName("dataDirLab")
        self.saveGrid.addWidget(self.dataDirLab, 0, 0, 1, 1)
        self.dataDirLine = QtWidgets.QLineEdit(self.saveBox)
        self.dataDirLine.setObjectName("dataDirLine")
        self.saveGrid.addWidget(self.dataDirLine, 0, 1, 1, 1)
        self.dataDirBtn = QtWidgets.QPushButton(self.saveBox)
        self.dataDirBtn.setObjectName("dataDirBtn")
        self.saveGrid.addWidget(self.dataDirBtn, 1, 1, 1, 1)
        self.logDirLab = QtWidgets.QLabel(self.saveBox)
        self.logDirLab.setObjectName("logDirLab")
        self.saveGrid.addWidget(self.logDirLab, 2, 0, 1, 1)
        self.logDirLine = QtWidgets.QLineEdit(self.saveBox)
        self.logDirLine.setObjectName("logDirLine")
        self.saveGrid.addWidget(self.logDirLine, 2, 1, 1, 1)
        self.logDirBtn = QtWidgets.QPushButton(self.saveBox)
        self.logDirBtn.setObjectName("logDirBtn")
        self.saveGrid.addWidget(self.logDirBtn, 3, 1, 1, 1)
        self.logNameLab = QtWidgets.QLabel(self.saveBox)
        self.logNameLab.setObjectName("logNameLab")
        self.saveGrid.addWidget(self.logNameLab, 4, 0, 1, 1)
        self.logNameLine = QtWidgets.QLineEdit(self.saveBox)
        self.logNameLine.setObjectName("logNameLine")
        self.saveGrid.addWidget(self.logNameLine, 4, 1, 1, 1)
        self.parDirLab = QtWidgets.QLabel(self.saveBox)
        self.parDirLab.setObjectName("parDirLab")
        self.saveGrid.addWidget(self.parDirLab, 5, 0, 1, 1)
        self.parDirLine = QtWidgets.QLineEdit(self.saveBox)
        self.parDirLine.setObjectName("parDirLine")
        self.saveGrid.addWidget(self.parDirLine, 5, 1, 1, 1)
        self.parDirBtn = QtWidgets.QPushButton(self.saveBox)
        self.parDirBtn.setObjectName("parDirBtn")
        self.saveGrid.addWidget(self.parDirBtn, 6, 1, 1, 1)
        self.parNameLab = QtWidgets.QLabel(self.saveBox)
        self.parNameLab.setObjectName("parNameLab")
        self.saveGrid.addWidget(self.parNameLab, 7, 0, 1, 1)
        self.parNameLine = QtWidgets.QLineEdit(self.saveBox)
        self.parNameLine.setObjectName("parNameLine")
        self.saveGrid.addWidget(self.parNameLine, 7, 1, 1, 1)
        self.parSaveBtn = QtWidgets.QPushButton(self.saveBox)
        self.parSaveBtn.setObjectName("parSaveBtn")
        self.saveGrid.addWidget(self.parSaveBtn, 8, 0, 1, 1)
        self.parLoadBtn = QtWidgets.QPushButton(self.saveBox)
        self.parLoadBtn.setObjectName("parLoadBtn")
        self.saveGrid.addWidget(self.parLoadBtn, 8, 1, 1, 1)
        self.saveGrid.setColumnStretch(0, 1)
        self.saveGrid.setColumnStretch(1, 1)
        self.verticalLayout_8.addLayout(self.saveGrid)
        self.verticalLayout_9.addWidget(self.saveBox)
        self.logText = QtWidgets.QTextEdit(self.conSavLogFrame)
        self.logText.setMaximumSize(QtCore.QSize(300, 16777215))
        self.logText.setObjectName("logText")
        self.verticalLayout_9.addWidget(self.logText)
        self.lockFbBtn = QtWidgets.QPushButton(self.conSavLogFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lockFbBtn.sizePolicy().hasHeightForWidth())
        self.lockFbBtn.setSizePolicy(sizePolicy)
        self.lockFbBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.lockFbBtn.setObjectName("lockFbBtn")
        self.verticalLayout_9.addWidget(self.lockFbBtn)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 3)
        self.verticalLayout_9.setStretch(2, 6)
        self.horizontalLayout.addWidget(self.conSavLogFrame)
        self.sysCtrlVert = QtWidgets.QVBoxLayout()
        self.sysCtrlVert.setObjectName("sysCtrlVert")
        self.plotNfbHor = QtWidgets.QHBoxLayout()
        self.plotNfbHor.setObjectName("plotNfbHor")
        self.plotTabs = QtWidgets.QTabWidget(self.mainGuiHor)
        self.plotTabs.setObjectName("plotTabs")
        self.signalTab = QtWidgets.QWidget()
        self.signalTab.setObjectName("signalTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.signalTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sig3selCmb = QtWidgets.QComboBox(self.signalTab)
        self.sig3selCmb.setObjectName("sig3selCmb")
        self.sig3selCmb.addItem("")
        self.sig3selCmb.addItem("")
        self.sig3selCmb.addItem("")
        self.gridLayout_3.addWidget(self.sig3selCmb, 3, 3, 1, 1)
        self.sig2selCmb = QtWidgets.QComboBox(self.signalTab)
        self.sig2selCmb.setObjectName("sig2selCmb")
        self.sig2selCmb.addItem("")
        self.sig2selCmb.addItem("")
        self.sig2selCmb.addItem("")
        self.gridLayout_3.addWidget(self.sig2selCmb, 3, 0, 1, 1)
        self.scaleSig1Btn = QtWidgets.QPushButton(self.signalTab)
        self.scaleSig1Btn.setObjectName("scaleSig1Btn")
        self.gridLayout_3.addWidget(self.scaleSig1Btn, 1, 3, 1, 1)
        self.autoScaleSig1Check = QtWidgets.QCheckBox(self.signalTab)
        self.autoScaleSig1Check.setObjectName("autoScaleSig1Check")
        self.gridLayout_3.addWidget(self.autoScaleSig1Check, 1, 4, 1, 1)
        self.scaleSig3Btn = QtWidgets.QPushButton(self.signalTab)
        self.scaleSig3Btn.setObjectName("scaleSig3Btn")
        self.gridLayout_3.addWidget(self.scaleSig3Btn, 3, 4, 1, 1)
        self.scaleSig2Btn = QtWidgets.QPushButton(self.signalTab)
        self.scaleSig2Btn.setObjectName("scaleSig2Btn")
        self.gridLayout_3.addWidget(self.scaleSig2Btn, 3, 1, 1, 1)
        self.autoScaleSig2Check = QtWidgets.QCheckBox(self.signalTab)
        self.autoScaleSig2Check.setObjectName("autoScaleSig2Check")
        self.gridLayout_3.addWidget(self.autoScaleSig2Check, 3, 2, 1, 1)
        self.autScaleSig3Check = QtWidgets.QCheckBox(self.signalTab)
        self.autScaleSig3Check.setObjectName("autScaleSig3Check")
        self.gridLayout_3.addWidget(self.autScaleSig3Check, 3, 5, 1, 1)
        self.sig1Plot = QtWidgets.QGraphicsView(self.signalTab)
        self.sig1Plot.setObjectName("sig1Plot")
        self.gridLayout_3.addWidget(self.sig1Plot, 0, 0, 1, 6)
        self.sig2Plot = QtWidgets.QGraphicsView(self.signalTab)
        self.sig2Plot.setObjectName("sig2Plot")
        self.gridLayout_3.addWidget(self.sig2Plot, 2, 0, 1, 3)
        self.sig3Plot = QtWidgets.QGraphicsView(self.signalTab)
        self.sig3Plot.setObjectName("sig3Plot")
        self.gridLayout_3.addWidget(self.sig3Plot, 2, 3, 1, 3)
        self.sig1selCmb = QtWidgets.QComboBox(self.signalTab)
        self.sig1selCmb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sig1selCmb.setObjectName("sig1selCmb")
        self.sig1selCmb.addItem("")
        self.sig1selCmb.addItem("")
        self.sig1selCmb.addItem("")
        self.gridLayout_3.addWidget(self.sig1selCmb, 1, 0, 1, 3)
        self.gridLayout_3.setRowStretch(0, 3)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 2)
        self.gridLayout_3.setRowStretch(3, 1)
        self.plotTabs.addTab(self.signalTab, "")
        self.psTab = QtWidgets.QWidget()
        self.psTab.setObjectName("psTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.psTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.autoScalePs2Check = QtWidgets.QCheckBox(self.psTab)
        self.autoScalePs2Check.setObjectName("autoScalePs2Check")
        self.gridLayout_4.addWidget(self.autoScalePs2Check, 3, 2, 1, 1)
        self.ps2selCmb = QtWidgets.QComboBox(self.psTab)
        self.ps2selCmb.setObjectName("ps2selCmb")
        self.ps2selCmb.addItem("")
        self.ps2selCmb.addItem("")
        self.ps2selCmb.addItem("")
        self.gridLayout_4.addWidget(self.ps2selCmb, 3, 0, 1, 1)
        self.scalePs3Btn = QtWidgets.QPushButton(self.psTab)
        self.scalePs3Btn.setObjectName("scalePs3Btn")
        self.gridLayout_4.addWidget(self.scalePs3Btn, 3, 4, 1, 1)
        self.scalePs1Btn = QtWidgets.QPushButton(self.psTab)
        self.scalePs1Btn.setObjectName("scalePs1Btn")
        self.gridLayout_4.addWidget(self.scalePs1Btn, 1, 3, 1, 1)
        self.ps2selCmb_2 = QtWidgets.QComboBox(self.psTab)
        self.ps2selCmb_2.setObjectName("ps2selCmb_2")
        self.ps2selCmb_2.addItem("")
        self.ps2selCmb_2.addItem("")
        self.ps2selCmb_2.addItem("")
        self.gridLayout_4.addWidget(self.ps2selCmb_2, 3, 3, 1, 1)
        self.autoScalePs1Check = QtWidgets.QCheckBox(self.psTab)
        self.autoScalePs1Check.setObjectName("autoScalePs1Check")
        self.gridLayout_4.addWidget(self.autoScalePs1Check, 1, 4, 1, 1)
        self.scalePs2Btn = QtWidgets.QPushButton(self.psTab)
        self.scalePs2Btn.setObjectName("scalePs2Btn")
        self.gridLayout_4.addWidget(self.scalePs2Btn, 3, 1, 1, 1)
        self.autoScalePs3Check = QtWidgets.QCheckBox(self.psTab)
        self.autoScalePs3Check.setObjectName("autoScalePs3Check")
        self.gridLayout_4.addWidget(self.autoScalePs3Check, 3, 5, 1, 1)
        self.powSpec1Plot = QtWidgets.QGraphicsView(self.psTab)
        self.powSpec1Plot.setObjectName("powSpec1Plot")
        self.gridLayout_4.addWidget(self.powSpec1Plot, 0, 0, 1, 6)
        self.powSpec2Plot = QtWidgets.QGraphicsView(self.psTab)
        self.powSpec2Plot.setObjectName("powSpec2Plot")
        self.gridLayout_4.addWidget(self.powSpec2Plot, 2, 0, 1, 3)
        self.powSpec3Plot = QtWidgets.QGraphicsView(self.psTab)
        self.powSpec3Plot.setObjectName("powSpec3Plot")
        self.gridLayout_4.addWidget(self.powSpec3Plot, 2, 3, 1, 3)
        self.ps1selCmb = QtWidgets.QComboBox(self.psTab)
        self.ps1selCmb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ps1selCmb.setObjectName("ps1selCmb")
        self.ps1selCmb.addItem("")
        self.ps1selCmb.addItem("")
        self.ps1selCmb.addItem("")
        self.gridLayout_4.addWidget(self.ps1selCmb, 1, 0, 1, 3)
        self.gridLayout_4.setRowStretch(0, 3)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(2, 2)
        self.gridLayout_4.setRowStretch(3, 1)
        self.plotTabs.addTab(self.psTab, "")
        self.plotNfbHor.addWidget(self.plotTabs)
        self.fbFrame = QtWidgets.QFrame(self.mainGuiHor)
        self.fbFrame.setMinimumSize(QtCore.QSize(150, 0))
        self.fbFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fbFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fbFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fbFrame.setObjectName("fbFrame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.fbFrame)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fbToolBox = QtWidgets.QToolBox(self.fbFrame)
        self.fbToolBox.setMinimumSize(QtCore.QSize(150, 0))
        self.fbToolBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fbToolBox.setObjectName("fbToolBox")
        self.piPage = QtWidgets.QWidget()
        self.piPage.setGeometry(QtCore.QRect(0, 0, 180, 394))
        self.piPage.setObjectName("piPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.piPage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.zPLab = QtWidgets.QLabel(self.piPage)
        self.zPLab.setObjectName("zPLab")
        self.gridLayout_6.addWidget(self.zPLab, 6, 0, 1, 1)
        self.zILab = QtWidgets.QLabel(self.piPage)
        self.zILab.setObjectName("zILab")
        self.gridLayout_6.addWidget(self.zILab, 7, 0, 1, 1)
        self.zPNumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.zPNumDbl.setObjectName("zPNumDbl")
        self.gridLayout_6.addWidget(self.zPNumDbl, 6, 2, 1, 1)
        self.zPDial = QtWidgets.QDial(self.piPage)
        self.zPDial.setObjectName("zPDial")
        self.gridLayout_6.addWidget(self.zPDial, 6, 1, 1, 1)
        self.xyIDial = QtWidgets.QDial(self.piPage)
        self.xyIDial.setObjectName("xyIDial")
        self.gridLayout_6.addWidget(self.xyIDial, 3, 1, 1, 1)
        self.xyPDial = QtWidgets.QDial(self.piPage)
        self.xyPDial.setObjectName("xyPDial")
        self.gridLayout_6.addWidget(self.xyPDial, 1, 1, 1, 1)
        self.xyILab = QtWidgets.QLabel(self.piPage)
        self.xyILab.setObjectName("xyILab")
        self.gridLayout_6.addWidget(self.xyILab, 3, 0, 1, 1)
        self.zINumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.zINumDbl.setObjectName("zINumDbl")
        self.gridLayout_6.addWidget(self.zINumDbl, 7, 2, 1, 1)
        self.xyPLab = QtWidgets.QLabel(self.piPage)
        self.xyPLab.setObjectName("xyPLab")
        self.gridLayout_6.addWidget(self.xyPLab, 1, 0, 1, 1)
        self.xyLab = QtWidgets.QLabel(self.piPage)
        self.xyLab.setObjectName("xyLab")
        self.gridLayout_6.addWidget(self.xyLab, 0, 0, 1, 1)
        self.xyPNumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.xyPNumDbl.setObjectName("xyPNumDbl")
        self.gridLayout_6.addWidget(self.xyPNumDbl, 1, 2, 1, 1)
        self.zIDial = QtWidgets.QDial(self.piPage)
        self.zIDial.setObjectName("zIDial")
        self.gridLayout_6.addWidget(self.zIDial, 7, 1, 1, 1)
        self.xyINumDbl = QtWidgets.QDoubleSpinBox(self.piPage)
        self.xyINumDbl.setObjectName("xyINumDbl")
        self.gridLayout_6.addWidget(self.xyINumDbl, 3, 2, 1, 1)
        self.zLab = QtWidgets.QLabel(self.piPage)
        self.zLab.setObjectName("zLab")
        self.gridLayout_6.addWidget(self.zLab, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.piPage)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 4, 0, 1, 3)
        self.setFbBtn = QtWidgets.QPushButton(self.piPage)
        self.setFbBtn.setObjectName("setFbBtn")
        self.gridLayout_6.addWidget(self.setFbBtn, 8, 0, 1, 3)
        self.xyFbOnCheck = QtWidgets.QCheckBox(self.piPage)
        self.xyFbOnCheck.setObjectName("xyFbOnCheck")
        self.gridLayout_6.addWidget(self.xyFbOnCheck, 0, 1, 1, 1)
        self.zFbOnCheck = QtWidgets.QCheckBox(self.piPage)
        self.zFbOnCheck.setObjectName("zFbOnCheck")
        self.gridLayout_6.addWidget(self.zFbOnCheck, 5, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.fbToolBox.addItem(self.piPage, "")
        self.padPage = QtWidgets.QWidget()
        self.padPage.setGeometry(QtCore.QRect(0, 0, 180, 394))
        self.padPage.setObjectName("padPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.padPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.trapPadPlot = QtWidgets.QGraphicsView(self.padPage)
        self.trapPadPlot.setMaximumSize(QtCore.QSize(180, 180))
        self.trapPadPlot.setObjectName("trapPadPlot")
        self.verticalLayout_6.addWidget(self.trapPadPlot)
        self.trapPadSpeedGrid = QtWidgets.QGridLayout()
        self.trapPadSpeedGrid.setObjectName("trapPadSpeedGrid")
        self.ySpeedTrapPadSlider = QtWidgets.QSlider(self.padPage)
        self.ySpeedTrapPadSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ySpeedTrapPadSlider.setObjectName("ySpeedTrapPadSlider")
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadSlider, 3, 0, 1, 1)
        self.xSpeedTrapPadLab = QtWidgets.QLabel(self.padPage)
        self.xSpeedTrapPadLab.setObjectName("xSpeedTrapPadLab")
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadLab, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem, 5, 0, 1, 1)
        self.ySpeedTrapPadLab = QtWidgets.QLabel(self.padPage)
        self.ySpeedTrapPadLab.setObjectName("ySpeedTrapPadLab")
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadLab, 2, 0, 1, 1)
        self.ySpeedTrapPadNumDbl = QtWidgets.QDoubleSpinBox(self.padPage)
        self.ySpeedTrapPadNumDbl.setObjectName("ySpeedTrapPadNumDbl")
        self.trapPadSpeedGrid.addWidget(self.ySpeedTrapPadNumDbl, 3, 1, 1, 1)
        self.xSpeedTrapPadNumDbl = QtWidgets.QDoubleSpinBox(self.padPage)
        self.xSpeedTrapPadNumDbl.setObjectName("xSpeedTrapPadNumDbl")
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadNumDbl, 1, 1, 1, 1)
        self.xSpeedTrapPadSlider = QtWidgets.QSlider(self.padPage)
        self.xSpeedTrapPadSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xSpeedTrapPadSlider.setObjectName("xSpeedTrapPadSlider")
        self.trapPadSpeedGrid.addWidget(self.xSpeedTrapPadSlider, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.trapPadSpeedGrid.addItem(spacerItem3, 7, 0, 1, 1)
        self.trapPadSpeedGrid.setColumnStretch(0, 2)
        self.trapPadSpeedGrid.setRowStretch(0, 1)
        self.trapPadSpeedGrid.setRowStretch(2, 1)
        self.verticalLayout_6.addLayout(self.trapPadSpeedGrid)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(1, 2)
        self.fbToolBox.addItem(self.padPage, "")
        self.otherPage = QtWidgets.QWidget()
        self.otherPage.setGeometry(QtCore.QRect(0, 0, 180, 394))
        self.otherPage.setObjectName("otherPage")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.otherPage)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.yOffSetNumDbl = QtWidgets.QDoubleSpinBox(self.otherPage)
        self.yOffSetNumDbl.setObjectName("yOffSetNumDbl")
        self.gridLayout_11.addWidget(self.yOffSetNumDbl, 1, 2, 1, 1)
        self.yOffSetDial = QtWidgets.QDial(self.otherPage)
        self.yOffSetDial.setObjectName("yOffSetDial")
        self.gridLayout_11.addWidget(self.yOffSetDial, 1, 1, 1, 1)
        self.xOffSetDial = QtWidgets.QDial(self.otherPage)
        self.xOffSetDial.setObjectName("xOffSetDial")
        self.gridLayout_11.addWidget(self.xOffSetDial, 0, 1, 1, 1)
        self.xOffSetNumDbl = QtWidgets.QDoubleSpinBox(self.otherPage)
        self.xOffSetNumDbl.setObjectName("xOffSetNumDbl")
        self.gridLayout_11.addWidget(self.xOffSetNumDbl, 0, 2, 1, 1)
        self.zOffSetNumDbl = QtWidgets.QDoubleSpinBox(self.otherPage)
        self.zOffSetNumDbl.setObjectName("zOffSetNumDbl")
        self.gridLayout_11.addWidget(self.zOffSetNumDbl, 2, 2, 1, 1)
        self.zOffSetLab = QtWidgets.QLabel(self.otherPage)
        self.zOffSetLab.setObjectName("zOffSetLab")
        self.gridLayout_11.addWidget(self.zOffSetLab, 2, 0, 1, 1)
        self.zOffSetDial = QtWidgets.QDial(self.otherPage)
        self.zOffSetDial.setObjectName("zOffSetDial")
        self.gridLayout_11.addWidget(self.zOffSetDial, 2, 1, 1, 1)
        self.yOffSetLab = QtWidgets.QLabel(self.otherPage)
        self.yOffSetLab.setObjectName("yOffSetLab")
        self.gridLayout_11.addWidget(self.yOffSetLab, 1, 0, 1, 1)
        self.xOffSetLab = QtWidgets.QLabel(self.otherPage)
        self.xOffSetLab.setObjectName("xOffSetLab")
        self.gridLayout_11.addWidget(self.xOffSetLab, 0, 0, 1, 1)
        self.fbToolBox.addItem(self.otherPage, "")
        self.verticalLayout_10.addWidget(self.fbToolBox)
        self.plotNfbHor.addWidget(self.fbFrame)
        self.plotNfbHor.setStretch(1, 2)
        self.sysCtrlVert.addLayout(self.plotNfbHor)
        self.posNmodHor = QtWidgets.QHBoxLayout()
        self.posNmodHor.setObjectName("posNmodHor")
        self.trapPosXYPlot = QtWidgets.QGraphicsView(self.mainGuiHor)
        self.trapPosXYPlot.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trapPosXYPlot.sizePolicy().hasHeightForWidth())
        self.trapPosXYPlot.setSizePolicy(sizePolicy)
        self.trapPosXYPlot.setMaximumSize(QtCore.QSize(370, 370))
        self.trapPosXYPlot.setSizeIncrement(QtCore.QSize(0, 0))
        self.trapPosXYPlot.setObjectName("trapPosXYPlot")
        self.posNmodHor.addWidget(self.trapPosXYPlot)
        self.trapPosZPlot = QtWidgets.QGraphicsView(self.mainGuiHor)
        self.trapPosZPlot.setMaximumSize(QtCore.QSize(71, 370))
        self.trapPosZPlot.setObjectName("trapPosZPlot")
        self.posNmodHor.addWidget(self.trapPosZPlot)
        self.modTabs = QtWidgets.QTabWidget(self.mainGuiHor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modTabs.sizePolicy().hasHeightForWidth())
        self.modTabs.setSizePolicy(sizePolicy)
        self.modTabs.setMaximumSize(QtCore.QSize(16777215, 370))
        self.modTabs.setObjectName("modTabs")
        self.calibTab = QtWidgets.QWidget()
        self.calibTab.setObjectName("calibTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.calibTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calibStack = QtWidgets.QStackedWidget(self.calibTab)
        self.calibStack.setObjectName("calibStack")
        self.passiveCalPage = QtWidgets.QWidget()
        self.passiveCalPage.setObjectName("passiveCalPage")
        self.formLayout = QtWidgets.QFormLayout(self.passiveCalPage)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.passiveCalDurLab = QtWidgets.QLabel(self.passiveCalPage)
        self.passiveCalDurLab.setObjectName("passiveCalDurLab")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passiveCalDurLab)
        self.passiveCalDurNumDbl = QtWidgets.QDoubleSpinBox(self.passiveCalPage)
        self.passiveCalDurNumDbl.setObjectName("passiveCalDurNumDbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passiveCalDurNumDbl)
        self.passiveCalMaxFreqLab = QtWidgets.QLabel(self.passiveCalPage)
        self.passiveCalMaxFreqLab.setObjectName("passiveCalMaxFreqLab")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passiveCalMaxFreqLab)
        self.passiveLab = QtWidgets.QLabel(self.passiveCalPage)
        self.passiveLab.setObjectName("passiveLab")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passiveLab)
        self.passiveCalMaxFreq = QtWidgets.QDoubleSpinBox(self.passiveCalPage)
        self.passiveCalMaxFreq.setObjectName("passiveCalMaxFreq")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passiveCalMaxFreq)
        self.passiveCalAvgLav = QtWidgets.QLabel(self.passiveCalPage)
        self.passiveCalAvgLav.setObjectName("passiveCalAvgLav")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.passiveCalAvgLav)
        self.passiveCalAvgNum = QtWidgets.QSpinBox(self.passiveCalPage)
        self.passiveCalAvgNum.setObjectName("passiveCalAvgNum")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.passiveCalAvgNum)
        self.passiveCalStartBtn = QtWidgets.QPushButton(self.passiveCalPage)
        self.passiveCalStartBtn.setObjectName("passiveCalStartBtn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.passiveCalStartBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.calibStack.addWidget(self.passiveCalPage)
        self.activeCalPage = QtWidgets.QWidget()
        self.activeCalPage.setObjectName("activeCalPage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.activeCalPage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.activeCalSinsConfGrid = QtWidgets.QGridLayout()
        self.activeCalSinsConfGrid.setObjectName("activeCalSinsConfGrid")
        self.activeCalYLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalYLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalYLab.setObjectName("activeCalYLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalYLab, 0, 2, 1, 1)
        self.activeCalZAmplNumDbl = QtWidgets.QSpinBox(self.activeCalPage)
        self.activeCalZAmplNumDbl.setObjectName("activeCalZAmplNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalZAmplNumDbl, 1, 3, 1, 1)
        self.activeCalZLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalZLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalZLab.setObjectName("activeCalZLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalZLab, 0, 3, 1, 1)
        self.activeCalAmpLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalAmpLab.setObjectName("activeCalAmpLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalAmpLab, 1, 0, 1, 1)
        self.activeCalXAmplNumDbl = QtWidgets.QSpinBox(self.activeCalPage)
        self.activeCalXAmplNumDbl.setObjectName("activeCalXAmplNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalXAmplNumDbl, 1, 1, 1, 1)
        self.activeCalLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalLab.setObjectName("activeCalLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalLab, 0, 0, 1, 1)
        self.activeCalYAmplNumDbl = QtWidgets.QSpinBox(self.activeCalPage)
        self.activeCalYAmplNumDbl.setObjectName("activeCalYAmplNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalYAmplNumDbl, 1, 2, 1, 1)
        self.activeCalXLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalXLab.setAlignment(QtCore.Qt.AlignCenter)
        self.activeCalXLab.setObjectName("activeCalXLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalXLab, 0, 1, 1, 1)
        self.activeCalFreqLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalFreqLab.setObjectName("activeCalFreqLab")
        self.activeCalSinsConfGrid.addWidget(self.activeCalFreqLab, 2, 0, 1, 1)
        self.activeCalXFreqNumDbl = QtWidgets.QSpinBox(self.activeCalPage)
        self.activeCalXFreqNumDbl.setObjectName("activeCalXFreqNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalXFreqNumDbl, 2, 1, 1, 1)
        self.activeCalYFreqNumDbl = QtWidgets.QSpinBox(self.activeCalPage)
        self.activeCalYFreqNumDbl.setObjectName("activeCalYFreqNumDbl")
        self.activeCalSinsConfGrid.addWidget(self.activeCalYFreqNumDbl, 2, 2, 1, 1)
        self.activeCalYFreqNumDbl_2 = QtWidgets.QSpinBox(self.activeCalPage)
        self.activeCalYFreqNumDbl_2.setObjectName("activeCalYFreqNumDbl_2")
        self.activeCalSinsConfGrid.addWidget(self.activeCalYFreqNumDbl_2, 2, 3, 1, 1)
        self.activeCalSinsConfGrid.setRowStretch(1, 3)
        self.activeCalSinsConfGrid.setRowStretch(2, 2)
        self.verticalLayout_11.addLayout(self.activeCalSinsConfGrid)
        self.activeConfForm = QtWidgets.QFormLayout()
        self.activeConfForm.setObjectName("activeConfForm")
        self.activeCalDurLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalDurLab.setObjectName("activeCalDurLab")
        self.activeConfForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.activeCalDurLab)
        self.activeCalAvgNum = QtWidgets.QSpinBox(self.activeCalPage)
        self.activeCalAvgNum.setObjectName("activeCalAvgNum")
        self.activeConfForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.activeCalAvgNum)
        self.activeCalMaxFreqLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalMaxFreqLab.setObjectName("activeCalMaxFreqLab")
        self.activeConfForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.activeCalMaxFreqLab)
        self.activeCalAvgLab = QtWidgets.QLabel(self.activeCalPage)
        self.activeCalAvgLab.setObjectName("activeCalAvgLab")
        self.activeConfForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.activeCalAvgLab)
        self.activeCalDurNumDbl = QtWidgets.QDoubleSpinBox(self.activeCalPage)
        self.activeCalDurNumDbl.setObjectName("activeCalDurNumDbl")
        self.activeConfForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.activeCalDurNumDbl)
        self.activeCalMaxFreqNumDbl = QtWidgets.QDoubleSpinBox(self.activeCalPage)
        self.activeCalMaxFreqNumDbl.setObjectName("activeCalMaxFreqNumDbl")
        self.activeConfForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.activeCalMaxFreqNumDbl)
        self.verticalLayout_11.addLayout(self.activeConfForm)
        self.activeCalStartBtn = QtWidgets.QPushButton(self.activeCalPage)
        self.activeCalStartBtn.setObjectName("activeCalStartBtn")
        self.verticalLayout_11.addWidget(self.activeCalStartBtn)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 1)
        self.calibStack.addWidget(self.activeCalPage)
        self.horizontalLayout_2.addWidget(self.calibStack)
        self.genParVert = QtWidgets.QVBoxLayout()
        self.genParVert.setObjectName("genParVert")
        self.genParBox = QtWidgets.QGroupBox(self.calibTab)
        self.genParBox.setObjectName("genParBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.genParBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.radiusNumDbl = QtWidgets.QDoubleSpinBox(self.genParBox)
        self.radiusNumDbl.setObjectName("radiusNumDbl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radiusNumDbl)
        self.dynViscNumDbl = QtWidgets.QDoubleSpinBox(self.genParBox)
        self.dynViscNumDbl.setObjectName("dynViscNumDbl")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dynViscNumDbl)
        self.dynViscLab = QtWidgets.QLabel(self.genParBox)
        self.dynViscLab.setObjectName("dynViscLab")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dynViscLab)
        self.radiusLab = QtWidgets.QLabel(self.genParBox)
        self.radiusLab.setObjectName("radiusLab")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radiusLab)
        self.genParVert.addWidget(self.genParBox)
        self.horizontalLayout_2.addLayout(self.genParVert)
        self.groupBox_5 = QtWidgets.QGroupBox(self.calibTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.kxLab = QtWidgets.QLabel(self.groupBox_5)
        self.kxLab.setObjectName("kxLab")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kxLab)
        self.kxNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.kxNumDbl.setObjectName("kxNumDbl")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kxNumDbl)
        self.kyLab = QtWidgets.QLabel(self.groupBox_5)
        self.kyLab.setObjectName("kyLab")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kyLab)
        self.kyNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.kyNumDbl.setObjectName("kyNumDbl")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kyNumDbl)
        self.kzLab = QtWidgets.QLabel(self.groupBox_5)
        self.kzLab.setObjectName("kzLab")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.kzLab)
        self.kzNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.kzNumDbl.setObjectName("kzNumDbl")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kzNumDbl)
        self.SxNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.SxNumDbl.setObjectName("SxNumDbl")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SxNumDbl)
        self.SyNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.SyNumDbl.setObjectName("SyNumDbl")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SyNumDbl)
        self.SzNumDbl = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.SzNumDbl.setObjectName("SzNumDbl")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.SzNumDbl)
        self.SxLab = QtWidgets.QLabel(self.groupBox_5)
        self.SxLab.setObjectName("SxLab")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.SxLab)
        self.SyLab = QtWidgets.QLabel(self.groupBox_5)
        self.SyLab.setObjectName("SyLab")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.SyLab)
        self.SzLab = QtWidgets.QLabel(self.groupBox_5)
        self.SzLab.setObjectName("SzLab")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.SzLab)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.modTabs.addTab(self.calibTab, "")
        self.stdExpTab = QtWidgets.QWidget()
        self.stdExpTab.setObjectName("stdExpTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.stdExpTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stdExpConfigGrid = QtWidgets.QGridLayout()
        self.stdExpConfigGrid.setObjectName("stdExpConfigGrid")
        self.stdExpXLab = QtWidgets.QLabel(self.stdExpTab)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.stdExpXLab.setFont(font)
        self.stdExpXLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpXLab.setObjectName("stdExpXLab")
        self.stdExpConfigGrid.addWidget(self.stdExpXLab, 1, 0, 1, 1)
        self.stdExpXSetPntNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpTab)
        self.stdExpXSetPntNumDbl.setObjectName("stdExpXSetPntNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpXSetPntNumDbl, 1, 1, 1, 1)
        self.stdExpSetPointLab = QtWidgets.QLabel(self.stdExpTab)
        self.stdExpSetPointLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpSetPointLab.setObjectName("stdExpSetPointLab")
        self.stdExpConfigGrid.addWidget(self.stdExpSetPointLab, 0, 1, 1, 1)
        self.stdExpYEqForceVsMaxLine = QtWidgets.QLineEdit(self.stdExpTab)
        self.stdExpYEqForceVsMaxLine.setObjectName("stdExpYEqForceVsMaxLine")
        self.stdExpConfigGrid.addWidget(self.stdExpYEqForceVsMaxLine, 2, 2, 1, 1)
        self.stdExpAxisLab = QtWidgets.QLabel(self.stdExpTab)
        self.stdExpAxisLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpAxisLab.setObjectName("stdExpAxisLab")
        self.stdExpConfigGrid.addWidget(self.stdExpAxisLab, 0, 0, 1, 1)
        self.stdExpZLab = QtWidgets.QLabel(self.stdExpTab)
        self.stdExpZLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpZLab.setObjectName("stdExpZLab")
        self.stdExpConfigGrid.addWidget(self.stdExpZLab, 3, 0, 1, 1)
        self.stdExpZSetPntNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpTab)
        self.stdExpZSetPntNumDbl.setObjectName("stdExpZSetPntNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpZSetPntNumDbl, 3, 1, 1, 1)
        self.stdExpZEqForceVsMaxLine = QtWidgets.QLineEdit(self.stdExpTab)
        self.stdExpZEqForceVsMaxLine.setObjectName("stdExpZEqForceVsMaxLine")
        self.stdExpConfigGrid.addWidget(self.stdExpZEqForceVsMaxLine, 3, 2, 1, 1)
        self.stdExpXEqForceVsMaxLine = QtWidgets.QLineEdit(self.stdExpTab)
        self.stdExpXEqForceVsMaxLine.setObjectName("stdExpXEqForceVsMaxLine")
        self.stdExpConfigGrid.addWidget(self.stdExpXEqForceVsMaxLine, 1, 2, 1, 1)
        self.stdExpYLab = QtWidgets.QLabel(self.stdExpTab)
        self.stdExpYLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpYLab.setObjectName("stdExpYLab")
        self.stdExpConfigGrid.addWidget(self.stdExpYLab, 2, 0, 1, 1)
        self.stdExpEqForceVsMaxLab = QtWidgets.QLabel(self.stdExpTab)
        self.stdExpEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.stdExpEqForceVsMaxLab.setObjectName("stdExpEqForceVsMaxLab")
        self.stdExpConfigGrid.addWidget(self.stdExpEqForceVsMaxLab, 0, 2, 1, 1)
        self.stdExpYSetPntNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpTab)
        self.stdExpYSetPntNumDbl.setObjectName("stdExpYSetPntNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpYSetPntNumDbl, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.stdExpTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stdExpConfigGrid.addWidget(self.line, 4, 0, 1, 3)
        self.stdExpDurNumDbl = QtWidgets.QDoubleSpinBox(self.stdExpTab)
        self.stdExpDurNumDbl.setObjectName("stdExpDurNumDbl")
        self.stdExpConfigGrid.addWidget(self.stdExpDurNumDbl, 5, 2, 1, 1)
        self.stdExpDurLab = QtWidgets.QLabel(self.stdExpTab)
        self.stdExpDurLab.setObjectName("stdExpDurLab")
        self.stdExpConfigGrid.addWidget(self.stdExpDurLab, 5, 1, 1, 1)
        self.stdExpConfigGrid.setColumnStretch(0, 1)
        self.stdExpConfigGrid.setColumnStretch(1, 2)
        self.stdExpConfigGrid.setColumnStretch(2, 2)
        self.stdExpConfigGrid.setRowStretch(1, 1)
        self.stdExpConfigGrid.setRowStretch(2, 1)
        self.stdExpConfigGrid.setRowStretch(3, 1)
        self.stdExpConfigGrid.setRowStretch(4, 1)
        self.horizontalLayout_6.addLayout(self.stdExpConfigGrid)
        self.fbSchedVert = QtWidgets.QVBoxLayout()
        self.fbSchedVert.setObjectName("fbSchedVert")
        self.fbSchedBox = QtWidgets.QGroupBox(self.stdExpTab)
        self.fbSchedBox.setObjectName("fbSchedBox")
        self.formLayout_12 = QtWidgets.QFormLayout(self.fbSchedBox)
        self.formLayout_12.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName("formLayout_12")
        self.fbSchedNumIntLab = QtWidgets.QLabel(self.fbSchedBox)
        self.fbSchedNumIntLab.setObjectName("fbSchedNumIntLab")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fbSchedNumIntLab)
        self.fbSchedNumIntNumDbl = QtWidgets.QSpinBox(self.fbSchedBox)
        self.fbSchedNumIntNumDbl.setObjectName("fbSchedNumIntNumDbl")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fbSchedNumIntNumDbl)
        self.fbSchedOnDurLab = QtWidgets.QLabel(self.fbSchedBox)
        self.fbSchedOnDurLab.setObjectName("fbSchedOnDurLab")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fbSchedOnDurLab)
        self.fbSchedOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.fbSchedBox)
        self.fbSchedOnDurNumDbl.setObjectName("fbSchedOnDurNumDbl")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fbSchedOnDurNumDbl)
        self.fbSchedOffDurLab = QtWidgets.QLabel(self.fbSchedBox)
        self.fbSchedOffDurLab.setObjectName("fbSchedOffDurLab")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fbSchedOffDurLab)
        self.fbSchedOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.fbSchedBox)
        self.fbSchedOffDurNumDbl.setObjectName("fbSchedOffDurNumDbl")
        self.formLayout_12.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fbSchedOffDurNumDbl)
        self.fbSchedStartOnCheck = QtWidgets.QCheckBox(self.fbSchedBox)
        self.fbSchedStartOnCheck.setTristate(False)
        self.fbSchedStartOnCheck.setObjectName("fbSchedStartOnCheck")
        self.formLayout_12.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fbSchedStartOnCheck)
        self.fbSchedVert.addWidget(self.fbSchedBox)
        self.stdExpStartBtn = QtWidgets.QPushButton(self.stdExpTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stdExpStartBtn.sizePolicy().hasHeightForWidth())
        self.stdExpStartBtn.setSizePolicy(sizePolicy)
        self.stdExpStartBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.stdExpStartBtn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stdExpStartBtn.setObjectName("stdExpStartBtn")
        self.fbSchedVert.addWidget(self.stdExpStartBtn)
        self.fbSchedVert.setStretch(0, 1)
        self.fbSchedVert.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.fbSchedVert)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 2)
        self.modTabs.addTab(self.stdExpTab, "")
        self.custExpTab = QtWidgets.QWidget()
        self.custExpTab.setObjectName("custExpTab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.custExpTab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.customExpAxisStack = QtWidgets.QStackedWidget(self.custExpTab)
        self.customExpAxisStack.setObjectName("customExpAxisStack")
        self.customExpXPage = QtWidgets.QWidget()
        self.customExpXPage.setObjectName("customExpXPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.customExpXPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.customExpXConfGrid = QtWidgets.QGridLayout()
        self.customExpXConfGrid.setObjectName("customExpXConfGrid")
        self.customExpXOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXOnDurNumDbl.setObjectName("customExpXOnDurNumDbl")
        self.customExpXConfGrid.addWidget(self.customExpXOnDurNumDbl, 3, 1, 1, 1)
        self.customExpXNumIntLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXNumIntLab.setObjectName("customExpXNumIntLab")
        self.customExpXConfGrid.addWidget(self.customExpXNumIntLab, 2, 0, 1, 1)
        self.customExpXOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXOffDurNumDbl.setObjectName("customExpXOffDurNumDbl")
        self.customExpXConfGrid.addWidget(self.customExpXOffDurNumDbl, 4, 1, 1, 1)
        self.customExpXMultiIntCheck = QtWidgets.QCheckBox(self.customExpXPage)
        self.customExpXMultiIntCheck.setObjectName("customExpXMultiIntCheck")
        self.customExpXConfGrid.addWidget(self.customExpXMultiIntCheck, 1, 0, 1, 1)
        self.customExpXlab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXlab.setObjectName("customExpXlab")
        self.customExpXConfGrid.addWidget(self.customExpXlab, 0, 0, 1, 1)
        self.customExpXStartOnCheck = QtWidgets.QCheckBox(self.customExpXPage)
        self.customExpXStartOnCheck.setObjectName("customExpXStartOnCheck")
        self.customExpXConfGrid.addWidget(self.customExpXStartOnCheck, 5, 0, 1, 1)
        self.customExpXNumIntNumDbl = QtWidgets.QSpinBox(self.customExpXPage)
        self.customExpXNumIntNumDbl.setObjectName("customExpXNumIntNumDbl")
        self.customExpXConfGrid.addWidget(self.customExpXNumIntNumDbl, 2, 1, 1, 1)
        self.customExpXOffDurLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXOffDurLab.setObjectName("customExpXOffDurLab")
        self.customExpXConfGrid.addWidget(self.customExpXOffDurLab, 4, 0, 1, 1)
        self.customExpXOnDurLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXOnDurLab.setObjectName("customExpXOnDurLab")
        self.customExpXConfGrid.addWidget(self.customExpXOnDurLab, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpXConfGrid.addItem(spacerItem6, 3, 2, 1, 1)
        self.customExpXConfGrid.setColumnStretch(0, 1)
        self.customExpXConfGrid.setColumnStretch(1, 2)
        self.customExpXConfGrid.setColumnStretch(2, 2)
        self.verticalLayout_2.addLayout(self.customExpXConfGrid)
        self.customExpXWFGrid = QtWidgets.QGridLayout()
        self.customExpXWFGrid.setObjectName("customExpXWFGrid")
        self.customExpXAmplNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXAmplNumDbl.setObjectName("customExpXAmplNumDbl")
        self.customExpXWFGrid.addWidget(self.customExpXAmplNumDbl, 1, 2, 1, 1)
        self.customExpXWFLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXWFLab.setObjectName("customExpXWFLab")
        self.customExpXWFGrid.addWidget(self.customExpXWFLab, 0, 0, 1, 1)
        self.customExpXFreqLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXFreqLab.setObjectName("customExpXFreqLab")
        self.customExpXWFGrid.addWidget(self.customExpXFreqLab, 0, 1, 1, 1)
        self.customExpXAmplLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXAmplLab.setObjectName("customExpXAmplLab")
        self.customExpXWFGrid.addWidget(self.customExpXAmplLab, 0, 2, 1, 1)
        self.customExpXFreqNumDbl = QtWidgets.QDoubleSpinBox(self.customExpXPage)
        self.customExpXFreqNumDbl.setObjectName("customExpXFreqNumDbl")
        self.customExpXWFGrid.addWidget(self.customExpXFreqNumDbl, 1, 1, 1, 1)
        self.customExpXWFCmb = QtWidgets.QComboBox(self.customExpXPage)
        self.customExpXWFCmb.setObjectName("customExpXWFCmb")
        self.customExpXWFGrid.addWidget(self.customExpXWFCmb, 1, 0, 1, 1)
        self.customExpXEqForceVsMaxLine = QtWidgets.QLineEdit(self.customExpXPage)
        self.customExpXEqForceVsMaxLine.setObjectName("customExpXEqForceVsMaxLine")
        self.customExpXWFGrid.addWidget(self.customExpXEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpXEqForceVsMaxLab = QtWidgets.QLabel(self.customExpXPage)
        self.customExpXEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpXEqForceVsMaxLab.setObjectName("customExpXEqForceVsMaxLab")
        self.customExpXWFGrid.addWidget(self.customExpXEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpXWFGrid.setColumnStretch(0, 2)
        self.customExpXWFGrid.setColumnStretch(1, 1)
        self.customExpXWFGrid.setColumnStretch(2, 1)
        self.customExpXWFGrid.setColumnStretch(3, 1)
        self.verticalLayout_2.addLayout(self.customExpXWFGrid)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.customExpAxisStack.addWidget(self.customExpXPage)
        self.customExpYPage = QtWidgets.QWidget()
        self.customExpYPage.setObjectName("customExpYPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.customExpYPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.customExpYConfGrid = QtWidgets.QGridLayout()
        self.customExpYConfGrid.setObjectName("customExpYConfGrid")
        self.customExpYNumIntNumDbl = QtWidgets.QSpinBox(self.customExpYPage)
        self.customExpYNumIntNumDbl.setObjectName("customExpYNumIntNumDbl")
        self.customExpYConfGrid.addWidget(self.customExpYNumIntNumDbl, 2, 1, 1, 1)
        self.customExpYOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYOnDurNumDbl.setObjectName("customExpYOnDurNumDbl")
        self.customExpYConfGrid.addWidget(self.customExpYOnDurNumDbl, 3, 1, 1, 1)
        self.customExpYOffDurLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYOffDurLab.setObjectName("customExpYOffDurLab")
        self.customExpYConfGrid.addWidget(self.customExpYOffDurLab, 4, 0, 1, 1)
        self.customExpYStartOnCheck = QtWidgets.QCheckBox(self.customExpYPage)
        self.customExpYStartOnCheck.setObjectName("customExpYStartOnCheck")
        self.customExpYConfGrid.addWidget(self.customExpYStartOnCheck, 5, 0, 1, 1)
        self.customExpYOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYOffDurNumDbl.setObjectName("customExpYOffDurNumDbl")
        self.customExpYConfGrid.addWidget(self.customExpYOffDurNumDbl, 4, 1, 1, 1)
        self.customExpYNumIntLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYNumIntLab.setObjectName("customExpYNumIntLab")
        self.customExpYConfGrid.addWidget(self.customExpYNumIntLab, 2, 0, 1, 1)
        self.customExpYlab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYlab.setObjectName("customExpYlab")
        self.customExpYConfGrid.addWidget(self.customExpYlab, 0, 0, 1, 1)
        self.customExpYOnDurLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYOnDurLab.setObjectName("customExpYOnDurLab")
        self.customExpYConfGrid.addWidget(self.customExpYOnDurLab, 3, 0, 1, 1)
        self.customExpYMultiIntCheck = QtWidgets.QCheckBox(self.customExpYPage)
        self.customExpYMultiIntCheck.setObjectName("customExpYMultiIntCheck")
        self.customExpYConfGrid.addWidget(self.customExpYMultiIntCheck, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpYConfGrid.addItem(spacerItem7, 3, 2, 1, 1)
        self.customExpYConfGrid.setColumnStretch(0, 1)
        self.customExpYConfGrid.setColumnStretch(1, 2)
        self.customExpYConfGrid.setColumnStretch(2, 2)
        self.verticalLayout_4.addLayout(self.customExpYConfGrid)
        self.customExpYWFGrid = QtWidgets.QGridLayout()
        self.customExpYWFGrid.setObjectName("customExpYWFGrid")
        self.customExpYAmplNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYAmplNumDbl.setObjectName("customExpYAmplNumDbl")
        self.customExpYWFGrid.addWidget(self.customExpYAmplNumDbl, 1, 2, 1, 1)
        self.customExpYWFLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYWFLab.setObjectName("customExpYWFLab")
        self.customExpYWFGrid.addWidget(self.customExpYWFLab, 0, 0, 1, 1)
        self.customExpYFreqLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYFreqLab.setObjectName("customExpYFreqLab")
        self.customExpYWFGrid.addWidget(self.customExpYFreqLab, 0, 1, 1, 1)
        self.customExpYAmplLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYAmplLab.setObjectName("customExpYAmplLab")
        self.customExpYWFGrid.addWidget(self.customExpYAmplLab, 0, 2, 1, 1)
        self.customExpYFreqNumDbl = QtWidgets.QDoubleSpinBox(self.customExpYPage)
        self.customExpYFreqNumDbl.setObjectName("customExpYFreqNumDbl")
        self.customExpYWFGrid.addWidget(self.customExpYFreqNumDbl, 1, 1, 1, 1)
        self.customExpYWFCmb = QtWidgets.QComboBox(self.customExpYPage)
        self.customExpYWFCmb.setObjectName("customExpYWFCmb")
        self.customExpYWFGrid.addWidget(self.customExpYWFCmb, 1, 0, 1, 1)
        self.customExpYEqForceVsMaxLine = QtWidgets.QLineEdit(self.customExpYPage)
        self.customExpYEqForceVsMaxLine.setObjectName("customExpYEqForceVsMaxLine")
        self.customExpYWFGrid.addWidget(self.customExpYEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpYEqForceVsMaxLab = QtWidgets.QLabel(self.customExpYPage)
        self.customExpYEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpYEqForceVsMaxLab.setObjectName("customExpYEqForceVsMaxLab")
        self.customExpYWFGrid.addWidget(self.customExpYEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpYWFGrid.setColumnStretch(0, 2)
        self.customExpYWFGrid.setColumnStretch(1, 1)
        self.customExpYWFGrid.setColumnStretch(2, 1)
        self.customExpYWFGrid.setColumnStretch(3, 1)
        self.verticalLayout_4.addLayout(self.customExpYWFGrid)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.customExpAxisStack.addWidget(self.customExpYPage)
        self.customExpZPage = QtWidgets.QWidget()
        self.customExpZPage.setObjectName("customExpZPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.customExpZPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.customExpZConfGrid = QtWidgets.QGridLayout()
        self.customExpZConfGrid.setObjectName("customExpZConfGrid")
        self.customExpZMultiIntCheck = QtWidgets.QCheckBox(self.customExpZPage)
        self.customExpZMultiIntCheck.setObjectName("customExpZMultiIntCheck")
        self.customExpZConfGrid.addWidget(self.customExpZMultiIntCheck, 1, 0, 1, 1)
        self.customExpZOnDurLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZOnDurLab.setObjectName("customExpZOnDurLab")
        self.customExpZConfGrid.addWidget(self.customExpZOnDurLab, 3, 0, 1, 1)
        self.customExpZOnDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZOnDurNumDbl.setObjectName("customExpZOnDurNumDbl")
        self.customExpZConfGrid.addWidget(self.customExpZOnDurNumDbl, 3, 1, 1, 1)
        self.customExpZOffDurLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZOffDurLab.setObjectName("customExpZOffDurLab")
        self.customExpZConfGrid.addWidget(self.customExpZOffDurLab, 4, 0, 1, 1)
        self.customExpZOffDurNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZOffDurNumDbl.setObjectName("customExpZOffDurNumDbl")
        self.customExpZConfGrid.addWidget(self.customExpZOffDurNumDbl, 4, 1, 1, 1)
        self.customExpZStartOnCheck = QtWidgets.QCheckBox(self.customExpZPage)
        self.customExpZStartOnCheck.setObjectName("customExpZStartOnCheck")
        self.customExpZConfGrid.addWidget(self.customExpZStartOnCheck, 5, 0, 1, 1)
        self.customExpZNumIntLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZNumIntLab.setObjectName("customExpZNumIntLab")
        self.customExpZConfGrid.addWidget(self.customExpZNumIntLab, 2, 0, 1, 1)
        self.customExpZNumIntNumDbl = QtWidgets.QSpinBox(self.customExpZPage)
        self.customExpZNumIntNumDbl.setObjectName("customExpZNumIntNumDbl")
        self.customExpZConfGrid.addWidget(self.customExpZNumIntNumDbl, 2, 1, 1, 1)
        self.customExpZlab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZlab.setObjectName("customExpZlab")
        self.customExpZConfGrid.addWidget(self.customExpZlab, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.customExpZConfGrid.addItem(spacerItem8, 3, 2, 1, 1)
        self.customExpZConfGrid.setColumnStretch(0, 1)
        self.customExpZConfGrid.setColumnStretch(1, 2)
        self.customExpZConfGrid.setColumnStretch(2, 2)
        self.verticalLayout_5.addLayout(self.customExpZConfGrid)
        self.customExpZWFGrid = QtWidgets.QGridLayout()
        self.customExpZWFGrid.setObjectName("customExpZWFGrid")
        self.customExpZAmplNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZAmplNumDbl.setObjectName("customExpZAmplNumDbl")
        self.customExpZWFGrid.addWidget(self.customExpZAmplNumDbl, 1, 2, 1, 1)
        self.customExpZWFLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZWFLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZWFLab.setObjectName("customExpZWFLab")
        self.customExpZWFGrid.addWidget(self.customExpZWFLab, 0, 0, 1, 1)
        self.customExpZFreqLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZFreqLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZFreqLab.setObjectName("customExpZFreqLab")
        self.customExpZWFGrid.addWidget(self.customExpZFreqLab, 0, 1, 1, 1)
        self.customExpZAmplLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZAmplLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZAmplLab.setObjectName("customExpZAmplLab")
        self.customExpZWFGrid.addWidget(self.customExpZAmplLab, 0, 2, 1, 1)
        self.customExpZFreqNumDbl = QtWidgets.QDoubleSpinBox(self.customExpZPage)
        self.customExpZFreqNumDbl.setObjectName("customExpZFreqNumDbl")
        self.customExpZWFGrid.addWidget(self.customExpZFreqNumDbl, 1, 1, 1, 1)
        self.customExpZWFCmb = QtWidgets.QComboBox(self.customExpZPage)
        self.customExpZWFCmb.setObjectName("customExpZWFCmb")
        self.customExpZWFGrid.addWidget(self.customExpZWFCmb, 1, 0, 1, 1)
        self.customExpZEqForceVsMaxLine = QtWidgets.QLineEdit(self.customExpZPage)
        self.customExpZEqForceVsMaxLine.setObjectName("customExpZEqForceVsMaxLine")
        self.customExpZWFGrid.addWidget(self.customExpZEqForceVsMaxLine, 1, 3, 1, 1)
        self.customExpZEqForceVsMaxLab = QtWidgets.QLabel(self.customExpZPage)
        self.customExpZEqForceVsMaxLab.setAlignment(QtCore.Qt.AlignCenter)
        self.customExpZEqForceVsMaxLab.setObjectName("customExpZEqForceVsMaxLab")
        self.customExpZWFGrid.addWidget(self.customExpZEqForceVsMaxLab, 0, 3, 1, 1)
        self.customExpZWFGrid.setColumnStretch(0, 2)
        self.customExpZWFGrid.setColumnStretch(1, 1)
        self.customExpZWFGrid.setColumnStretch(2, 1)
        self.customExpZWFGrid.setColumnStretch(3, 1)
        self.verticalLayout_5.addLayout(self.customExpZWFGrid)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.customExpAxisStack.addWidget(self.customExpZPage)
        self.verticalLayout_12.addWidget(self.customExpAxisStack)
        self.customExpStartBtn = QtWidgets.QPushButton(self.custExpTab)
        self.customExpStartBtn.setObjectName("customExpStartBtn")
        self.verticalLayout_12.addWidget(self.customExpStartBtn)
        self.modTabs.addTab(self.custExpTab, "")
        self.posNmodHor.addWidget(self.modTabs)
        self.posNmodHor.setStretch(0, 8)
        self.posNmodHor.setStretch(1, 1)
        self.posNmodHor.setStretch(2, 15)
        self.sysCtrlVert.addLayout(self.posNmodHor)
        self.sysCtrlVert.setStretch(0, 7)
        self.sysCtrlVert.setStretch(1, 4)
        self.horizontalLayout.addLayout(self.sysCtrlVert)
        MainWindow.setCentralWidget(self.mainGuiHor)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 21))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.plotTabs.setCurrentIndex(0)
        self.sig3selCmb.setCurrentIndex(2)
        self.sig2selCmb.setCurrentIndex(1)
        self.ps2selCmb.setCurrentIndex(1)
        self.ps2selCmb_2.setCurrentIndex(2)
        self.fbToolBox.setCurrentIndex(0)
        self.modTabs.setCurrentIndex(0)
        self.calibStack.setCurrentIndex(1)
        self.customExpAxisStack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connBox.setTitle(_translate("MainWindow", "Connection"))
        self.ipAddLab.setText(_translate("MainWindow", "IP address"))
        self.portLab.setText(_translate("MainWindow", "Port"))
        self.connectBtn.setText(_translate("MainWindow", "CONNECT"))
        self.saveBox.setTitle(_translate("MainWindow", "Save settings"))
        self.dataDirLab.setText(_translate("MainWindow", "Data directory"))
        self.dataDirBtn.setText(_translate("MainWindow", "Browse..."))
        self.logDirLab.setText(_translate("MainWindow", "Log directory"))
        self.logDirBtn.setText(_translate("MainWindow", "Browse"))
        self.logNameLab.setText(_translate("MainWindow", "Log file name"))
        self.parDirLab.setText(_translate("MainWindow", "Param.s directory"))
        self.parDirBtn.setText(_translate("MainWindow", "Browse"))
        self.parNameLab.setText(_translate("MainWindow", "Param.s file name"))
        self.parSaveBtn.setText(_translate("MainWindow", "Save Param.s"))
        self.parLoadBtn.setText(_translate("MainWindow", "Load Param.s"))
        self.lockFbBtn.setText(_translate("MainWindow", "LOCK FEED-BACK"))
        self.sig3selCmb.setItemText(0, _translate("MainWindow", "X"))
        self.sig3selCmb.setItemText(1, _translate("MainWindow", "Y"))
        self.sig3selCmb.setItemText(2, _translate("MainWindow", "Z"))
        self.sig2selCmb.setItemText(0, _translate("MainWindow", "X"))
        self.sig2selCmb.setItemText(1, _translate("MainWindow", "Y"))
        self.sig2selCmb.setItemText(2, _translate("MainWindow", "Z"))
        self.scaleSig1Btn.setText(_translate("MainWindow", "SCALE"))
        self.autoScaleSig1Check.setText(_translate("MainWindow", "Auto scale"))
        self.scaleSig3Btn.setText(_translate("MainWindow", "SCALE"))
        self.scaleSig2Btn.setText(_translate("MainWindow", "SCALE"))
        self.autoScaleSig2Check.setText(_translate("MainWindow", "Auto scale"))
        self.autScaleSig3Check.setText(_translate("MainWindow", "Auto scale"))
        self.sig1selCmb.setItemText(0, _translate("MainWindow", "X"))
        self.sig1selCmb.setItemText(1, _translate("MainWindow", "Y"))
        self.sig1selCmb.setItemText(2, _translate("MainWindow", "Z"))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.signalTab), _translate("MainWindow", "Signals"))
        self.autoScalePs2Check.setText(_translate("MainWindow", "Auto scale"))
        self.ps2selCmb.setItemText(0, _translate("MainWindow", "X"))
        self.ps2selCmb.setItemText(1, _translate("MainWindow", "Y"))
        self.ps2selCmb.setItemText(2, _translate("MainWindow", "Z"))
        self.scalePs3Btn.setText(_translate("MainWindow", "SCALE"))
        self.scalePs1Btn.setText(_translate("MainWindow", "SCALE"))
        self.ps2selCmb_2.setItemText(0, _translate("MainWindow", "X"))
        self.ps2selCmb_2.setItemText(1, _translate("MainWindow", "Y"))
        self.ps2selCmb_2.setItemText(2, _translate("MainWindow", "Z"))
        self.autoScalePs1Check.setText(_translate("MainWindow", "Auto scale"))
        self.scalePs2Btn.setText(_translate("MainWindow", "SCALE"))
        self.autoScalePs3Check.setText(_translate("MainWindow", "Auto scale"))
        self.ps1selCmb.setItemText(0, _translate("MainWindow", "X"))
        self.ps1selCmb.setItemText(1, _translate("MainWindow", "Y"))
        self.ps1selCmb.setItemText(2, _translate("MainWindow", "Z"))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.psTab), _translate("MainWindow", "Power spectrums"))
        self.zPLab.setText(_translate("MainWindow", "P"))
        self.zILab.setText(_translate("MainWindow", "I"))
        self.xyILab.setText(_translate("MainWindow", "I"))
        self.xyPLab.setText(_translate("MainWindow", "P"))
        self.xyLab.setText(_translate("MainWindow", "X-Y"))
        self.zLab.setText(_translate("MainWindow", "Z"))
        self.setFbBtn.setText(_translate("MainWindow", "SET PI PARAMETERS"))
        self.xyFbOnCheck.setText(_translate("MainWindow", "FB ON"))
        self.zFbOnCheck.setText(_translate("MainWindow", "FB ON"))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.piPage), _translate("MainWindow", "PI controller parameters"))
        self.xSpeedTrapPadLab.setText(_translate("MainWindow", "X speed [nm/s]"))
        self.ySpeedTrapPadLab.setText(_translate("MainWindow", "Y speed [nm/s]"))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.padPage), _translate("MainWindow", "Optical trap control pad"))
        self.zOffSetLab.setText(_translate("MainWindow", "Z offset"))
        self.yOffSetLab.setText(_translate("MainWindow", "Y offset"))
        self.xOffSetLab.setText(_translate("MainWindow", "X offset"))
        self.fbToolBox.setItemText(self.fbToolBox.indexOf(self.otherPage), _translate("MainWindow", "Other parameters"))
        self.passiveCalDurLab.setText(_translate("MainWindow", "Duration [s]"))
        self.passiveCalMaxFreqLab.setText(_translate("MainWindow", "Max. frequency [Hz]"))
        self.passiveLab.setText(_translate("MainWindow", "Passive"))
        self.passiveCalAvgLav.setText(_translate("MainWindow", "Averages"))
        self.passiveCalStartBtn.setText(_translate("MainWindow", "START"))
        self.activeCalYLab.setText(_translate("MainWindow", "Y"))
        self.activeCalZLab.setText(_translate("MainWindow", "Z"))
        self.activeCalAmpLab.setText(_translate("MainWindow", "Ampl [nm]"))
        self.activeCalLab.setText(_translate("MainWindow", "Active"))
        self.activeCalXLab.setText(_translate("MainWindow", "X"))
        self.activeCalFreqLab.setText(_translate("MainWindow", "Freq [Hz]"))
        self.activeCalDurLab.setText(_translate("MainWindow", "Duration [s]"))
        self.activeCalMaxFreqLab.setText(_translate("MainWindow", "Max freq [Hz]"))
        self.activeCalAvgLab.setText(_translate("MainWindow", "Averages"))
        self.activeCalStartBtn.setText(_translate("MainWindow", "START"))
        self.genParBox.setTitle(_translate("MainWindow", "General Params"))
        self.dynViscLab.setText(_translate("MainWindow", "Dyn. Visc."))
        self.radiusLab.setText(_translate("MainWindow", "Radius [um]"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Results"))
        self.kxLab.setText(_translate("MainWindow", "kx"))
        self.kyLab.setText(_translate("MainWindow", "ky"))
        self.kzLab.setText(_translate("MainWindow", "kz"))
        self.SxLab.setText(_translate("MainWindow", "Sx"))
        self.SyLab.setText(_translate("MainWindow", "Sy"))
        self.SzLab.setText(_translate("MainWindow", "Sz"))
        self.modTabs.setTabText(self.modTabs.indexOf(self.calibTab), _translate("MainWindow", "Calibration"))
        self.stdExpXLab.setText(_translate("MainWindow", "X"))
        self.stdExpSetPointLab.setText(_translate("MainWindow", "Set point [nm]"))
        self.stdExpAxisLab.setText(_translate("MainWindow", "Axis"))
        self.stdExpZLab.setText(_translate("MainWindow", "Z"))
        self.stdExpYLab.setText(_translate("MainWindow", "Y"))
        self.stdExpEqForceVsMaxLab.setText(_translate("MainWindow", "S.P. Force [pN]/Max force[pN]"))
        self.stdExpDurLab.setText(_translate("MainWindow", "Duration [s]"))
        self.fbSchedBox.setTitle(_translate("MainWindow", "Feed Back time scheduler"))
        self.fbSchedNumIntLab.setText(_translate("MainWindow", "Number of intervals"))
        self.fbSchedOnDurLab.setText(_translate("MainWindow", "On part dur. [s]"))
        self.fbSchedOffDurLab.setText(_translate("MainWindow", "Off part dur. [s]"))
        self.fbSchedStartOnCheck.setText(_translate("MainWindow", "Start On"))
        self.stdExpStartBtn.setText(_translate("MainWindow", "START"))
        self.modTabs.setTabText(self.modTabs.indexOf(self.stdExpTab), _translate("MainWindow", "Standard experiment"))
        self.customExpXNumIntLab.setText(_translate("MainWindow", "Number of intervals"))
        self.customExpXMultiIntCheck.setText(_translate("MainWindow", "Multi interval"))
        self.customExpXlab.setText(_translate("MainWindow", "X axis"))
        self.customExpXStartOnCheck.setText(_translate("MainWindow", "Start On"))
        self.customExpXOffDurLab.setText(_translate("MainWindow", "Off part duration [s]"))
        self.customExpXOnDurLab.setText(_translate("MainWindow", "On part duration [s]"))
        self.customExpXWFLab.setText(_translate("MainWindow", "Waveform type"))
        self.customExpXFreqLab.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.customExpXAmplLab.setText(_translate("MainWindow", "Amplitude [nm]"))
        self.customExpXEqForceVsMaxLab.setText(_translate("MainWindow", "Force ampl. [pN]/Max. force [pN]"))
        self.customExpYOffDurLab.setText(_translate("MainWindow", "Off part duration [s]"))
        self.customExpYStartOnCheck.setText(_translate("MainWindow", "Start On"))
        self.customExpYNumIntLab.setText(_translate("MainWindow", "Number of intervals"))
        self.customExpYlab.setText(_translate("MainWindow", "Y axis"))
        self.customExpYOnDurLab.setText(_translate("MainWindow", "On part duration [s]"))
        self.customExpYMultiIntCheck.setText(_translate("MainWindow", "Multi interval"))
        self.customExpYWFLab.setText(_translate("MainWindow", "Waveform type"))
        self.customExpYFreqLab.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.customExpYAmplLab.setText(_translate("MainWindow", "Amplitude [nm]"))
        self.customExpYEqForceVsMaxLab.setText(_translate("MainWindow", "Force ampl. [pN]/Max. force [pN]"))
        self.customExpZMultiIntCheck.setText(_translate("MainWindow", "Multi interval"))
        self.customExpZOnDurLab.setText(_translate("MainWindow", "On part duration [s]"))
        self.customExpZOffDurLab.setText(_translate("MainWindow", "Off part duration [s]"))
        self.customExpZStartOnCheck.setText(_translate("MainWindow", "Start On"))
        self.customExpZNumIntLab.setText(_translate("MainWindow", "Number of intervals"))
        self.customExpZlab.setText(_translate("MainWindow", "Z axis"))
        self.customExpZWFLab.setText(_translate("MainWindow", "Waveform type"))
        self.customExpZFreqLab.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.customExpZAmplLab.setText(_translate("MainWindow", "Amplitude [nm]"))
        self.customExpZEqForceVsMaxLab.setText(_translate("MainWindow", "Force ampl. [pN]/Max. force [pN]"))
        self.customExpStartBtn.setText(_translate("MainWindow", "START"))
        self.modTabs.setTabText(self.modTabs.indexOf(self.custExpTab), _translate("MainWindow", "Custom experiment"))

