REST = ['START_MODSAFE',0]
NEUTRAL = ['START_MODSAFE',1]
FDBK = ['START_MODSAFE',2]
LIN = ['START_MODSAFE',3]
SIN = ['START_MODSAFE',4]

TYPES = {'Vconst':LIN,'Fconst':FDBK,'Pconst':NEUTRAL}

from libs.epzInterpreter import Commander


'''
GET_DEVICE_TYPE:a
GET_EXT_ADC_RANGE:b
GET_EXT_ADC_VINMIN:c
GET_EXT_ADC_VINMAX:d
GET_INT_ADC_RESOLUTION:e
IS_ADCBUF_PRESENT:f
GET_ADCBUF_VINMIN:g
GET_ADCBUF_VINMAX:h
GET_ADCBUF_VOUTMIN:i
GET_ADCBUF_VOUTMAX:j
GET_DAC_VREF:k
GET_DAC_POLARITY:l
'''